MaaAssistantArknights/MaaAssistantArknights

- src/MeoAsstGui/Helper/AsstProxy.cs
- src/MeoAsstGui/Helper/ScrollViewerBinding.cs
- src/MeoAsstGui/Helper/ToastNotification.cs
- src/MeoAsstGui/Helper/ViewStatusStorage.cs
- src/MeoAsstGui/MeoAsstGui.csproj
- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
- src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
- src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
- src/MeoAsstGui/Views/SettingsView.xaml
* 更换微软的 Notification 为兼容多版本 Windows 的 Notification.WPF 通知
* 修复 AsstProxy 中初始化异常时 ShowMessageBox 会导致程序未响应的问题
* 给当前使用的 ShowMessageBox 消息框加上消息图标
* 增加了主界面上各个设置数值的保存
* 更换了设置页面滚动和菜单列表定位方法
* 优化一点 C# 代码格式冗余
在之前公招出了高资、因为 MAA 使用 win10 通知、win7 系统不兼容就直接崩了、接着一不小心没把标签选上……
于是就决定插手改改通知了_(:з」∠)_ 
摸了将近一周才改了这点、不过最近貌似准备换成 WEB 界面、感觉这些更改可有可无了_(xз」∠)_ 
换了个通用的 wpf 通知、除了不像 win10 可以把通知存在通知中心、其它功能效果基本差不多
可以参考开源项目 Notification.WPF https://github.com/Platonenkov/Notification.Wpf
> 优化通知提示和界面部分功能

- src/MeoAsstGui/Helper/AsstProxy.cs
- src/MeoAsstGui/Helper/ScrollViewerBinding.cs
- src/MeoAsstGui/Helper/ToastNotification.cs
- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
- src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
* 修复 toast通知提示在非UI线程调用引起程式懵了的问题
* 修复 OTA 更新 stages.json 地址错误的问题
* 新增 3个OTA更新下载地址CDN接口，获取失败会尝试从下一个接口获取
* 新增 更新提示的 toast 通知样式
* 更改 部分 toast 通知样式
* 更改 设置页面滚动条滚动定位计算
* 调整 GUI 一些代码排版格式
记得调用界面相关的操作时、要放到 UI 线程里处理（嗯嗯嗯记住了 （下次还是忘记）
toast通知调用应该不会再崩溃了（或许大概肯定吧
看了OTA更新部分、用 Dictionary 类型遍历一样的内容有点大材小用、而且发现有一个文件路径没改导致不能获取到更新、于是换了个符合需求的 List 类型、避免出现同样的问题
顺便增加 3个 OTA更新文件用的接口、基本上能保证更新稳定性、但我这用的时代眼泪Win7系统、连获取更新信息都不行、所以没有实际测试过、理论上应该没问题、测试只好留给大佬了……
今天又开始上班、有其他界面问题、有空再看（摆烂……\_(:з」∠)_
> fix.修复界面toast通知线程调用时崩溃问题和一些其他改进

- resource/config.json
- src/MeoAssistant/AsstDef.h
- src/MeoAssistant/AsstUtils.hpp
- src/MeoAssistant/Controller.cpp
- src/MeoAssistant/GeneralConfiger.cpp
微软已经实现了WSA截屏所需要的接口，但是WSA似乎每个app是运行在独立的屏幕上的，故`screencap`和`input` 要添加`-d` 参数指定屏幕。
在`screencap`和`input`命令中增加了`[DisplayId]`用于表示屏幕ID的支持。
在`adb_connect`中添加了明日方舟的`display_id`的获取。
增加了一个实验性的国服的WSA支持，窗口`class`是包名，`title`是`app`的名称。
`display_id`获取以及根据窗口句柄找WSA需要针对不同服进一步适配（暂时没下外服包确认）。
> [experimental] feat. 增加WSA支持

- resource/combat_recruit.json
- src/MeoAssistant/AsstBattleDef.h
- src/MeoAssistant/CombatRecruitConfiger.cpp
- src/MeoAssistant/CombatRecruitConfiger.h
- src/MeoAssistant/OcrImageAnalyzer.cpp
- src/MeoAssistant/OcrImageAnalyzer.h
- src/MeoAssistant/Resource.cpp
- src/MeoAssistant/Resource.h
- src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
- src/MeoAssistant/RoguelikeRecruitTaskPlugin.cpp
- src/MeoAssistant/StageDropsTaskPlugin.cpp
主要修改：
具体的做法是：
1. 取当前页所有干员`visible_opers`；
2. 识别左上角干员的名字并在`CombatRecruitConfiger`中找到他的`level`；
3. 取`visiable_opers`中在`m_opers`中的所有干员`required_opers`；
4. 取`required_opers`中小于等于`level`的所有干员`available_opers`；
5. 取`available_opers`中`m_opers`（用户设置）优先级最高的`favour_oper`。
最后得到的`favour_oper`即为招募的干员。
（另外我写了识别初始四星临时招募的代码，但是不在这个PR里。感觉用这个队伍成功率会比近卫辅助医疗高一些吧，大概）
在干员被击败后尝试释放格子。具体做法是：
1. 检测到的干员数增加时，先对冷却中的干员遍历寻找其曾经放置的格子并释放，不够则继续对不在冷却的干员重复这个步骤
这个做法对召唤物很不友好（有召唤物的情况应该有bug），如果觉得不好就删了吧（
> fix.修复某些情况下肉鸽选人希望不够的情况

- resource/tasks.json
尝试修复 #340 中提到的问题，增加肉鸽的掉落物匹配的阈值。
> fix.修复某些情况下肉鸽掉落物识别错误的问题

- src/MeoAssistant/AbstractConfiger.cpp
- src/MeoAssistant/AsstCaller.cpp
- src/MeoAssistant/AsstUtils.hpp
- src/MeoAssistant/Logger.hpp
gbk_2_utf8 改为 ansi_to_utf8
utf8_to_gbk 改为 utf8_to_ansi
在这些函数中的memset调用统一改为类似 memset(ptr, 0, sizeof(ptr[0]) * 数组长度) 的形式
相关PR #499
> 重命名了asst::utils下的字符串编码转换函数，修复了ansi_to_utf8的wstr数组初始化不完全的问题

- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
解决#822 的问题，调cmd执行命令，但不再判定模拟器程序是否存在，地址出错会继续运行直至连不上模拟器
WSA能正常启动（C:\Users\cvcgl\AppData\Local\Microsoft\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\WsaClient.exe /launch wsa://com.hypergryph.arknights）
> 解决无法带命令启动模拟器

- src/MeoAssistant/StartUpTask.cpp
StartUp 任务每次重试间隔过短, 如果在无法识别的界面 (如 `StartUpConnectingFlag.png` 进度条走完之后, 进入主界面之前的小提示部分) 停留过长会导致重试次数耗尽, 任务退出, 没有处理后面出现的 `"TodaysSupplies"` 和 `"CloseAnno"`. 
表现为卡死在签到页面, 无法进行后续任务.
ref: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1084
> 降低因进入主界面时间太长 StartUp 提前退出的概率

- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
踢掉了cmd，WSA和蓝叠Hyper-V测试可用
请告知用户不要在模拟器路径两侧加引号
我之前写了一堆什么屎山……
> perf.简化启动模拟器的逻辑

- src/MeoAssistant/AsstUtils.hpp
- src/MeoAssistant/Logger.hpp
如果容器能用 `for (auto const& element : container)` 这种范围 for 语句遍历, 而且元素也是可以打印的, 那这个容器也能直接作为 log 函数的参数
> 在 log 函数的参数中支持 range-expression

- tools/MaaBuilder/Build.Job.Changelog.cs
之前的 _**弹窗 CHANGELOG**_ 和 _**tg 群 bot**_ 并不能正确给 contributor 加上链接的问题，给 CHANGELOG 的生成做一个小优化
> chore: 使 CHANGELOG 里的贡献者名字自动带上链接

- resource/tasks.json
- src/MeoAssistant/RoguelikeTask.cpp
- src/MeoAsstGui/Helper/AsstProxy.cs
- src/MeoAsstGui/Resources/Localizations/en-us.xaml
- src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
- src/MeoAsstGui/Resources/Localizations/ko-kr.xaml
- src/MeoAsstGui/Resources/Localizations/pallas.xaml
- src/MeoAsstGui/Resources/Localizations/zh-cn.xaml
- src/MeoAsstGui/Resources/Localizations/zh-tw.xaml
- src/MeoAsstGui/UserControl/RoguelikeSettingsUserControl.xaml
- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
- src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
主要改动了任务 Roguelike1StageTraderInvestSystem 的逻辑：
- 默认情况下，任务的 next 第一项是 Roguelike1StageTraderInvestSystemEnter（进入投资界面）
- 本次改动为任务添加了 exceededNext (不进行投资，直接购物)
- 当肉鸽投资次数设置为 0 时，会将该任务的 maxTimes 设置为 0，自动进入 exceededNext 逻辑
> feat: 肉鸽投资开关

- src/MeoAsstGui/ViewModels/StartSelfModel.cs
<!-- MODULE:GUI --!>
自己写的bug自己修2.0
fix#1505 ，用户需要在更新后取消勾选开机自启并重新勾选
建议检查一下其他地方有没有目录一类的东西可能带空格没加引号的
> fix. 修复目录带空格时无法自启的问题

- resource/tasks.json
- src/MeoAssistant/AutoRecruitTask.cpp
- src/MeoAssistant/AutoRecruitTask.h
- 仅汇报来自刚招募到干员的槽位或刚刷新了 tags 的槽位, 以防重复汇报
- 修复 tag 组合中同时存在 1, 2 星与 3, 4, 5 星干员时的平均等级计算方法, 低星干员不纳入计算
- 调整自动使用加急许可时的执行顺序
~~好像不用重构也能判断是否汇报, 那就先不重构了~~
> feat: 公招相关调整

- resource/tasks.json
- src/MeoAssistant/AsstBattleDef.h
- src/MeoAssistant/RoguelikeRecruitImageAnalyzer.cpp
- src/MeoAssistant/RoguelikeRecruitTaskPlugin.cpp
- 删除旧逻辑遗留的招募结果排序及 required 字段
- 如果我没理解错：```RoguelikeRecruitImageAnalyzer::analyze``` 是先识别干员，再 ```set_required``` 并 ```sort_result_by_required```，即：```oper_order``` (干员名字列表) 并不影响识别结果，只用于排序。由于后续已经有优先级排序，此处不再需要排序。进而，```required``` 字段也没有必要
- 以下情况自动停止滑动 (fix #1642)：
- 滑动前识别的干员少于8个（初始页面可以显示2列，8个干员）
- 滑动后识别的干员少于4个（滑动后至少能显示1列，4个干员）
- 滑动后识别失败（没有识别结果，通常是干员不可选）
- 滑了没动，任意干员名字的位置没有变化（x 偏移低于阈值20像素）
识别区域如图所示，滑动后至少能显示1列：
> perf: 改进肉鸽招募逻辑

- resource/tasks.json
- src/MeoAssistant/StageDropsImageAnalyzer.cpp
之前在群里提到过的一个想法, 大概就是竖直方向变化减去水平方向变化. 
给图片加一个预处理, 用 Sobel 算符求出偏导数 $\partial_y I$ 和 $\partial_x I$, 因为材料下面的线条是水平的而且只有两个像素粗, 所以减一下把梯度偏太多的像素过滤掉
$$V = \sqrt{(\partial_y I)^2 - (\tan\alpha \cdot \partial_x I)^2},$$
这样只有梯度方向朝上或者朝下的像素可以得出正值, 偏离多于 $\frac{\pi}{2}-\alpha$ 的像素都是负值. 
----
<details><summary>2022-07-20_21-29-36.169_raw.png</summary>
</details>
----
<details><summary>2022-07-24_23-22-10.387_raw.png</summary>
</details>
----
<details><summary>2022-08-14_13-46-36.453_raw.png</summary>
</details>
----
如果出现中间断开一个像素的情况, 可以用水平方向的 `cv::dilate` 填起来 (把每个像素值换成周围一定区域内的最大值), 然后再 `cv::erode` 回去 (可以防止探测出的线条比实际长).
因为边缘检测得到的线条有四个像素宽, 在竖直方向允许 `cv::erode` 成两个像素, 可以尽量排除干员皮肤中横线的干扰 (感觉不大会有这种干扰吧).
测试集全部都能通过, 但是因为原理不一样, 不知道会不会有意料之外的翻车情况
> perf: 在关卡掉落识别中使用边缘检测判断线条位置

- src/MeoAssistant/AbstractTask.cpp
- src/MeoAssistant/AsstUtils.hpp
抄了一下 boost 的写法
https://github.com/boostorg/core/blob/414dfb466878af427d33b36e6ccf84d21c0e081b/include/boost/core/type_name.hpp#L66-L104
MSVC 上的效果应该只是把 `class ` 前缀去掉了.
话说这两个字段有在什么地方被使用吗
> perf: 使用 demangle 来获得更准确的类型名称

- src/MeoAssistant/Controller.cpp
- src/MeoAsstGui/Helper/AsstProxy.cs
- src/MeoAsstGui/Resources/Localizations/en-us.xaml
- src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
- src/MeoAsstGui/Resources/Localizations/ko-kr.xaml
- src/MeoAsstGui/Resources/Localizations/pallas.xaml
- src/MeoAsstGui/Resources/Localizations/zh-cn.xaml
- src/MeoAsstGui/Resources/Localizations/zh-tw.xaml
- src/MeoAsstGui/UserControl/ConnectSettingsUserControl.xaml
- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
BUG：开启定时任务并设置任务完成后自动关闭模拟器时，仅有第一次定时任务可以成功执行，第二次定时任务只会尝试重连ADB不会自动启动模拟器，重连20次后进入失败状态且任务不会停止，后续定时任务均无法执行。同#1369
REASON：如果在MAA当前与模拟器ADB处于已连接状态时关闭模拟器（如设置定时任务完成后关闭模拟器或手动关闭模拟器），会导致下次任务开始时模拟器只会尝试重连ADB，重连次数耗尽时直接断开连接并停止任务，不会触发自动启动模拟器。
FIX：该PR将ADB重连次数减少为5次，并新增选项在ADB重连次数耗尽时重试任务，此时会尝试启动模拟器后再重新连接ADB，该选项默认关闭。开启该选项后可将MAA定时任务常驻后台，并选择任务完成后自动关闭模拟器，启动模拟器->执行定时任务->关闭模拟器的循环，无需模拟器常驻后台占用资源。
> feat: 新增在ADB重连失败断开连接时重启模拟器重试的选项，默认关闭

- src/MeoAsstGui/Helper/StageActivityInfo.cs
- src/MeoAsstGui/Helper/StageInfo.cs
- src/MeoAsstGui/Helper/StageManager.cs
- src/MeoAsstGui/MeoAsstGui.csproj
- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
- src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
重构并优化关卡选择逻辑：
- 添加 ```StageInfo``` 类
- 继承自 ```CombData``` 类，实现原有的 ```AllStageList``` 功能
- 整合 ```_stageAvailableInfo``` 的相关功能和字段（```Tuple<DayOfWeek[] openDays, string tip>```）
- 可以关联限时活动 ```StageActivityInfo```
- 可以设置隐藏（例如某些关卡仅用于每日关卡提示、不显示在关卡列表）
- 添加 ```StageActivityInfo``` 类
- 用于限时活动（SideStory、故事集或资源收集活动）
- 普通活动结束时，关联的关卡也随之关闭
- 资源收集活动 (```IsResourceCollection == true``` ) 结束时，会继续检查资源关卡的轮换时间
- 添加 ```StageManager``` 类
- 用于管理所有关卡
- 原有的 ```AllStageList``` 和 ```_stageAvailableInfo``` 合并为 ```Dictionary<string, StageInfo> _stages```
- 添加 ```IsStageOpen``` 方法判断关卡是否开放
- 添加 ```GetStageTips``` 方法获取今日关卡提示
- 选择了已关闭的活动关卡时，今日关卡提示会显示 “活动已结束”
- 重构 ```TaskQueueViewModel.UpdateStageList```：
- 原有的 ```AllStageList``` 已移至 ```StageManager``` 类
- 未勾选 “隐藏不开放关卡” 时，只在初始化或选项改变时更新 ```StageList```，```Timer``` 中不再实时更新
- …
> feat: 优化Gui关卡选择逻辑

- src/MeoAssistant/AsstHttp.hpp
- src/MeoAssistant/AsstUtils.hpp
- src/MeoAssistant/AutoRecruitTask.cpp
- src/MeoAssistant/Logger.hpp
- src/MeoAssistant/ReportDataTask.cpp
1. 修复不了 string_split_view 传入左值 char_t 时 _pat 悬垂的问题，传入左值的时候 static_assert false
2. `Response` 类不再从 `std::string` 继承，而是使用一个 `string` 类型的 `m_raw_data`
3. 对于 headers，直接修改 `m_raw_data` 的大小写，不再重新创建 `string`
4. 移除 `view_cast`
5. 增加一些 `noexcept`, `const&`
6. 修正一些 typo
> perf: AsstHttp 的各种优化

- CMakeLists.txt
> chore:修复在Windows下因CMake脚本缺少宏定义导致构建失败的问题

- src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
Depot Recognition Over sees client "how to" add.（CN版では自動で可能だがJPでは手順が一つ増えているので追記） https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1809
> Doc:Depot Recognition Text Tweak

- src/MeoAssistant/StageDropsImageAnalyzer.cpp
原来是我自己写错了, 有些和周围像素相关的处理是不能放在裁剪之后的. 我当时写 #1657 的时候为了方便观察没有裁剪, 所以没发现这个问题
#1817
> fix: 修复关卡掉落识别

- src/MeoAssistant/Assistant.cpp
- src/MeoAssistant/Controller.cpp
- src/MeoAssistant/Controller.h
- src/MeoAsstGui/Helper/AsstProxy.cs
- src/MeoAsstGui/Resources/Localizations/en-us.xaml
- src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
- src/MeoAsstGui/Resources/Localizations/ko-kr.xaml
- src/MeoAsstGui/Resources/Localizations/pallas.xaml
- src/MeoAsstGui/Resources/Localizations/zh-cn.xaml
- src/MeoAsstGui/Resources/Localizations/zh-tw.xaml
- src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
- src/MeoAsstGui/Views/TaskQueueView.xaml
1. `call_command` 不再通过 `m_inited` 来判断是否处于递归；  
增加一个参数 `allow_reconnect` 表示是否允许重连，默认为 `true`，递归时为 `false`；
2. `release()` 函数不再直接调用；
3. 把 `m_inited` 的值和 `m_instance_count` 的增减绑定；  
外部不再直接调用 `m_inited` 和 `m_instance_count`，改为调用 `set_inited(true)` `set_inited(false)`；
4. 修复 UI 上连接模拟器时点击 `停止` 按钮卡顿的问题
> fix: 优化 Controller

- src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
蓝叠模拟器一共有4个进程
关闭模拟器时，只使用killEumlatorbyWindow()会留下两个进程，其中一个内存占用特别大
如果先调用killEumlatorbyWindow()，再调用killEmulator()，就可以把那个内存占用特别大的进程关掉
所以在killEumlatorbyWindow()之后添加了killEmulator()
> fix: 修复关闭模拟器后台进程不完全

- resource/tasks.json
- src/MeoAssistant/Task/FightTask.cpp
1. `LastBattle` 之前没有用上，干脆拿来当作 当前/上次作战 的启动任务
2. 把 `StageBegin` 的 `next` 抽出来（因为它是 `JustReturn` 的不会重试）
@DavidWang19 来看看
> perf: 优化刷理智任务逻辑

- CMakeLists.txt
- src/MeoAssistant/Resource/RecruitConfiger.h
- src/MeoAssistant/Utils/AsstHttp.hpp
- src/MeoAssistant/Utils/AsstUtils.hpp
- src/MeoAssistant/Utils/Logger.hpp
- 添加 POSIX 头文件
- 实现 `std::string` 的 `<=>` 运算符
- 使用兼容的 string_view 构造函数
- 添加 range-v3 依赖
> fix: 修复使用 clang 在 Linux 和 macOS 平台的编译问题

- src/MeoAssistant/Task/Sub/InfrastAbstractTask.cpp
- src/MeoAssistant/Task/Sub/InfrastControlTask.cpp
- src/MeoAssistant/Task/Sub/InfrastDormTask.cpp
- src/MeoAssistant/Task/Sub/InfrastProductionTask.cpp
- src/MeoAssistant/Task/Sub/InfrastReceptionTask.cpp
> perf: 加快相邻排班变化不大时的干员选取速度

- resource/tasks.json
- src/MeoAssistant/Task/StartUpTask.cpp
- src/MeoAssistant/Task/Sub/ProcessTask.cpp
- src/MeoAssistant/Task/Sub/ProcessTask.h
- src/MeoAssistant/TaskData.cpp
- src/MeoAssistant/TaskData.h
允许把某个 task（例如 "A"）当作模板，然后 "B@A" 表示由 "A" 生成的任务。
例如：
在 `tasks.json` 中定义
```jsonc
"A": {
"template": "A.png",
...,
"next": { "N1", "N2", "N3", "N4" }
}
```
- 如果 `tasks.json` 中没有定义任务 "B@A"，那么除了 `next`, `onErrorNext`, `exceededNext`, `reduceOtherTimes` 增加 `B@` 前缀，其余都直接使用任务 "A" 的参数。就是说相当于定义了
```jsonc
"B@A": {
"template": "A.png",
...,
"next": { "B@N1", "B@N2", "B@N3", "B@N4" }
}
```
- 如果 `tasks.json` 中定义了任务 "B@A"，则优先使用 "B@A"（类似 cpp 的模板特化）。
> feat: 增加模板任务逻辑

- src/MeoAssistant/Assistant.cpp
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2331
详细描述见 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2331
手动测试，使用编译的 maa 多次连续点击 “Link Start” 和 “停止”，未出现“任务出错”。
> fix: 修复手动终止任务时有概率出现的“任务出错”

- .github/workflows/dev-build-mac.yml
- CMakeLists.txt
使用 `git describe --tags --dirty --broken --abbrev=40` 的输出
当前如果在 tag 上结果就是 `v4.6.4`, 如果不在 tag 上大概会长这样
```
v4.6.4-58-g96814e1c4ef70c892c31630b8e985e22ff26b948-dirty
```
表示 `HEAD` 在 `v4.6.4` 前面 58 个 commit, hash 是 `9681...`, 有尚未提交的更改
~~坏了 GitHub action 的 checkout 好像是 shallow fetch~~
> chore: 使 CMake 能自动定义 `MAA_VERSION`

- src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
1. 由于 2ddba7f54dba6fe0c12634ed90a2f7a01d98279f 修改了 resource 文件夹的更新逻辑，可以预见：  
**从 `v4.6.5-beta.1` 往后升级版本时会遇到重命名 `resource` 到 `resource.old` 时异常导致闪退。**  
此 pr 对其进行优化。
2. 简化 75200911cf98a5bdde7e3b0b057d2d1725808388 （`fix: 修复下载新版本失败导致闪退的问题`）的逻辑
(此问题是**下载更新文件发生异常时文件流没有正常关闭**导致的）
这块之前好像是 @Puqns67 佬写的（https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/4b818067a9dd7e4085dc95f86145d053d9dc13f1
> perf: 修改 GUI 更新相关逻辑

- .github/workflows/release-ota.yml
- tools/OTAPacker/build.sh
- 在每次发版的时候自动打 20 个 OTA 包并上传至 MaaRelease 的同名 release, 现在包名如 https://github.com/horror-proton/MaaRelease/releases 
- 被删除的文件列在 `deleted.txt` 中, 新版本所有文件的和校验和在 `md5sum.txt` 中
为了正常工作, 需要在 `MaaAssistantArknights/MaaAssistantArknights` 的 Repository secrets 里增加一个名字为 `MAARELEASE_RELEASE` 的项用来保存对 MaaAssistantArknights/MaaRelease 仓库有 release 权限的 token
> chore: 增加 OTA 打包的 action workflow

- .github/workflows/release-ota.yml
inputs.limit 自动触发的话不是默认值而是直接为空, 上次所以按照脚本里面的默认参数只打了 5 个 😿
> chore: 自动触发 release-ota 时设定默认值

- README.md
- README_zh-TW.md
- src/MeoAsstGui/Resources/Localizations/en-us.xaml
- src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
- src/MeoAsstGui/Resources/Localizations/ko-kr.xaml
- src/MeoAsstGui/Resources/Localizations/pallas.xaml
- src/MeoAsstGui/Resources/Localizations/zh-cn.xaml
- src/MeoAsstGui/Resources/Localizations/zh-tw.xaml
- src/MeoAsstGui/UserControl/VersionUpdateSettingsUserControl.xaml
- src/MeoAsstGui/ViewModels/SettingsViewModel.cs
- src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
勾选内测版更新后，在 MaaRelease 仓库中若最新者不是当前版本，则直接使用该版本。
测试版和稳定版检测版本号是否为v开头的版本，内测版不做检查。
> feat: 内测版本更新 GUI 选项

- .github/workflows/release-ota.yml
> chore: OTA 打包时在 MaaRelease 创建新的 commit 和 tag

- .github/workflows/release-nightly-ota.yml
- .github/workflows/release-ota.yml
- tools/OTAPacker/build.sh
脚本还比较丑, 有一些重复的内容, 不过应该勉强能用 (
效果如 https://github.com/horror-proton/MaaRelease/releases 的最新几个 release
可以在 Action tab 里面选择这个 workflow, 然后点右边的 Run workflow, 输入要打的 nightly release 对应的分支名或者 commit SHA 值
> chore: 新增发 nightly 版本的 workflow

- resource/custom_infrast/243_layout_4_times_per_day.json
https://docs.google.com/spreadsheets/d/10Wljo-5TroDXD-7OWVcK1oQP1hGJ_-KYsrzPyfFm5Dg/edit?usp=sharing
具体换班表看这里。版本新增干员之后的例行维护。
> feat: 更新基建作业243一日四换至2022年11月版本

- .github/workflows/release-nightly-ota.yml
不太会写 powershell，快帮我看看
这个 pr 是允许自定义发 nightly 版本的 tag。
例如自定义一个 `v4.6.7-beta.4.0+gddbcbd64` 就过不了旧版本的 isStdVersion，从而可以正常更新
> ci: Allow input nightly tag

- resource/tasks.json
fix #2055
#2055 提到已经可以了，但似乎目前 dev 分支和 master 都不会活用安全屋。
应该是因为 Encounter 中匹配多个选项的时候会优先选择下方的选项？
改了之后在 Encounter 节点中找完 Free 选项就会去找活用安全屋选项，没有才会离开。
> feat: 水月肉鸽支持活用安全屋选项

- resource/tasks.json
- src/MeoAssistant/Controller.cpp
- src/MeoAssistant/Controller.h
- src/MeoAssistant/Task/Plugin/RoguelikeBattleTaskPlugin.cpp
- src/MeoAssistant/Task/Sub/ProcessTask.cpp
- src/MeoAssistant/Task/Sub/ProcessTask.h
1. 增加滑动 interval
2. up 操作延迟 50ms
3. 增加滑动加速度参数 `acceleration_coef`：=0 表示匀速，>0 表示加速，<0 表示减速；超出 [1, -1] 会往反方向滑动一段
顺带一提，改之前在我的电脑上肉鸽是基本不能用的，改之后基本能用了：）
> feat: 优化 minitouch 滑动操作

- resource/tasks.json
- src/MeoAssistant/Controller.cpp
- src/MeoAssistant/Controller.h
- src/MeoAssistant/Task/Plugin/RoguelikeBattleTaskPlugin.cpp
- src/MeoAssistant/Task/Sub/BattleProcessTask.cpp
- src/MeoAssistant/Task/Sub/ProcessTask.cpp
- src/MeoAssistant/Task/Sub/ProcessTask.h
- 增加 `slope_in` 和 `slope_out` 参数
- 当数值都为 1 时相当于线性插值
- 为 0 表示平缓 (开始/结束时速度为 0, [如果都为 0 就是先加速后减速](https://www.wolframalpha.com/input?i=plot+3x%5E2+-+2x%5E3%2C+0%3Cx%3C1))
- 如果为负数会先 overshoot 再移回来 (没试过)
- 修改 swipe 结束时的 wait (~~我乱改的, 不大清楚这个是干什么用的~~)
感觉对精确划动来说三次样条插值还不够平缓, 再好点恐怕得搞点贝塞尔插值或者把两个 $\exp(-x^2)$ 拼接起来
> feat: 在 minitouch 滑动操作中使用三次插值

- src/MeoAssistant/Controller.cpp
linux下socket超时时间默认两小时，还是设置成6s比较好
> fix: 修复POSIX下socket超时时间过长的问题

- resource/config.json
MAA 的 ncAddress 命令在 AVD 下获取错误结果。根据 Android 模拟器文档，宿主机的 IP 一般都是 10.0.2.2。使用这条命令获取的 IP 有时候会是 10.0.2.3。
```
stdout output:
10.0.2.3         0x1         0x2         52:55:0a:00:02:03     *        wlan0
10.0.2.2         0x1         0x2         52:55:0a:00:02:02     *        eth0
10.0.2.2         0x1         0x2         52:55:0a:00:02:02     *        wlan0
10.0.2.3         0x1         0x2         52:55:0a:00:02:03     *        eth0
```
目前的解决方案是加一个 sort，让 10.0.2.2 排在前面。
因为我现在没有 MAA 主仓库的 push 权限，我所有对 MeoAsstMac 的修改都只能通过 PR 的形式合并，有时候会忘记。我们要不写个什么 action，让主仓库可以自动 pull。
> fix: 修复macOS启动卡住的问题

- resource/config.json
- src/MaaWpfGui/Main/SettingsViewModel.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/Python/asst.py
- src/Python/sample.py
丢弃截图命令的stderr. 如Amd显卡+Waydroid时, screencap会先输出一行报错, 再输出图片信息, 通过丢弃stderr让adb exec-out能得到仅图片信息, 防止MAA解码失败.
py接口新增额外配置(触控, 暂停下干员等)方法.
> 修改截图命令 && 添加Python额外配置(触控, 暂停下干员等)接口

- src/MaaCore/Controller.cpp
`recv_by_socket`模式下直接使用break跳出while循环, 未等待子进程结束. 由于短时间多次调用该API(大概是失败重试机制), fork的大量子进程也由于饥饿无法调度到结束. 
导致出现数次以下LOG后系统全局进程资源不足
```log
[2023-02-06 20:20:42.595][ERR][Px11c40][Tx72b5ddf9be091e81] Call ` /Applications/MAA.app/Contents/MacOS/adb -s 127.0.0.1:5555 exec-out "screencap | nc -w 3 10.0.2.2 51412" ` create process failed, child: -1
[2023-02-06 20:20:42.595][ERR][Px11c40][Tx72b5ddf9be091e81] data is empty!
[2023-02-06 20:20:42.595][ERR][Px11c40][Tx72b5ddf9be091e81] Call ` /Applications/MAA.app/Contents/MacOS/adb -s 127.0.0.1:5555 exec-out "screencap | nc -w 3 10.0.2.2 51412" ` create process failed, child: -1
[2023-02-06 20:20:42.595][ERR][Px11c40][Tx72b5ddf9be091e81] data is empty!
[2023-02-06 20:20:42.595][ERR][Px11c40][Tx72b5ddf9be091e81] Call ` …
```
> fix: `call_command_posix` in socket mode should return after child process finished

- src/MaaCore/Task/BattleHelper.cpp
这个bug会导致技能在使用后会报以下告警
[2023-02-08 07:52:17.788][WRN][Px1d84][Txe590936566bd74ca] Skill 山 is not ready
并在三次后不再使用技能
[2023-02-08 07:52:17.788][WRN][Px1d84][Txe590936566bd74ca] Do not use skill anymore 山
> fix: `check_and_use_skill` logic bug

- src/MaaWpfGui/Helper/MaaHotKeys/MaaHotKeyActionHandler.cs
- src/MaaWpfGui/Helper/StageManager.cs
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Main/Bootstrapper.cs
- src/MaaWpfGui/Main/CopilotViewModel.cs
- src/MaaWpfGui/Main/DepotViewModel.cs
- src/MaaWpfGui/Main/RecruitViewModel.cs
- src/MaaWpfGui/Main/RootViewModel.cs
- src/MaaWpfGui/Main/SettingsViewModel.cs
- src/MaaWpfGui/Main/TaskQueueViewModel.cs
- src/MaaWpfGui/Main/VersionUpdateViewModel.cs
- 将AsstProxy和工具类注入更改为构造器注入
- 在业务代码中不再使用`_container.Get<T>`方法
- 从`Screen`类继承的Model，在第一次显示Model时进行注入，这样做是避免已经存在的循环依赖导致构造堆栈溢出
- `VersionUpdateViewModel`是特殊的，因为它有可能不显示，所以它仍然采用构造器注入的方式
- `StageManager`为非单例类，`_container.Get<StageManager>()`会返回一个新的实例
> refactor: 重构注入方式

- src/MaaCore/Config/TaskData.cpp
- src/MaaCore/Config/TaskData.h
link to #2857 
咕咕咕！初步写完啦！
```
$name         = 至少一位的任务名
$numbers      = 至少一位的数字
$subtask_type = sub
| next
| on_error_next
| exceeded_next
| reduce_other_times
$sharp_type   = $subtask_type
| self
| back
| none
$subtask      = $subtask_type ( $tasks )
$lambda_task  = { $subtask , ... }         // 推迟实现
| { $tasks }                 // 推迟实现；不写 subtask_type 默认为 sub
$parens       = # $sharp_type
| $name
| $name $lambda_task         // 推迟实现
| ( $tasks )
$top_tasks    = $top_tasks @ $parens
| $top_tasks # $sharp_type
| $parens
$mul_tasks    = $top_tasks * $numbers
| $top_tasks
$tasks        = $mul_tasks + $tasks
| $mul_tasks ^ $tasks         // 删除 $mul_tasks 中所有在 $tasks 中的任务
| $mul_tasks
```
双目运算符 `@` `#` `*` `+` `^` 有优先级：`@` = `#` > `*` > `+` = `^`。均为左结合。
注意：单目运算符 `#` 和 双目运算符 `#` 在分析时优先级不同。
> feat: 增加任务的表达式计算

- resource/tasks.json
- src/MaaCore/Controller.cpp
- src/MaaCore/Controller.h
- src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.h
***图中数据标错了，左边是 350，右边是 210***
以上图为例，假设最后识别到的是 海蒂 一列，那么格劳克斯一列在滑动后不能被挡住。
注意到再肉鸽里识别一个干员时用到的最左边的东西是干员等级，也就是说滑动之后格劳克斯一列的干员等级不能被挡住。
假设海蒂的左端点 x 坐标 = pos_x，那么如图所示，最长滑动距离约为 `pos_x + 210 - 350 = pos_x - 140`。
代码中使用 `pos_x - 200` 保证容错。
以这种方式滑动，基本能够保证每次都多 8 个干员。
link to #3811
> feat: 加速肉鸽招募时滑动

- src/MaaWpfGui/Helper/MaaUrls.cs
缺少的斜杠导致一图流站点导航栏出现不正确高亮的bug。
其实应该在一图流前端修的，如果不想合并的话也行。
> fix: Fix CustomInfrastGenerator URL

- src/MaaWpfGui/Main/RootViewModel.cs
- src/MaaWpfGui/Main/VersionUpdateViewModel.cs
- src/MaaWpfGui/Views/VersionUpdateView.xaml
重新使用了 [NeoMarkdigXaml](https://github.com/neolithos/NeoMarkdigXaml/tree/0fedd1a48de1585f10dfa967db7e57ddca10b5f3)，现在能插入 `[!]()` 形式的图片，并且会隐藏 `` 形式的注释
<details>
<summary>效果</summary>
ps: 好像字体有点丑，但我不知道怎么改（x
</details>
另外，我把 ”好的“ 按钮删了，感觉有点占空间（点右上角的 x 不就好了么），这样能显示更多的 changelog
> feat: 优化 changelog 弹窗

- .github/workflows/dev-build-mac.yml
- .github/workflows/release-maa-mac.yml
- .gitignore
- 方便官网放下载链接，新的文件名叫 MAA-vX.Y.Z-macos-universal.dmg
- 为接下来实现 OTA 做准备
相对于分开架构只多了40MB，其实还好（
> chore: macOS构建Universal App

- src/MaaWpfGui/Main/TaskQueueViewModel.cs
方案思路来源：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3966
经过测试后已经能正常退出`雷电模拟器`的对应进程。
同时由于`逍遥模拟器`、与`夜神模拟器`使用同种方案，因此理应也是测试通过的。
可以合并了
> feat:更好的退出模拟器方式

- src/MaaCore/Config/TaskData.cpp
- src/MaaCore/Config/TaskData.h
之前每个 `tasks.json` 文件读取的时候都会调用 `expend_task()` 来 _解释_ 已加载的所有任务，在很多文件的时候会浪费时间。  
例如，外服加载现在有 3(?) 个 `tasks.json`，假设第一次加载的文件有 900 个项，那总共至少要进行 2700 次 _解释_ ：）  
另外，如果有用户不进行肉鸽任务，他就不必加载肉鸽相关的任务链！
现在在 `parse()` 的时候不 _解释_ , 而是等到一个任务被第一次 `get()` 时才进行 _解释_ 。  
不知道会不会出问题（？
> perf: 加速 `tasks.json` 的读取

- .github/issue-checker.yml
remove了半天 #4165 的copilot label但是死活删不掉
乱翻配置看到了顺手改一下
(所以说 remove `copilot` 这个comment为什么触发不了bot 明明匹配上了表达式)
> chore: 更正注释

- src/MaaCore/Assistant.cpp
- src/MaaCore/Common/AsstTypes.h
- src/MaaCore/Controller/Controller.cpp
- src/MaaCore/Controller/ControllerAPI.h
- src/MaaCore/Controller/ControllerFactory.h
- src/MaaCore/Controller/PlayToolsController.cpp
- src/MaaCore/Controller/PlayToolsController.h
- src/MaaCore/MaaCore.vcxproj
- src/MaaCore/Task/Infrast/InfrastDormTask.cpp
添加新的触控方式，针对 macOS 平台原生运行的 iOS 版明日方舟客户端。
macOS 上有一个叫做 [PlayCover](https://playcover.io) 的 iOS 游戏启动器的项目。它的原理是通过注入库（[PlayTools](https://github.com/PlayCover/PlayTools)）让应用绕过系统的运行环境检查。
我们可以 [fork 一份 PlayTools](https://github.com/hguandl/PlayTools/tree/MaaTools)，添加一个功能类似 adb 的本地 server，来实现截图和触控。我们可以称其为 MaaTools。
当前的 MaaTools 基于 TCP 实现了以下协议：
- 握手：`MAA\x00` 作为最初的 4 个字节发送以尝试建立连接，如果成功会收到 `OKAY`，连接就此建立。
- 请求体：后续请求会先有2字节作为长度，然后发送请求内容。
- 截图请求：内容为 `SCRN`，返回 4 字节头作为长度，然后紧接着是 RGBA bitmap 内容。
- 分辨率请求：内容为 `SIZE`，返回各 2 字节长度的宽和高。
- 触控请求：内容为 `TUCH` + 1 字节触控类型 + 各 2 字节长度的 x 和 y，无返回。
- 关闭请求：内容为 `TERM`，关闭客户端，无返回。
请 @aa889788 帮忙看看我对新 Controller 类的实现是否完全。iOS 不支持 ESC 按键，不知道除了不能暂停部署之外，会不会对 MAA 的其他功能造成影响。最后再让玛丽 @MistEO 把把关（）
> feat: 初步实现MacController

- src/MaaWpfGui/Constants/UILogColor.cs
- src/MaaWpfGui/Helper/ThemeHelper.cs
- src/MaaWpfGui/Res/Themes/Dark.xaml
- src/MaaWpfGui/Res/Themes/Light.xaml
- src/MaaWpfGui/Styles/Controls/TextBlock.cs
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/Views/UI/CopilotView.xaml
- src/MaaWpfGui/Views/UI/SettingsView.xaml
- src/MaaWpfGui/Views/UI/TaskQueueView.xaml
close #4336 
close #4365
示例作业中，
```
"xxx_color": "dark"
```
实际上是不合法的，正确的方式是使用[Colors类的命名](https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.media.colors?view=netframework-4.8#properties) _(:з」∠)_ ，之前会默认使用Colors.Black，现在默认使用UiLogColor.Message。
同时会检查TextBlock使用的Foreground颜色是否和背景颜色太相近。
> feat: UiColor适配DarkMode & feat: 在主界面保存位置时进行检查

- resource/tasks.json
- src/MaaCore/Config/TaskData.cpp
JustReturn 检查: 任务的 next 系列属性中，JustReturn 类的任务只能作为列表最后一个出现（否则后面的任务运行不到）
忽略了 Loading 相关的检查（因为如果 JustReturn 的任务 A 如果本身有 JR 的 next，A@Loading 就会有非最后的 JR）
> fix: 打开 debug 模式下的任务 JustReturn 检查

- resource/roguelike/recruitment.json
- resource/tasks.json
- src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.h
- src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
- src/MaaCore/Vision/OcrWithFlagTemplImageAnalyzer.cpp
- src/MaaCore/Vision/OcrWithFlagTemplImageAnalyzer.h
- src/MaaCore/Vision/Roguelike/RoguelikeFormationImageAnalyzer.cpp
- src/MaaCore/Vision/Roguelike/RoguelikeFormationImageAnalyzer.h
1. 优化了肉鸽自动编队逻辑，目前会按照核心干员顺序依次编队；
2. 优化了部分招募逻辑；
3. 修复了部分情况下在不期而遇、地区委托卡死的问题（Issue #4362 #4354 #4339 #4324 ）
> feat: 优化肉鸽编队逻辑

- .github/workflows/release-nightly-ota.yml
- .github/workflows/release-ota.yml
- src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
- src/Python/asst/updater.py
- tools/OTAPacker/build.sh
- tools/OTAPacker/ziplist.sh
- tools/OTAPacker/zipota.sh
使用 zip 格式内部 crc 来比较文件, 去掉 `md5sum.txt` 改为 `filelist.txt`
~~危险的修改, 准备好 revert~~ (
> chore: 加快更新包构建速度

- docs/1.3-模拟器支持.md
#4616
如题，对于蓝叠模拟器Hyper-V版本，启用`自动检测连接` 功能，会导致连接失败
在文档中做了补充说明
> docs: 补全蓝叠模拟器Hyper-V版本的指示

- resource/config.json
Fix #4045
已在蓝叠中国版的 Android 7 32位、 Android 7 64位、 Android 9、 Android 11 版本，和 Mumu X 模拟器（Android 12 版本）上测试，均能正确输出 `com.hypergryph.arknights`。
下列是导出的 `dumpsys activity activities 2>/dev/null` 的结果，可用以测试：
[Android_7_32_bs_cn.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414988/Android_7_32_bs_cn.txt) | [Android_7_64_bs_cn.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414990/Android_7_64_bs_cn.txt) | [Android_9_bs_cn.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414991/Android_9_bs_cn.txt) | [Android_11_bs_cn.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11414992/Android_11_bs_cn.txt) | [Android_12_mumu_x.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/1 …
> fix: 修正 Android 12 上无法结束游戏进程的问题

- README.md
- docs/1.3-模拟器支持.md
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/Python/asst/emulator.py
bluestacks.conf 中的 `bst.installed_images` 一项其实已经指明了使用的核心，可以直接读取
以及根据 #4616 的讨论完善文档
> feat: 支持直接读取蓝叠模拟器Hyper-V版本非多开模式下使用的核心

- src/MaaCore/Config/ResourceLoader.cpp
m_save_path is empty & ::load() never called when cache folder does not exist.
> fix(avatarcachemanager): avatar saved at wrong path in set_avatar()

- src/MaaCore/Common/AsstBattleDef.h
1. guard拼错了（
2. 游戏里辅助的正统翻译是supporter，所以顺便加上了
> fix: 解决guard和supporter字段不识别的问题

- resource/global/YoStarEN/resource/tasks.json
The OCR fails for the `InfrastFilterMenuNotStationedButton` task at higher resolutions, so I lowered the threshold a bit.
Logs for `1600x900` client:
```
[TRC][Px6fc0][Txfaa4] match_templ | InfrastFilterMenuNotStationedButton.png score: 0.785273 rect: [ 396, 343, 119, 37 ] roi: [ 300, 300, 250, 150 ]
```
> fix: update InfrastFilterMenuNotStationedButton for EN

- resource/global/YoStarEN/resource/tasks.json
Wild Mane has whitespace in between in-game.
From asst.log:
[2023-05-30 12:04:25.156][TRC][Px20dc][Tx3444] asst::WordOcr [{ Wild Mane: [ 0, 0, 84, 22 ], score: 0.994166 }] by OCR Rec , cost 6 ms
[2023-05-30 12:04:25.157][TRC][Px20dc][Tx3444] Proced []
Skadi Alter has name with new line.
Also bot only recognizes Skadi the Corrup***e***ing.
From asst.log:
[2023-05-30 12:04:13.814][TRC][Px20dc][Tx3444] asst::WordOcr [{ Skadi the Corrupeing: [ 0, 0, 108, 22 ], score: 0.986404 }] by OCR Rec , cost 5 ms
[2023-05-30 12:04:13.814][TRC][Px20dc][Tx3444] Proced []
ALSO
Every alter operator has the first name missing probably because the scope for searching the name is too small
Nearl Alter for example:
Gavial Alter for example:
> YostarEN: Skadi Alter / Wild Mane fixed in oper recognition

- resource/global/YoStarEN/resource/tasks.json
[issue.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11617845/issue.log)
`match_templ | Mizuki@Roguelike@GetDropSelectRecruit.png score: 0.795256 rect: [ 885, 488, 168, 40 ] roi: [ 0, 420, 1280, 175 ]`
Threshold 0.8 is just a bit too high for score: 0.795256.
The images are from 1920×1080. For systems with higher resolutions the problem might not exist.
> Update YostarEN tasks.json Mizuki Roguelike: map drop Triple Recruit permit exception leads to abandon

- resource/global/YoStarEN/resource/tasks.json
260/260 operators detected, finally fixed.
@MistEO the
`        "specialParams": [`
`            160,`
`            4,`
`            6,`
`            0`
`        ]`
from #5004 with [2] = 6 was a godbless, basically all the work that I had been doing this week has been rendered useless XD. I just tried tonight changing it and everything fixed itself. It took me a week because I had to understand a bit better the tasks.json and the MaaCore.
The only that is left is Operator's names that have a new line in them, such as Skadi the Corrupting Heart and Greyy the Lightningbearer.
> Update tasks.json for OperBoxNameOCR YostarEN

- src/MaaWpfGui/Res/Localizations/en-us.xaml
`"Foreign service adaptation is unsalable, help us! It's okay to not program."` is not proper English, especially "unsalable": it makes little to no sense. I've used the Japanese version and translated it to English, adding a bit of my own. I think this is better.
> Changed translation en-us.xaml

- resource/global/YoStarEN/resource/tasks.json
Normal / Adverse difficulty selection implemented from resource/tasks.json in YostarEN
from findmissingJsonTranslate.py:
EnterChapterDifficultyHard ['进入作战']
EnterChapterDifficultyNormal ['进入作战']
> feat: Difficulty selection for YostarEN

- src/MaaWpfGui/Res/Localizations/en-us.xaml
In video recognition message there is a \n that is not needed.
> typo: useless \n in EN GUI

- src/MaaWpfGui/States/RunningState.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
没搞懂，在`_ = Task.Run(async () => { ... })`中使用`Thread.Sleep`会影响UI线程吗
`ManualUpdate`是在`_ = Task.Run(async () => { ... })`里调用的，`AskToRestart`是在`ManualUpdate`里调用的，为什么这样会卡死
瞅瞅对不对）
> fix: 尝试修复运行时下载完成更新包后卡死

- resource/tasks.json
相关issue: #5373
为点击技能启动按钮的任务添加了检查启动按钮已消失的后续任务，这样在技能启动失败，界面仍处于选中干员的状态下时，可以重新尝试点击按钮。这一逻辑与其他类似确认操作已完成的逻辑一致，例如 [OFToOF-Chapter](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/resource/tasks.json#L1684)
此PR部分修复 #5373 以及其关联 issue, 可以防止该bug的触发将游戏状态卡死在子弹时间状态下，并通过反复尝试点击来让技能释放最终成功。但无法解决错误点击导致干员选择取消，从而跳过copolit设定的手动技能释放的情况。该bug仍需对识别和点击坐标的进一步调试。
> fix: 点击技能启动按钮时，验证按钮已消失，防止卡死在子弹时间中

- src/Python/asst/__init__.py
- src/Python/asst/updater.py
原代码中重试次数超过2后失效
修改后，重试次数将在所有备用下载站间均匀分配
> fix: 修复Python更新器中重试次数的问题

- resource/global/YoStarEN/resource/tasks.json
- resource/tasks.json
VisitNextBlack has default threshold (0.8 score) --> Gets detected even when the image is VisitNext (0.98 score)
Bumped the threshold up to 0.85.
Without this, MAA would visit only one friend and leave next.
1/10 friends visited.
extract from log:
[2023-07-15 18:37:27.463][TRC][Px888][Txfd8] asst::PipelineAnalyzer::analyze VisitNextBlack
[2023-07-15 18:37:27.464][TRC][Px888][Txfd8] match_templ | VisitNextBlack.png _**score: 0.808517**_ rect: [ 1116, 608, 122, 52 ] roi: [ 1080, 570, 195, 130 ]
> fix: Visiting only 1 Friend Clue Exchange in YostarEN

- resource/roguelike/copilot.json
现在的打法是百嘉朝左，打不到开局的几个小怪，并且医疗和狙击放置位置是如上图所示的（5,3）朝下，相当于浪费掉了医疗干员，突袭就很容易死并且开局几个小怪会把石头打穿。所以我改成了百嘉朝右，医狙（6,4）朝左，个人认为（6,4）的覆盖范围应该是完全优于（5,3）的。
tips：实测15难度普通死囚之夜百嘉这个位置朝右就能单刷（~~不过要卡轴~~
> 优化萨米肉鸽死囚之夜战斗逻辑

- resource/roguelike/copilot.json
禁止部署干员到蓝门左下方的三个格子
（因为可能会出现以下情况）
> 修改萨米肉鸽关卡“饥渴祭坛”摆放

- src/MaaCore/Common/AsstConf.h
当前的 Xcode 版本神奇地添加了 `#define  __cpp_lib_ranges 201811L`，造成 #5510 会编译失败。<del>然而 CI 上的 Xcode 版本比较老，反而没这个，所以莫名其妙地通过了。</del>
因此还要检查一下值，由 [cppreference](https://en.cppreference.com/w/cpp/ranges) 得出 `201911L` 应该就够了。
> fix: 修复对ranges支持检测的判断条件

- resource/roguelike/copilot.json
1、将第一层除兽群外所有关卡的提丰首下
2、修改”死囚之夜“提丰位置为[ 7, 4 ]
3、修改”度假村冤魂”提丰位置为[ 1, 2 ]
4、修改“苔手”提丰位置为[ 2, 2 ]
> 修改第一层提丰放置顺序以及站位

- src/MaaWpfGui/Main/Bootstrapper.cs
有时候在更新重启之后 gui.log 就无法写入，在定时自重启时也有概率发生。尝试修复一下，看看有没有效果。
> fix: gui.log 在自重启后有几率无法正常写入

- src/MaaWpfGui/Main/AsstProxy.cs
解决可能有人选了刷源石锭策略但是高级设置内未勾选投资源石锭选项的问题
> feat: 选择刷源石锭策略时强制启用投资选项

- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
这里提前两分钟切换配置，如果未勾选强制定时启动，是否可以豁免重启？
并且增加校验，如果没有切换到目标配置，跳过启动。
> 未勾选"强制定时启动"时就不必重启了

- qodana.yaml
忽略的警告类型是额外的逗号，如下：
```csharp
"zh-tw" => new[] { "zh-cn", _culture, },
"en-us" => new[] { "zh-cn", _culture, },
_ => new[] { "zh-cn", "en-us", _culture, }, //<- 尾部的逗号
};
```
```csharp
{ "en-us", "YoStarEN" },
{ "ja-jp", "YoStarJP" },
{ "ko-kr", "YoStarKR" }, // <- 尾部的逗号
};
```
> fix#根据反馈调整Qodana 忽略特定的警告

- resource/config.json
用单引号可以防止`$`内的变量在外部shell中替换，我在macOS和Linux上测试过都没有问题，不够我没有windows设备，不确定在windows上是否有效。
Edit: 由于这个修改可能在Windows上引发错误，所以我将其加入到了CompatMac里面使其只对Mac生效，但是Linux下应该也会有相同的问题，请问我应该创建相同的一个新的配置还是加入某一个现存的配置里面？
Fixes #5914
> fix: `CloseDown` not works on macOS

- resource/global/txwy/ocr_config.json
Reverts MaaAssistantArknights/MaaAssistantArknights#5933
@Roland125 @Constrat
请使用 tasks.json 中 ocrReplace 来进行替换，而非 equivalence_classes，这个是全局配置，会导致以后出的所有 `嗚` 均被替换为 `鴻`，而 tasks.json 中可以区分仅为干员名进行替换
equivalence_classes 的设计初衷是针对日语中这类仅靠肉眼都无法有效区分、在任意场合替换都合适的字符。
> Revert "添加繁中服对于鸿雪的OCR等价规则 #5931"

- .github/workflows/release-ota.yml
在macOS上`ln`产生的符号链接会直接沿用输入的路径，而不会进行变换，因此在现在的情况下产生的符号链接是这样的：
```
libonnxruntime.1.14.1.dylib
libMaaDerpLearning.dylib
libMaaCore.dylib
libopencv_world4.407.dylib
libonnxruntime.dylib@ -> macos-runtime-temp/libonnxruntime.1.14.1.dylib
libopencv_world4.dylib@ -> macos-runtime-temp/libopencv_world4.407.dylib
```
为了生成正确的符号符号链接，我们需要输入的是目标相对链接文件的路径，由于目标和符号链接位于同一文件夹，所以应该是目标的文件名：
```bash
bash-3.2$ libonnxruntime_file=$(basename macos-runtime-temp/libonnxruntime*.dylib)
bash-3.2$ ln -vs $libonnxruntime_file macos-runtime-temp/libonnxruntime.dylib
macos-runtime-temp/libonnxruntime.dylib -> libonnxruntime.1.14.1.dylib
bash-3.2$ libopencv_world_file=$(basename macos-runtime-temp/libopencv_world*.dylib)
bash-3.2$ ln -vs $libopencv_world_file macos-runtime-temp/libopencv_world4.dylib …
```
> fix: link in mac-runtime release

- src/MaaCore/Config/Miscellaneous/RecruitConfig.cpp
- src/MaaCore/Config/Miscellaneous/RecruitConfig.h
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaWpfGui/ViewModels/UI/RecognizerViewModel.cs
Makes Maa use IDs for recruitment instead of names, so it can properly show potential data for overseas clients.
<details><summary>Screenshot (Before)</summary>
</details>
<details><summary>Screenshot (After)</summary>
</details>
> fix: all operators are marked as new for overseas clients (Toolbox-Recruitment)

- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
Nested if logic can potentially be optimized (?)
With [3fa182d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6050/commits/3fa182d735bb55b6e2eb8580076de76308c0e0f5) 
```
{
"activity": {
"name": "引航者试炼",
"time": 1692345600
},
"gacha": {
"pool": "云间清醒梦",
"time": 1690862400
}
}
```
`time` is used and compared to the current (UTC, NOT local) time of the machine to choose what event / gacha pool to display
> feat: Event Activity and Gacha Banner are displayed according to current time

- resource/roguelike/Mizuki/encounter.json
- resource/roguelike/Mizuki/encounter_for_deposit.json
- resource/roguelike/Phantom/encounter.json
- resource/roguelike/Phantom/encounter_for_deposit.json
- resource/roguelike/Sami/encounter.json
- resource/roguelike/Sami/encounter_for_deposit.json
水月和傀影的文件都是小小改动,只调数字,萨米的顺便修复了顺序使其与wiki顺序保持一致,而且使encounter_for_deposit与encounter同项对齐,方便对比
> roguelike: 适配刷源石锭模式不期而遇选择策略

- CMakeLists.txt
@mole828 指出 Python 脚本在 macos 下没法正常运行, 可能是这个问题
(我没有 macos 设备, 得测下对不对~~
> chore: fix rpath for macos

- resource/global/YoStarJP/resource/tasks.json
OCR识别结果好像不稳定
```
[2023-08-27 11:56:48.010][TRC][Px20e2c][Tx16724] asst::WordOcr [{ 購買照: [ 37, 28, 115, 53 ], score: 0.724399 }] by OCR Pipeline , cost 22 ms
```
```
[2023-08-27 11:47:23.769][TRC][Px2b2c8][Tx158a4] asst::WordOcr [{ 購買瑠拠: [ 38, 29, 114, 51 ], score: 0.650200 }] by OCR Pipeline , cost 19 ms
```
> fix: ocr replace for YostarJP

- .github/workflows/ci.yml
- README.md
- docs/1.6-CLI使用指南.md
增加了CLI的文档，并且在Linux的发行版里面打包了一个预编译的CLI。因为现在CLI可以完全独立于Core编译了，所以我就没有把那个库当成子模块加进来。
> feat: 添加CLI支持

- src/MaaCore/Task/Fight/SanityBeforeStagePlugin.cpp
> fix: 修复在部分情况下，刷理智的当前理智识别结果丢失分隔符

- docs/ja-jp/readme.md
The current default font specified is a Chinese-based font, which is very difficult to read, so a Japanese-based font was mandatorily specified.
現在デフォルトで指定されているフォントが中国語ベースのフォントで非常に読みづらくなっているので、日本語ベースフォントを強制指定した。
> [JP] readme Update test / Japanese font readability

- resource/tasks.json
- src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp
fix #5837 #6306 
已知出问题的老鲤皮、纯艾精二皮都是暗红色的背景，把明度阈值提高点就完事了
Refer to https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6308#issuecomment-1713173208
测测？
> fix: 修复因部分皮肤造成的关卡难度识别问题

- src/MaaCore/Status.h
- src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
- src/MaaCore/Task/Infrast/InfrastAbstractTask.h
- src/MaaCore/Task/Interface/InfrastTask.cpp
> fix: 将基建换班编组匹配的可用干员缓存移动至Status，以免多实例时发生冲突

- resource/tasks.json
当藏品超过5个时，点击Mizuki@Roguelike@CloseEvent会有概率点到藏品导致展开藏品界面并卡主
fix #5892 
fix #6148 
fix #6090 
fix #5530 
fix #6452 
fix #6366 
fix #5831 
fix #5709 
fix #5041 
fix #4759 
fix #4499 
fix #4175
> fix: 修复水月肉鸽卡在藏品

- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
The time diff in sanity report in the current version is in the format h:mm which can cause confusion. I made changes to specificly note the units. For example, in Chinese, it would show as x时xx分.
> perf: optimize time diff format in sanity report

- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
修了一下格式问题（日期丢失，导致难以判断第一个时间是具体时间）
设计格式：
当前格式：
顺带修改了一下时间间隔的格式
- close #6506
> fix: 修复理智预测时间格式

- resource/tasks.json
#6552 重命名任务，缩小了点击范围（只测了下萨米的，其他的不知道位置变化大不大），逻辑改成直到进入肉鸽开始战斗界面前一直点
> fix: 尝试修复#6552导致的死循环

- resource/tasks.json
- src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
- src/MaaCore/Task/Interface/StartUpTask.cpp
1. 删除已有 `CloseAnnos#next` 时冗余的 `TodaysSupplies`
2. `ReturnTo` -> `BlackReturn`, `Return-White` -> `WhiteReturn`, `ReturnToConfirm` -> `ReturnConfirm`
3. 把 黑返回键 `BlackReturn`、白返回键 `WhiteReturn`、`FromStageSN` 组合成 返回键组 `ReturnButtons`（类似 `CloseAnnos`）
4. 给 黑白返回键 的 _next_ 增加 _Loading_ 套餐（跳过领取奖励时匹配得分低也许是因为这个）
5. 由于 _Infrast_, _Roguelike_, _Reclamation_ 之前特化了 `ReturnTo`，现在重新特化黑白返回键；_Reclamation_ 之前特化了 `PopupConfirm` 作为 `ReturnConfirm` (好奇怪，但我应该没理解错吧)，现在重新特化 `ReturnConfirm`，修改了名称和相关内容
> perf: tasks.json 大修改

- resource/tasks.json
- src/MaaCore/Task/Roguelike/RoguelikeControlTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeControlTaskPlugin.h
这样就可以在配置文件中控制是否直接退出肉鸽任务链，不用 改插件 或者 set_enable(false) 了
> refactor: 修改肉鸽开始行动和商店投资达到上限时退出的实现方式

- src/MaaCore/MaaCore.vcxproj.filters
I understand that most of the MAA developers use Chinese as main language but I feel like this little change will not impact the developers, as the new nomenclature is basic programming knowledge (needed for VS22) but will definitely help all of the developers that don't understand Chinese.
This change will not impact the VSCode default environment where no programming knowledge is needed.
> style: VS22 Solution Explorer name change

- src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
- https://github.com/orgs/MaaAssistantArknights/discussions/6600
现在新版加完战斗列表之后太长了，完全遮挡了作业信息部分。
或许挪到作业信息之前会好一些？
> perf: WpfGui自动战斗解析作业后，提示文本移动至最顶端

- src/MaaWpfGui/Main/AsstProxy.cs
close #6660
+ TCP连接检测部分变量名错误，导致所有都判断为无法连接
+ 连接设置为空时会跳过对蓝叠模拟器Hyper-V版本的处理
> fix: 修复模拟器连接错误的问题

- src/MaaWpfGui/Views/UserControl/ConnectSettingsOnWakeUpUserControl.xaml
YostarEN does not allow multi-accounting (I'm pretty sure it's the same for JP and KR as they are all under Yostar) the "Manual Switch" button is not really needed.
With this PR I'm completely hiding the Grid.
> style: hidden "Manual switch" button

- qodana.yaml
EAP 满 30 天的有效时间，过期了，只能等 Jetbrains 解决那个问题了。目前先换回正式版的镜像，在 QODANA-TOKEN 有效的情况下，依然可以使用。
https://youtrack.jetbrains.com/issue/QD-6711
只能说不知道 Jetbrains 还要摆多久了，这个问题也两个多月了（sad
> ci: 移除 qodana 的插件来恢复工作流

- src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
- src/MaaWpfGui/Constants/ConfigurationKeys.cs
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- src/MaaWpfGui/Views/UI/TaskQueueView.xaml
- src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
- close #1961
~~顺带移除了肉鸽battle里面从status()读数据的部分~~
~~顺带移除了status()的肉鸽主题数据，以及在肉鸽battle的缓存了一下精英数据(?)~~
- ↑移动至 #6646
> feat: WpfGui新增 肉鸽设置-中止行为等待至本次战斗结束后

- resource/global/YoStarEN/resource/tasks.json
- resource/tasks.json
- src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
I still haven't fully tested on the CN, but it has the same specialParams as `OperBoxNameOCR` so it shouldn't create problems.
Closes #6680
> feat: OCR manipulation params for QuickFormation

- src/MaaCore/Controller/Platform/PosixIO.cpp
在满足 `recv_by_socket = true` 时的一些特殊情况下，POSIX 平台上执行 ADB 命令的子进程可能无法及时退出：
1. **子进程在 `nc` 后未退出。**[这篇博文](https://billauer.co.il/blog/2018/07/netcat-nc-stop-quit-disconnect/)提及 FreeBSD、GNU 和其他 Netcat 实现，在以下情况是否会退出**是未定义的**：
1. gets an EOF on its standard input;
2. receives a FIN packet.
如果模拟器的 `nc` 是一个不良的实现，可能会在不传递 `-q` 参数时完全不退出，在 MAA 对不同截屏命令进行测速时卡死；
2. **子进程有任何标准输出或错误输出。** 因为未将 `m_pipe_out[PIPE_WRITE]` 设置 `O_NONBLOCKING`，也未读取管道内容，子进程将在管道缓冲区满时挂起。
该 PR 对于第一种情况添加了超时 Killing，对第二种情况排空了管道。
Fix #6688.
> fix: 修复 POSIX 平台上在一些情况下子进程不结束而使 MAA 永久性挂起的问题 

- resource/global/YoStarEN/resource/tasks.json
The OCR currently fails for the `UnlockClues` task at higher resolutions, so I lowered the threshold a bit for EN (from default `0.90` to `0.85`).
Logs for `1600x900` client:
```
match_templ | UnlockClues.png score: 0.871378 rect: [ 554, 619, 256, 62 ] roi: [ 200, 600, 700, 120 ]
```
> fix: update UnlockClues for EN

- resource/infrast.json
如题
我寻思水月组能正常识别多萝西组怎么不行，翻了下issues全是建议使用自定义基建的
> feat: 添加了淬羽赫墨与多萝西的基建技能联动

- resource/tasks.json
> fix: 修复战斗列表中跳过剧情确认识别问题

- .github/workflows/ci.yml
尝试解决下载 403 的问题：https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/6522057109/job/17711276716。
但是这个可能不一定解决了这个问题，因为下载速率限制可能可以通过使用 `GITHUB_TOKEN` 来解决。这已经是 `release-downloader` 的[默认值](https://github.com/robinraju/release-downloader/blob/0ef9efab81fa2487942697c8f438cdd179f82529/action.yml#L39)了，我不确定再换一个 token 是否真的可以解决这个问题。如果之后还是出现这种情况，我就在 clone 过来再编译。
BTW, 我还改了 CI 的触发条件，因为即使是主仓库的分支，任何只对 CI 的修改也没办法触发 CI，如果这个不需要，我就 revert。
> ci: 使用 token 下载 CLI

- resource/global/YoStarJP/resource/tasks.json
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6947
此处难度选择可能不依赖图片模板，而是依赖文字OCR。已添加文字OCR所需任务，并初步测试能够正常选择“风平浪静”难度。
> fix: 日服水月Rogue选择难度功能

- .github/workflows/ci.yml
- .gitmodules
换了 token 之后出现 401 #6941 , 所以放弃下载，直接编译算了。Submodule 每次 CLI 发新版了之后我过来 bump 一下。
#6945 #6948 #6949 都是因为出现了 401 导致CI失败。
> ci: use submodule for `maa-cli` and build it from source

- resource/global/YoStarEN/resource/tasks.json
ref:
- #6992
For 5750 - 5770 the regex is basically impossible.
I?m trying my best but some items WILL be duplicates.
"Fortification Co-op\n" has lots of duplicates (they are in different I.S.)
@Lancarus, this is a lot of work, mut maybe dividing the collectibles between I.S.s could help?
> fix: YostarEN Mizuki I.S. regex

- src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
关卡名匹配规则为：
1. 如果由[a-z0-9\-]*组成，则直接使用
2. 匹配正则：[a-z]{0,3}-(([A-D]|EX)-)?\d+
匹配顺序：
1. 作业[doc][title]（仅单文件添加时启用）
2. 文件名
- close #6978
> fix: 修复Wpf自动战斗-战斗列表-批量导入时，缓存文件夹未存在导致报错的bug；调整关卡名匹配规则

- resource/config.json
使用 `busybox nc`
用户可能需要在模拟器中开启 adb 远程调试
> feat: 增加雷电模拟器 nc 截图方式

- src/MaaCore/Controller/Platform/Win32IO.cpp
[asst.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13072914/asst.zip)
```bash
[2023-10-23 17:01:35.431][INF][Px6798][Tx66c4] Call ` C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s emulator-5554 exec-out "screencap | nc -w 3 10.0.2.3 1853" ` ret 0 , cost 835 ms , stdout size: 0 , socket size: 8294412
[2023-10-23 17:01:35.456][TRC][Px6798][Tx66c4] asst::BattlefieldMatcher::pause_button_analyze count 0 threshold 200
[2023-10-23 17:01:35.493][TRC][Px6798][Tx16f0] asst::Assistant::stop | enter
[2023-10-23 17:01:35.493][INF][Px6798][Tx16f0] Stop | block
[2023-10-23 17:01:35.493][TRC][Px6798][Tx16f0] asst::Assistant::stop | leave, 0 ms
[2023-10-23 17:01:35.526][INF][Px6798][Tx66c4] Call ` C:\Program Files\BlueStacks_nxt_cn\.\HD-Adb.exe -s emulator-5554 exec-out …
```
> fix: 修复在点击停止后下一次开始任务时可能操作延时很高的问题

- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/Views/UserControl/GUISettingsUserControl.xaml
- src/MaaWpfGui/Views/UserControl/GuideUserControl.xaml
如题，先前的宽度设置会导致 `UI Theme` 显示不全
顺便做了个style（
> fix: 优化设置引导界面的视觉效果，并给 UI Theme 添加翻译

- src/MaaWpfGui/Views/UserControl/VersionUpdateSettingsUserControl.xaml.cs
内测版的UI Version显示为`DEBUG VERSION`，不知道是不是bug
> fix: 修复Wpf无法复制版本号至剪贴板

- src/MaaCore/Utils/Logger.hpp
这 Logger 好多奇奇怪怪的功能, 根本没地方用到 (
只在调试模式开启是因为这块万一有 bug 搞崩溃了, 光看用户发的日志可能很难发现是 Logger 自己炸了
要提前加锁是因为多线程的时候 scope_slice 的修改顺序如果和打印的行顺序不一致可能会导致对不上
如果按照原来的风格写得话可能得 `xxx << lv << s_push(&i) << ...;` `xxx << lv << s_pop(i) << ...;` 好麻烦 (反正都没人用
> feat: 开启 ASST_DEBUG 时在日志中用连线表示 LoggerAux

- resource/tasks.json
- src/MaaCore/Task/Fight/SanityBeforeStagePlugin.cpp
- src/MaaCore/Task/Fight/SanityBeforeStagePlugin.h
- 对识别区域进行预处理
- 识别失败后重试3次
- 重试识别延迟改为使用taskDelay
- 减少不必要的log
- 增加更多识别失败时的log
> perf: 理智识别模块优化：对识别区域预处理；增加失败后重试；优化log输出

- resource/config.json
reopen https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7173 here
> 悠星服的包名Arknights的A大写，导致grep找不到包名。因此完成后任务 退出明日方舟 无法完成。
> 修复偷懒直接把a删了，如果还有问题就把a改成大小写均可的正则表达式。
我再也不敢用主分支提pr了（
> fix: Exit Arknights of YoStar servers

- src/MaaCore/Task/Fight/StageDropsTaskPlugin.cpp
- src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp
- src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.h
基本就是先想办法边划动边截图先把所有材料都拼接到一整张长图片里面, 然后按原来的方法识别.
- 里面硬编码了一些 ROI 和划动参数是我瞎凑的, 应该可以继续优化
fix #7176
fix #7193
fix #7194
> feat: 支持识别长于一页的掉落列表

- resource/tasks.json
- src/MaaCore/Task/BattleHelper.cpp
- link to #7215 
旋转角度被去掉了，看了下似乎不同坐标的角度有差别
> fix: 修复部署时补偿距离过大，导致部署朝向滑动起始点超出范围

- src/MaaCore/Task/Interface/FightTask.cpp
> fix: 修复 刷理智-指定材料 选项取消无效的问题

- src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
> fix: 修复Wpf自动战斗-作业代码直接读取剪贴板会带入换行的错误

- src/MaaCore/Common/AsstTypes.h
- src/MaaCore/Config/TaskData.cpp
- src/MaaCore/Config/TaskData.h
- src/MaaCore/Config/TaskData/TaskDataSymbol.cpp
- src/MaaCore/Config/TaskData/TaskDataSymbol.h
- src/MaaCore/Config/TaskData/TaskDataSymbolStream.cpp
- src/MaaCore/Config/TaskData/TaskDataSymbolStream.h
- src/MaaCore/Config/TaskData/TaskDataTypes.h
- src/MaaCore/Config/TaskData/TaskDataTypes.hpp
- src/MaaCore/MaaCore.vcxproj
- src/MaaCore/MaaCore.vcxproj.filters
- 从 TaskData 中分离 TaskDataSymbol, TaskDataSymbolStream
- 优化与 TaskData 的 get_raw 和 get 相关部分
现在 get_raw 只能获取任务的继承信息，其它详细信息会在 get 的时候解析。
- 增加 TaskDerivedType 表示任务的继承类型
- 增加 TaskPipelineInfo 表示任务的流程信息（name + 5 个 TaskList 的任务列表）
- 增加 TaskDerivedInfo 表示任务的继承信息，包含 base & prefix & TaskDerivedType
- 给各个任务类型的 shared_ptr 增加了别名；
- 增加 ResultOrError（是 std::expected 的下位替代，同时又类似于 std::optional）
close #7129
> feat: 重构 TaskData

- src/MaaCore/Task/BattleHelper.cpp
- src/MaaCore/Task/BattleHelper.h
- src/MaaCore/Task/Miscellaneous/BattleProcessTask.cpp
- src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
- src/MaaCore/Task/SSS/SSSBattleProcessTask.cpp
修改前待部署区干员不会有无法识别的干员，修改后待部署区干员可能name为空
- close #7397
> refactor: 重构BattleHelper的m_cur_deployment_opers为vector

- include/AsstCaller.h
- resource/config.json
- src/MaaCore/Assistant.cpp
- src/MaaCore/Assistant.h
- src/MaaCore/AsstCaller.cpp
- src/MaaCore/Config/GeneralConfig.cpp
- src/MaaCore/Config/GeneralConfig.h
- src/MaaCore/Controller/AdbController.cpp
- src/MaaCore/Controller/AdbController.h
- src/MaaCore/Controller/Controller.cpp
- src/MaaCore/Controller/Controller.h
- src/MaaCore/Controller/ControllerAPI.h
- src/MaaCore/Controller/MaaThriftController.cpp
- src/MaaCore/Controller/MaaThriftController.h
- src/MaaCore/Controller/MinitouchController.cpp
- src/MaaCore/Controller/MinitouchController.h
- src/MaaCore/Controller/PlayToolsController.cpp
- src/MaaCore/Controller/PlayToolsController.h
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/Services/MaaService.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7132
添加完成后选项 返回桌面（windows返回桌面） 和 将明日方舟切入后台（模拟器返回桌面）。
返回桌面 没什么用，而且应该是一段windows only的代码，是否保留可能需要讨论一下。
模拟器返回桌面 是根据 issues 7132 的建议写的，使用```adb shell input keyevent HOME```使模拟器返回桌面，在模拟器内保留游戏进程方便下次唤起。经测试可以释放大约80%的CPU占用和一部分GPU占用，但似乎不会释放内存占用。以这种方式结束任务后，游戏会停留在任务结束时的界面，下次启动时需要勾选“开始唤醒”任务才能唤起游戏进程。
已知问题：
1. 不清楚模拟器会不会、什么时候会杀后台。
2. WSA能接收这个指令，也会把游戏切后台省CPU资源，表现为音乐停止，画面保留最后的图像不动。现阶段要用WSA需要把它全屏，此时需要把它手动退出全屏。或许可以把两个功能合并出第三个。
待改进：
1. 没有韩语翻译，这个我真不会。
2. 测试更多模拟器，可能有些模拟器不会响应这个keyevent。
> feat: 完成后选项 模拟器返回桌面

- resource/tasks.json
- src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
选择三技能前先进行一次滑动
- close #4977 
- fix #7349
> fix: 修复重岳等干员带三技能时点错的问题

- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- link to #7441
进一步拓展提示，但是单独copilot的时候还不会输出到对应的那边去
GrowlInfo试了下如果MAA不在前台就显示不了，Global信息又会报错（而且位置也不是期望值，给到屏幕右上角去了
> feat: 最快截图耗时超出阈值后，输出额外提示文本

- resource/tasks.json
This pull request fixes a typo in the task name from 
Changes tasks from "Comfirm" to "Confirm"
I've checked the Core, it doesn't seem like these tasks were used, so there shouldn't be any core changes needed.
> fix: typo in task name

- .github/workflows/ci.yml
- .github/workflows/docs-build-test.yml
- .github/workflows/gen-changelog.yml
- .github/workflows/issue-checker.yml
- .github/workflows/pr-auto-tag.yml
- .github/workflows/pr-checker.yml
- .github/workflows/qodana.yml
- .github/workflows/release-nightly-ota.yml
- .github/workflows/release-ota.yml
- .github/workflows/res-update-game.yml
- .github/workflows/smoke-testing.yml
- .github/workflows/sync-resource.yml
+ 给所有 ci 文件的每一个 step 都添加了名字，并且做了格式化
+ 现在 pr-checker 的触发机制应该是正常的了
先前不正常的原因是：PR被合并后会触发synchronize事件，此时获取的comimits是merge后分支内的commit，加一个检查就可以跳过这种情况了
+ 给 pr-checker 添加了 issue 评论，现在不合规的 commit 将会由 github-action bot 做出评论
大致效果：
> ci: 规范化ci文件格式及命名，优化pr-checker的触发逻辑及表现形式

- .github/workflows/smoke-testing.yml
- src/Cpp/main.cpp
修复类似 [0291163](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/02911638ce49730d3745fd910c250bc31a9cd44c) 的问题
（本地DEBUG就先扔着了
> ci: 修复smoke-testing重复加载外服和国服资源导致潜在的非预期TaskData字段问题

- src/MaaWpfGui/Views/UserControl/FightSettingsUserControl.xaml
- src/MaaWpfGui/Views/UserControl/FightSettingsUserControl.xaml.cs
有个问题是，右键之后，重启就变成未选中了（比如吃药）。而不是修改前的状态
> perf: 移除CheckBox右键额外调用

- docs/en-us/3.1-INTEGRATION.md
- docs/ja-jp/3.1-統合ドキュメント.md
- docs/ko-kr/3.1-연동.md
- docs/zh-tw/3.1-集成文件.md
- docs/协议文档/集成文档.md
- src/MaaCore/Config/Miscellaneous/RecruitConfig.h
- src/MaaCore/Task/Interface/RecruitTask.cpp
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.h
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- src/MaaWpfGui/Views/UserControl/AutoRecruitSettingsUserControl.xaml
* fix #7452   
按照 #7452 的想法，在 #6900  的基础上增加了只选尽可能多选且只选高星tag的功能选项，并将选项策略合并
默认策略：只选一个高星tag组合
#6900 策略：选满三个tag为止
新增策略：尽可能多选高星tag，且额外的tag组合要么完整选入，要么舍弃；且若当前出现更高星tag组合，则不会考虑较低星，只会尽可能选高星tag组合（例如出现五星tag时，将尽力多选五星tag，不会考虑四星tag）
(result_vec的排序规则暂时未更改)
在GUI中增加了选择公招策略的功能，如图：
<details>
</details>
最后用模拟器在自己账号上进行了一些自动公招测试。
> feat: 增加公招多选策略

- resource/tasks.json
- src/MaaCore/Task/Roguelike/RoguelikeStrategyChangeTaskPlugin.cpp
关于 StrategyChange：
这个任务是通过识别肉鸽选关界面正上方的层名来进行策略变更的，之前的处理逻辑会在 NextLevel（进入下一层，画面正下方会出现层名的界面，萨米肉鸽则是”完成本层后将获得“的密文板界面）任务点击后识别层名。
- 最早的处理逻辑，水月肉鸽会在 NextLevel 结束后卡死在 StrategyChange 的识别上，因为这个时候会卡在 DiceConfirm 的界面。
- 之前采用的 TryOnce 方法（仅识别一次，未识别到则忽略）虽然不会卡死，但可能会导致没有识别到层名就继续任务，可能导致包括烧热水在内的许多（策略相关的）任务逻辑出问题。
这个 PR 的逻辑：
- Phantom 和 Sami 的 NextLevel 后有 `next: [ StrategyChange ]`
- Mizuki 的 NextLevel 后有 `next: [ DiceConfirmAfterNextLevel, StrategyChange ]`,
DiceConfirmAfterNextLevel 后有 `next: [ StrategyChange ]`.
- `StrategyChange->next = [ Stages ]` （而不是 Stages#next）
有其它想法欢迎讨论。
> fix: 修复肉鸽烧水逻辑错误、肉鸽卡在第三层 boss 等策略相关问题

- src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
- src/MaaCore/Task/Miscellaneous/BattleFormationTask.h
- fix #7395
从点干员名改成点左上角的职业标（感觉是从一坨变成另一坨（
> fix: 修复 自动战斗-自动编队 当干员过于接近屏幕边缘时，编入操作可能被UI遮挡的问题

- resource/tasks.json
作为 JustReturn 任务还有自己作为 next 也太危险了（
看了一下，应该所有任务都会通过 CloseEvent 退出，剩下的就是直接进下一层了，接上 NextLevel
（如果有除了 CloseEvent 和 NextLevel 之外的玩意才能退出不期而遇的话，这个 PR 可能会导致引入新问题卡在不期而遇）
should fix #7884
> fix: 移除 StageEncounterClickToLeave 任务

- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
#7890 中提到"启动时提示，请求的操作需要提升，从而导致无法正常打开MAA。"，加了一个判断去捕获这个异常，使得MAA能正常启动，并且给出Warning。翻译是AI翻译的
> feat: 捕获启动模拟器时产生的权限不足异常

- docs/maa-infra.schema.json
`period` 应该是一个数组的数组：
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7d89e1d2e8e39a12715b2b08fc93cacbc6bfe7a1/docs/%E5%8D%8F%E8%AE%AE%E6%96%87%E6%A1%A3/%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md?plain=1#L27-L37
启动肥鸭和无人机加速应该是 `enable` 而不是 `enabled`:
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/7d89e1d2e8e39a12715b2b08fc93cacbc6bfe7a1/docs/%E5%8D%8F%E8%AE%AE%E6%96%87%E6%A1%A3/%E5%9F%BA%E5%BB%BA%E6%8E%92%E7%8F%AD%E5%8D%8F%E8%AE%AE.md?plain=1#L39-L47
> chore: 修复基建排班的 JSON schema

- src/MaaCore/Utils/Logger.hpp
保存后滚动可能会出现只有个bak，然后本体没了
而且gui那边保存时也不会滚动
> perf: Logger析构时不滚动日志

- .github/workflows/ci.yml
- docs/用户手册/CLI使用指南.md
我不确定现在其他语言的文档怎么改所以只更新了一下中文的文档。
顺便贴一份 CLI 的 Release Notes在这里。
<details>
<summary> Release Notes </summary>
- Search both origin and canonicalized directory of `current_exe` ([#94](https://github.com/MaaAssistantArknights/maa-cli/issues/94))
- Add a new subcommand `fight` ([#104](https://github.com/MaaAssistantArknights/maa-cli/issues/104))
- Add `BoolInput` to query user for boolean input ([#107](https://github.com/MaaAssistantArknights/maa-cli/issues/107))
- Qurey `start_game_enabled` and `client_type` in startup task ([#110](https://github.com/MaaAssistantArknights/maa-cli/issues/110))
- Add subcommand `copilot` to complete the auto-battle feature  ([#127](https://github.com/MaaAssistantArknights/maa-cli/issues/127))
- **BREAKING**: Resource update and refactor maa core binding …
> chore: bump `maa-cli` to `v0.4.0`

- src/MaaWpfGui/Helper/DataHelper.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
@Constrat All names in battle_data for characters that exist on official client but have not yet appeared on foreign client are in Chinese. Any good ideas?
> feat: 肉鸽开局干员支持输入任意客户端对应名称

- .github/workflows/ci.yml
- .github/workflows/docs-build-test.yml
- .github/workflows/release-nightly-ota.yml
- .github/workflows/release-ota.yml
- .github/workflows/smoke-testing.yml
旧版本使用的是 Node 16，已经过了生命周期了
新版本用的 Node 20
> ci: 更新使用的Node版本至最新的LTS版本

- resource/config.json
AMDGPU 现在需要使用 GeneralWithoutScreencapErr 来屏蔽 error 以保证 screencap 可用，但是现在 GeneralWithoutScreencapErr 实现是 2>/tmp/xxx.log, 而部分模拟器不会创建 /tmp 比如 redroid. 于是 screencap 会因为 permission denied 失败。
这个 PR 将 `GeneralWithoutScreencapErr` 行为改为 `2>/dev/null` 这样也与 config.json 中其他抛弃 error message 的行为一致。
> fix: screencap failure with amdgpu on some emulators (even with GeneralWithoutScreencapErr)

- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/Services/RemoteControl/RemoteControlService.cs
> feat: 远程控制对非 https 连接仅提出警告

- src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
- src/MaaCore/Task/Miscellaneous/BattleFormationTask.h
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
Now task would report an error and stop after two more failed retries instead of looping forever when a required operator is missing
This is a solution to #8042
> feat: stop and log when missing operators during formarion

- src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
- src/MaaCore/Task/Miscellaneous/BattleFormationTask.h
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
现在当识别到缺失的干员时会记录并继续编队，全部编队完成后一并报告并退出
并将自动编队重试次数调为0（不重试）
TODO：当仅缺失一个干员时自动借助战
fix #8390
> perf: 优化自动编队逻辑

- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
对于YoStar服务器，肉鸽开局干员选项中，隐藏未实装干员。
原理为判断当前MAA针对的服务器名称是否包含YoStar，然后判断battle_data.json中的干员名称的中文名称和英文名称是否相同。对于YoStar服务器，这一判断方法目前适用于除W外的所有5、6星干员（此外还有九色鹿中日文名称相同，但不影响）。
效果如下，隐藏了锏。
该方法不适用于繁中服，我没想好该怎么设置条件。
> perf: 肉鸽开局干员 隐藏未实装干员

- resource/tasks.json
- src/MaaCore/Task/Miscellaneous/DepotRecognitionTask.cpp
- src/MaaCore/Vision/Miscellaneous/DepotImageAnalyzer.cpp
- src/MaaCore/Vision/Miscellaneous/DepotImageAnalyzer.h
- src/MaaWpfGui/MaaWpfGui.csproj
识别时间缩短到10多秒。芯片材料中的近卫和术士芯片太过相近可能会导致识别不全和不匹配。
> perf: 优化仓库识别速度

- src/MaaCore/Task/BattleHelper.cpp
> fix: 修复肉鸽重复部署一个干员后不会开启技能

- src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp
- src/MaaCore/Vision/RegionOCRer.cpp
- src/MaaCore/Vision/RegionOCRer.h
> feat: 根据灰度二值化关卡名后再识别

- .clang-format
基于某单文件 40000+ 行屎山代码测试结果
```
基准 1:24
去掉 120-147 52秒
去掉 QualifierAlignment 和 QualifierOrder 55 秒
---------------------------
新基准 55秒
去掉 6-100 44秒
去掉 101-190 29秒
去掉 101-150 34秒
去掉 151-190 45秒
去掉 101-122 36秒
去掉 101-110 36秒
去掉 105-110 56秒
去掉 101-102 54秒
去掉 103 InsertBraces 37秒
--------------------------
新基准 37秒
去掉 6-100 27秒
去掉 101-190 28秒
去掉 6-58 36秒
去掉 60-80 37秒
去掉 90-99 36秒
去掉 80 37秒
去掉 89 36s
去掉 82 FixNamespaceComments 28s
-------------------------
新基准 28秒
去掉 101-150 29秒
去掉 151-175 22秒
去掉 151-162 21秒
去掉 151-156 22s
去掉 151-153 29s
去掉 155 29s
去掉 154 SeparateDefinitionBlocks 22s
--------------------------
新基准 22秒
去掉 6-100 19秒
去掉 101-190 21秒
```
```
InsertBraces: true
SeparateDefinitionBlocks: Always
FixNamespaceComments: true
```
这三个比较有用，先保留了
> chore: 去掉太慢的clang-format配置

- .github/workflows/release-nightly-ota.yml
`changelog_generator.py` 用 GitHub API 来获得对应的作者和 committer 登陆名。
https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/df90caba1b4f61565d87dae8742dbdb59b249924/tools/ChangelogGenerator/changelog_generator.py#L186-L202
Fixes #8725
> ci: generate changelog with python script for nightly

- docs/en-us/1.5-EMULATOR_SUPPORTS_FOR_LINUX.md
- docs/en-us/1.6-USER_GUIDE_FOR_CLI.md
- docs/en-us/2.1-LINUX_TUTORIAL.md
- docs/zh-tw/1.5-Linux模擬器支援.md
- docs/zh-tw/1.6-CLI使用說明.md
- docs/zh-tw/2.1-Linux編譯教學.md
- docs/开发文档/Linux编译教程.md
- docs/用户手册/CLI使用指南.md
- docs/用户手册/模拟器和设备支持/Linux模拟器与容器.md
- Upstream docs update: https://github.com/MaaAssistantArknights/maa-cli/pull/248
- 明确区分编译MAA动态库，安装MAA动态库与安装maa-cli并添加相关指引
- 使用 markdownlint 格式化文本
- docs/zh-tw/1.6-CLI使用說明.md: 使用OpenCC转换，与简体中文最新文档同步
_TODO_: 日语与韩语文档待同步
---
review point: 需繁体中文文化环境相关的本地人员审阅繁体中文部分用语及习惯用词
*请勿 squash merge，应直接merge或rebase
> docs: sync with upstream, re-arrange for linux users

- .github/workflows/ci.yml
- 更新 CLI 到 0.4.5，文档没有更新，因为我最近想重构一下 CLI 的文档，每次文档两边都要更新太麻烦了。
- 对所有架构都自行编译 openssl 而不是使用系统的 openssl，以防止部份发行版的 openssl 版本过低而无法使用。
> chore: update maa-cli to 0.4.5 and build with vendored-openssl

- resource/tasks.json
fix #8948
Require tests.
目前在日服版本中，选择“当前-上次”作战以进入 ZT-8 时，会直接识别到 FightSeries-Indicator.png ，得分 0.8 以上，如果此时选择了连战次数为1，就会点击到报酬区域，卡住流程。
所以将此项任务的 templThreshold 调整到 0.9，需要测试是否影响其他关卡。正常情况下应该可以达到 0.99 以上，不受影响。
> fix: 避免识别到不存在的连续作战图标

- docs/en-us/3.1-INTEGRATION.md
- docs/ja-jp/プロトコルドキュメント/統合ドキュメント.md
- docs/ko-kr/스키마/1.통합문서.md
- docs/zh-tw/3.1-集成文件.md
- docs/协议文档/集成文档.md
- src/MaaCore/Task/Interface/RecruitTask.cpp
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.h
- src/MaaWpfGui/Constants/ConfigurationKeys.cs
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- src/MaaWpfGui/Views/UserControl/AutoRecruitSettingsUserControl.xaml
增加了遇到 3 星 Tag 时的会选择的 Tag 倾向，并且如果有倾向的 Tag 会阻止试图刷新的行为，也会忽略“不选择 3 星 Tag”的设定（如果有）而选择并确认（如果需要确认）
在 GUI 中也添加了这一选项，如图：
已做过一些公招的测试，确保功能在默认情况下可以使用。外文文档使用 DeepL 机翻。
_作为个人给 MAA 投的第一个 PR，如果有不规范的地方也请指出（_
- Closes https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8818
> feat: 新增公招 3 星 Tag 的倾向策略

- resource/custom_infrast/243_layout_4_times_a_day_yituliu_1713115015768723.json
根据排班表协议，提示下一次换班时间的信息应该使用 `description_post` 字段，而目前一图流的编辑器貌似不支持，所以姑且先这样手动改一下吧。
虽然可能并不是大问题，~毕竟之前的一图流版配置也是这么写的，这么长时间也没见有人提~，但如果是写在 `description` 里就会在“自动保存为下个计划”时提前显示出来，用户如果真的按这个提示时间去换班那就错了。
> fix: 一图流 243 一天四换换班结束时的日志信息

- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
resolved #8953 
鉴于目前公招『元素』标签只有辅助小车有，所以就先硬编码进去吧，日后如果有变化再revert就好了
另外只改了中文界面的描述，不知道其他语言是否需要更改
> fix: Recruit 公招手动确认『元素』

- src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
Trying to fix #9138.
This is just a patch and not the permanent solution. 
InfrastAbstracttTask.cpp does not have any check after `ctrler()->click` meaning that it will always `return true` independently if the click is correct or not.
Other solutions are happily accepted (for example changing the enter_facilty algorithm, to allow usage of a flag (reception already has one for example))
> fix: adding delay between swipe and click

- src/MaaCore/Task/Fight/StageDropsTaskPlugin.cpp
fix #8942
现在掉落物识别时，滑动的位置靠近屏幕右边缘，导致呼出安卓的系统导航栏（HOME/返回/最近按钮)，使截图拼接时图片出现撕裂，最终导致 OCR 时 MAA 崩溃。
此 PR 只是一个简单的 workaround，将滑动起始位置向左移动 200，已测试一周，没有再出现崩溃的情况。
> fix: 掉落物识别时滑动起始位置过于偏右导致崩溃

- src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
Reverts MaaAssistantArknights/MaaAssistantArknights#9154 as it only added latency without resolving the issue.
> Revert "fix: adding delay between swipe and click"

- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- tools/AutoLocalization/example/en-us_force.xaml
- tools/AutoLocalization/example/zh-cn.xaml
- tools/AutoLocalization/example/zh-cn_new.xaml
对 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/8868 的补充
顺带给刷新 3 星 Tags 的 GUI 选项前面补充了没有倾向 Tag 的前提描述
- fixes https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9141
> fix: 公招 `m_first_tag` 匹配个数少于 3 个时的非预期情况

- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
> #7266: 使用加急许可选项仅会尝试对第一格进行加急招募，但如果第一格的招募内容需要手动确认，MAA就不再会加急剩下三格。
原因是所有格子都是空时，执行`recruit_now()`显然会失败，这导致maa误以为是『加急许可』用完了（注释也是这样写的`ran out of expedited plan`），因此关闭了使用『加急许可』的可能。实际上，如果还有可以招募的格子（`try_get_start_button(...).has_value()`），那么就应该还有机会使用加急许可，故不可将`try_use_expedited`设置为`false`。
resolves #3564
resolves #4982
resolves #7266
resolves #9228
> fix: 修复公招没有使用足量的加急许可

- src/MaaCore/MaaCore.vcxproj
可能修复新版本崩溃问题 (或者要求所有用户更新 vcruntime)
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9321#issuecomment-2163124698
> fix: add `/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`

- src/MaaWpfGui/Helper/ItemListHelper.cs
- src/MaaWpfGui/ViewModels/UI/RecognizerViewModel.cs
- src/MaaWpfGui/Views/UI/RecognizerView.xaml
cc @Constrat due to longer item names in English, we can only fit two per line compared to three in Chinese. Any thoughts on this?
> perf: 优化仓库识别结果展示，支持多语言显示

- src/MaaWpfGui/Views/UserControl/VersionUpdateSettingsUserControl.xaml
Scenario: automated MAA environment (multiple MAAs running at the same time).
The machine has an auto restart option to allow memory and register unload. MAA is restarted automatically meaning it will check update (good).
In the case of a one click update install by the user, these options need to be "trued".
But in the case of an auto restart, the first option is also true, meaning it will auto install and the user doesn't know / doesn't want to.
Disabling "Startup Update Check", currently also disables all the other options. Making it impossible for a user to one click install update when it doesn't want auto install after restart. 
This PR allows the user to change update settings even when the Startup Update Check is off. For example when a breaking change is fixed and a nightly is …
> chore: unlocks update options

- resource/global/txwy/resource/tasks.json
fix #9574, fix #9547, fix #9514, fix #9472 
如題，修正了繁中服薩米肉鴿獎勵無法多選一的問題
提個 PR 送合併先，不然感覺同問題的 issue 會一直出現 QQ
> fix: 修正繁中服薩米肉鴿獎勵無法多選一的問題

- README.md
Fix Weblate preview images and links in [README.md](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/README.md#%E5%A4%9A%E8%AF%AD%E8%A8%80-i18n) .
↓
> docs: fix Weblate status preview in README

- resource/global/YoStarEN/resource/tasks.json
- resource/global/YoStarJP/resource/tasks.json
- resource/global/YoStarKR/resource/tasks.json
- resource/global/txwy/resource/tasks.json
- resource/tasks.json
- src/MaaCore/Config/Roguelike/RoguelikeCollapsalParadigmConfig.h
- src/MaaCore/Task/Interface/RoguelikeTask.cpp
- src/MaaCore/Task/Interface/RoguelikeTask.h
- src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeCollapsalParadigmTaskPlugin.h
- src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp
- src/MaaCore/Task/Roguelike/RoguelikeConfig.h
- src/MaaCore/Task/Roguelike/RoguelikeFoldartalUseTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeFoldartalUseTaskPlugin.h
- src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.h
Gui的Bug是由于非标准格式Callback信息导致的，已舍弃。
傀影/水月肉鸽初始化Bug是由于调用了m_rare_clp_pds.at(theme)，而报错，已加了两层判定，双重保险。
给大家添麻烦了Orz
close #9559
> fix: 修复坍缩范式插件导致的Gui和傀影/水月肉鸽初始化Bug

- src/MaaCore/Task/Interface/RoguelikeTask.cpp
- src/MaaCore/Task/Interface/RoguelikeTask.h
- 修复肉鸽插件注册顺序，close #9631
破案了，我的坍缩范式插件pr和refactor/roguelike都修改了RoguelikeTask，merge后插件注册了两遍，第一遍注册早了，那会儿theme还没存进config里呢。
> fix: 修复萨米肉鸽因插件注册顺序导致的无法运行问题

- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
Translations update from [MAA Weblate](https://weblate.maa-org.net) for [MAA Assistant Arknights/Glossary](https://weblate.maa-org.net/projects/maa/glossary/).
It also includes following components:
* [MAA Assistant Arknights/WPF GUI](https://weblate.maa-org.net/projects/maa/wpf-gui/)
Current translation status:
> i18n: Translations update from MAA Weblate

- src/MaaCore/Config/Miscellaneous/AvatarCacheManager.cpp
- src/MaaCore/Config/Miscellaneous/AvatarCacheManager.h
- src/MaaCore/Task/BattleHelper.cpp
- close #9646 
- close #6024 
- close #6060
> fix: 自动战斗开始时移除召唤物类头像缓存，以避免跨局错误识别相似技能的召唤物

- resource/tasks.json
将 源石尘行动-复刻 的导航加入task.json，方便其他服务器后续使用。
删除了 OD-OpenOcr 的roi，使用默认区域。
所以为什么后来的 SS-OpenOcr 都需要各自指定roi了？是有什么UI改动吗？
> chore: OD navigation

- .github/workflows/res-update-game.yml
- tools/ResourceUpdater/main.cpp
@AnnAngela I'm wondering if just for the ResourceUpdater I can transfer everything on Ubuntu
1. To see if it's possible
2. To see if it's faster (duh)
Just as a personal challenge to be honest.
I've already tripled the speed by caching the executable. Adding parallelism seems to be faster by about 10-15 seconds as downloading the artifact compared to cloning the repo is 3 times as fast.
Ok I'm already having issues building it on a codespace as it's a subproject
> perf(ci): parallelism for resource updater action

- docs/zh-cn/protocol/task-schema.md
- src/MaaCore/Common/AsstTypes.h
- src/MaaCore/Config/TaskData.cpp
- src/MaaCore/Utils/JsonMisc.hpp
- src/MaaCore/Vision/Config/MatcherConfig.cpp
- src/MaaCore/Vision/Config/MatcherConfig.h
- src/MaaCore/Vision/Matcher.cpp
```json5
"method": "Ccoeff",                 // 可选项，模板匹配算法，可以是列表
// 不填写时默认为 Ccoeff
//      - Ccoeff:       对应 cv::TM_CCOEFF_NORMED
//      - CcoeffHSV:    转换为 HSV 颜色空间后再进行 CCOEFF
```
> feat: 支持自定义 MatchTemplate 匹配方法

- src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
有的玩意没有方向（比如鸟笼地雷），但是作业里面有方向，就表现为点开滑动末端干员的使用技能
link to #7141
fix #7790 
fix #8997
> fix: 肉鸽卡在干员技能面板

- docs/zh-cn/protocol/task-schema.md
- resource/tasks.json
- src/MaaCore/Common/AsstTypes.h
- src/MaaCore/Task/Interface/DebugTask.cpp
- src/MaaCore/Vision/Matcher.cpp
新增基于找色的图像匹配算法（
- RGBCount
先将待匹配区域和模板图片依据 maskRange 二值化，以 F1-score 为指标计算 RGB 颜色空间内的相似度
- HSVCount
类似 RGBCount，颜色空间换为 HSV
> feat!: 增加图像匹配算法 RGBCount, HSVCount

- .github/workflows/stale.yml
ref: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9853#issuecomment-2243230911
`exempt-issue-labels`  can be used to skip (for example) `MAA Team`  issues, or any issue that has a specific label, plus the custom made label `keep-open`, in case we want to use that.
> feat: close inactive issues

- src/MaaCore/Vision/MultiMatcher.cpp
~~### MultiTemplMatcher 和 MultiMatcher 的区别
MultiMatcher 只能应用于单模版多匹配结果的情况。
而 MultiTemplMatcher 可以应用于多模版多匹配结果。
我不知道 MultiMatcher 之前为什么那么设计。
如果可以确认 MultiMatcher 仅用于单模版，则可以直接用 MultiTemplMatcher 替换 MultiMatcher。
本功能将用于集成战略节点地图识别功能 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/9812 ，为未来肉鸽策略参数化打基础。~~
经（粗略）检查，目前所有使用 MultiMatcher 的情况都只有一个template，所以直接将改动应用至MultiMatcher。
> feat: MultiTemplMatcher

- resource/tasks.json
- src/MaaCore/Task/Roguelike/AbstractRoguelikeTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/AbstractRoguelikeTaskPlugin.h
- src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp
- src/MaaCore/Task/Roguelike/RoguelikeConfig.h
- src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.h
- src/MaaCore/Task/Roguelike/RoguelikeResetTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeShoppingTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.h
- src/MaaCore/Task/Roguelike/Sami/RoguelikeCollapsalParadigmTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/Sami/RoguelikeCollapsalParadigmTaskPlugin.h
- src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalGainTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalGainTaskPlugin.h
- src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalUseTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalUseTaskPlugin.h
~~Todo: （每做一步请示一遍102老师）~~
掀桌！删代码跑路！刷个隐藏坍缩范式不需要那么完善的功能。
（最后宣泄一点情绪，通宵好几天了情绪不太稳定）RoguelikeControlTaskPlugin 可能是插件间缺乏互动最早的受害者，怪不得我几乎没看到多少地方调用它。你可能会问可不可以ProcessTask(...).run(), 答案是不行，因为这样disable的不是主任务而是新的ProcessTask。我能想到的 workaround 是把 RoguelikeControlTaskPlugin-ExitThenStop 加到下一个任务的 sub 里。
> refactor: 肉鸽坍缩范式插件代码整理

- resource/roguelike/Sarkaz/autopilot/拆东补西.json
> fix: 修复萨卡兹肉鸽的自动战斗文件 拆东补西.json 的语法问题

- .github/workflows/optimize-templates.yml
I'm currently not sure if I shuold double check if there were real png changes. Currently this workflow should run only when changes are made to these paths:
```yaml
- "resource/global/txwy/resource/template/**"
- "resource/global/YostarEN/resource/template/**"
- "resource/global/YostarJP/resource/template/**"
- "resource/global/YostarKR/resource/template/**"
- "resource/template/**"
- "docs/.vuepress/public/image/**"
- "website/apps/web/public/**"
- "website/apps/web/src/assets/links/**"
```
Which are pretty much the locations of the pngs currently. Meaning that if a change happens there it's 95% a png change or addition.
There's the last 5% that makes me not sure. Meaning the optimizer could run when no optimization is actually needed. Nothing bad happens, but it's just wasted time. …
> feat: first implementation

- .github/workflows/markdown-checker.yml
为了防止误报，只检查相对链接和 github 相关的链接。
@SherkeyXD
> ci: only check github and github raw links

- resource/tasks.json
> fix: 萨卡兹肉鸽进入新一层识别太快导致先点击思绪后驼兽归队/混沌未来中逃脱

- src/MaaCore/Task/BattleHelper.cpp
疑似是因为无法自动将 std::chrono::milliseconds 转换为 std::string。
> fix: 修复debug模式在intel mac系统下无法通过编译的问题

- src/MaaWpfGui/Constants/ConfigurationKeys.cs
- src/MaaWpfGui/Helper/GpuOption.cs
- src/MaaWpfGui/MaaWpfGui.csproj
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/Views/UserControl/PerformanceUserControl.xaml
blacklist GPU if:
* no FL 12_0
* driver predates DirectML GA
* Intel: pre-Xe (Gen9, Gen11)
* AMD: pre-Polaris (Sea Islands, Volcanic Islands, Arctic Islands)
* NVIDIA: pre-Pascal (Kepler, Maxwell)
> feat: deprecate legacy GPUs

- .github/workflows/smoke-testing.yml
This DOES NOT NEED to be merged. I'm just asking an opinion because currently I have two ideas:
1. Use concurrency for smoke-testing, as only the most important pushes (latest) are really important, and before changes can be "discarded" as outdated.
2. Modify smoke-testing.yml to stop running when .png (templates) are pushed. This is not really a solution, as it could happen that a task is called the name of a .png, but they are "misstyped", meaning that not running smoke-testing at all could potentially lead to undiagnosed issues, so I'm more inclined to go with `1.`
Let me know what you think.
> ci(perf): add concurrency to block previous runs in case of new pushes

- resource/config.json
fix #9349 
尝试仅使用 packageName 查找包名，以规避雷电模拟器优先匹配 ActivityRecord 的情况。
> fix: 查询进程时仅使用 packageName

- src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.h
两套方案：
方案A，判断滑动后检测到的8个干员是否有变动，对拥有12+个同名预备干员的倒霉蛋不太友好。
方案B，坐标魔法，需要对MAA那并不一直很可靠的滑动精度充满信任。
甲方爸爸选择了 A 方案。
---
**以下内容已失效**
简单说一下460这个数字是怎么来着：
肉鸽滑动基本上是滑动一整个`column offset`，在没有触底的情况下，检测到的第一个结果必然会偏左（排序已经在 RoguelikeFormationImageAnalyzer 里做了），并且画面右边会露出一点点下一列的内容。
此时检测到的坐标应该在416左右。
当触底的时候，因为没有了下一列，画面回正后检测到的结果会偏右，横坐标会在509左右。
此次改动需要大家帮我测试一下，可能引发的问题有：画面没有及时回正导致检测不到触底，直接卡住在死循环。需要的话加一个100ms 的 sleep 。
> fix: 修改肉鸽编队滑页触底判断 (#9243, #9328)

- resource/tasks.json
有个叫"Roguelike@StageEncounterOptionUnknown"的任务一定在离开商店的前面成功识别，故将离开商店提前
> fix: 傀影肉鸽卡在商店界面

- docs/zh-cn/protocol/task-schema.md
- resource/tasks.json
- src/MaaCore/Common/AsstTypes.h
- src/MaaCore/Config/TaskData.cpp
- src/MaaCore/Task/BattleHelper.cpp
- src/MaaCore/Task/Interface/DebugTask.cpp
- src/MaaCore/Vision/Battle/BattlefieldMatcher.cpp
- src/MaaCore/Vision/Config/MatcherConfig.cpp
- src/MaaCore/Vision/Config/MatcherConfig.h
- src/MaaCore/Vision/Infrast/InfrastOperImageAnalyzer.cpp
- src/MaaCore/Vision/Matcher.cpp
- src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp
- 数色时使用的参数从 maskRange 中拆分并命名为 colorScales（-s 代表它是 list of color scale）
- 增加 colorWithClose 开关数色时闭运算，默认为 true
- maskRange 回退为仅支持 `array<int, 2>` （即 `pair<int, int>`）的输入，但代码中保留彩色和多个范围的支持
- colorScale 支持 `list<array<array<int, 3>, 2> | array<int, 2>>`，TaskData 实现中额外允许（不推荐的）
`array<int, 2>` 和 `list<array<array<int, 3>, 2> | array<int, 1>, 2> | array<int, 2>>`
fix #10235
> feat!: 拆分 maskRange，允许禁用数色时闭运算

- src/MaaWpfGui/Helper/ConfigurationHelper.cs
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
重新组织配置读取的函数。虽然还是没找到 #2535 的根因。
ConfigHelper 使用.bak前应该先检查一下.bak是否可以被有效解析，可能会出现两者同时解析失败的情况 
AsstConnect 勾选自动检测的逻辑处理感觉有些乱，也一并重写了一下。
> refactor(config) : reorganize settings loading

- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
- src/MaaWpfGui/ViewModels/UI/RecognizerViewModel.cs
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
Function required by https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10079#issuecomment-2298396723
允许通过手动修改 gui.json 中的 "GUI.OperNameLanguage" 字段强制干员名称显示指定语言。不正确的格式或不受支持的语言不会报错，只是会按默认处理，即跟随MAA。
```
"GUI.OperNameLanguage": "OperNameLanguageForce.en-us"
```
当前问题：小工具-干员识别，这里有单独的逻辑，并不直接使用软件设置，而是读取设置文件，自行解读其含义，相当于几乎不使用 SettingsViewModel.cs 中的方法。这是历史遗留问题吗，是否可以将其改为使用统一的方法？印象里两周前的测试中可以这样修改，但当时没有这样做。
先按原逻辑改改语法凑合用了（）
buff选项的修复针对的是 SSS_TowerMountains_SkalterEyjalterGoldenglowSilverash+Typhon.json，其中buff选项填了两个，不符合规则，按照规则只填写一个的话可以由MAA在开局时自动选取。
> feat: 允许手动指定WPFGUI中干员名称显示语言

- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
Simple change that implements GetLocalizedNames for infrast output.
(Didn't think it was this easy, so maybe issues arise from this?)
It's basically a cheap copy of what @Manicsteiner has done for CopilotView.
_Would like to require approval first since C# is not my main_
Output example:
Infrast:
Copilot:
^ how about rethinking the: `Current step: Deploy operator`. The `Current step:` seems very redundant
> feat: GetLocalizedNames for Infrast and Copilot output

- resource/tasks.json
> fix: 使用匹配后偏移代替每日任务

- docs/en-us/manual/cli/faq.md
- docs/ja-jp/manual/cli/faq.md
- docs/ko-kr/manual/cli/faq.md
- docs/zh-cn/manual/cli/faq.md
- docs/zh-tw/manual/cli/faq.md
Bump maa-cli to 0.4.12.
See [maa-cli changelog](https://github.com/MaaAssistantArknights/maa-cli/releases/tag/v0.4.12) for more details.
> chore: bump maa-cli to 0.4.12

- resource/global/YoStarJP/resource/tasks.json
- resource/tasks.json
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
三个文件改了四个问题
- task.json(JP) - Tales@RA@ConfirmToLoadSave
用词错误，必须修正
- task.json(JP) - Tales@RA@ResourceGained
roi区域较小，需要扩大，其他服务器可能也需要查看此问题
- task.json Tales@RA@PIS-ProsperityReachLimit-Dots
如果读档日期出现特定对话，如25天的固定敌袭，可以这样跳过对话
- SettingsViewModel.cs
当前版本代码下，必须为各个客户端输入对应语言的目标道具才能工作。此提交中的代码将导致无法置空该文本框，可能需要改进
> fix: Reclamation for YostarJP

- tools/OTAPacker/build.sh
在 [v5.5.1-alpha.1.d084.g5f5eccda7](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.5.1-alpha.1.d084.g5f5eccda7) 版本的 OTA 包中意外出现了先前版本的完整包
分析 [CI 日志](https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10199520807/job/28217514723) 发现如下几行
```
2024-08-01T14:00:51.2065910Z ##[group]v5.5.0-beta.1.d241.gbc3ad67a0
2024-08-01T14:00:51.2080265Z mkdir: created directory 'v5.5.0-beta.1.d241.gbc3ad67a0'
2024-08-01T14:00:51.2082057Z Downloading v5.5.0-beta.1.d241.gbc3ad67a0
2024-08-01T14:00:51.7285658Z release not found
2024-08-01T14:00:56.0414161Z stream error: stream ID 1; PROTOCOL_ERROR; received from peer
2024-08-01T14:00:56.0460379Z ##[warning] win x64 not found in release v5.5.0-beta.1.d241.gbc3ad67a0 skipping.
2024-08-01T14:00:56.0468909Z ##[endgroup] …
```
> fix: OTA打包时对跳过的版本做删除处理

- .github/workflows/res-update-game.yml
- tools/ResourceUpdateValidator/index.mjs
这个.mjs文件是一个用于自动化代码审查和版本控制的脚本。
脚本的核心功能是分析Git的差异输出，识别出哪些文件发生了变化，并根据变化类型（如是否为PNG文件或仅 version.json 的 last_updated 有变动的更新）来决定是否保留这些变更。对于不符合特定条件的变更，脚本会自动恢复到变更前的状态，确保代码库的一致性和规范性。
此外，脚本还使用了环境变量`GITHUB_OUTPUT`来记录分析结果，包括是否包含PNG文件的变更和是否有有效的文件变更。这些信息可以用于后续的自动化流程，如CI/CD管道中的决策步骤。
总体而言，这个脚本通过自动化和规范化的方式，提高了代码审查的效率和准确性，确保了代码库的健康和稳定。
> ci: 当仅 version.json 的 last_updated 有变动时，回退对应服务器所有资源文件改动

- tools/ResourceUpdateValidator/index.mjs
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/9d96081f47ea2a10be08f745f9d80baec16b95b4#commitcomment-146287940
This is just a patch fix, why is mainlandChina a Symbol anyway when the others don't seem to be one?
```
[2024/9/5 14:03:03] Parsed diff: {
YoStarEN: [ [ '1', '1', 'resource/global/YoStarEN/resource/version.json' ] ],
YoStarJP: [ [ '1', '1', 'resource/global/YoStarJP/resource/version.json' ] ],
YoStarKR: [ [ '1', '1', 'resource/global/YoStarKR/resource/version.json' ] ],
txwy: [ [ '1', '1', 'resource/global/txwy/resource/version.json' ] ],
[Symbol(mainlandChina)]: [ [ '1', '1', 'resource/version.json' ] ]
}
```
> fix: convert a Symbol value to a string

- .github/workflows/ci.yml
- .github/workflows/release-ota.yml
相比在 OTA workflow 里面靠解包 dmg 来生成 macOS 的 runtime 文件，在 CI 里面直接生成会更好一点。
> ci: create macOS runtime files in CI

- resource/tasks.json
根据文档，此处的参数表示额外滑动 https://maa.plus/docs/zh-cn/protocol/task-schema.html
实测会造成超长滑动范围，远超出一个页面，所以回调此修改
@Alan-Charred cc
虚拟设备：AVD 35.1.20 / Android 14.0 Google APIs x86_64 rev14
> fix: Reclamation scroll down

- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
Notification output:
`MAA has completed all tasks under the Mumu configuration on 2024-09-09 14:33:45 (in 0h 0m 3s)`
Log output:
I wanted to remove the leading zeros (in case there's any) to cleanup the output, but there's no "already made" method and since I'm lazy and don't want to clutter with more methods I think this is good enough :P
> feat: time diff log output and notification

- tools/build_macos_universal.zsh
修复对于 x86_64 CPU 的识别
[skip changelog]
> fix: macOS build script

- resource/tasks.json
商店页面部分 UI 位置下移后未及时适配，现修复。
原 roi 位置
修复后 roi 位置
> fix: 调整肉鸽 StageTraderRefreshWithDice 任务的 roi 参数

- src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.h
#9510
正常来说 cur_page 变量都是正确的，可以作为判断依据，既不用每次都划几下也不用识别左侧是否还有干员。
> fix: 肉鸽重新编队应在首页执行

- .github/issue-checker.yml
issue-checker uses typescript, or whatever, and does not support mode modifiers.
Luckily, we should be able to do this.
https://github.com/MaaAssistantArknights/issue-checker/blob/08d909e163099974c55f9dda40e45ac668bf91dc/src/main.ts#L942C5-L945C26
> chore: fix issue-checker macGui regex

- resource/global/YoStarEN/resource/tasks.json
- resource/global/YoStarJP/resource/tasks.json
- resource/global/YoStarKR/resource/tasks.json
- resource/global/txwy/resource/tasks.json
- resource/tasks.json
Fixes #10752 
在明日方舟国服最新的版本中，助战功能得到了更新，主要体现在，普通作战选择助战干员后也有了和集成战略开局借助战类似的确认框，且可以选择技能和模组。
这是普通作战
这是集成战略
目前观察到，助战干员会默认选择挂助战时选择的技能和模组。
未来 MAA 的借助战功能应当被重构，实现根据需要自动借助战，自动选择技能和模组，同时可以考虑拓展作业协议，让作业作者们选择刚需模组。
一些细节还有待讨论。
顺带：我不明白为什么要选择 OCR，模版匹配左边那个图标不好吗？
> fix: 为随机借助战功能添加点击确认按钮的步骤

- resource/global/YoStarEN/resource/tasks.json
This change modifies the OCR bounding box for the EN Babel Event
> fix: EN Babel OCR ROI

- maadeps-download.py
在 MaaFW 那边遇到了问题是部分 GPU 上 OCR 识别没有结果（甚至包括一些很主流的 N 卡），理论上对其他 onnx 模型也有影响（比如技能识别）
之前用的 DirectML 1.14.x，这个版本有问题（有什么问题呢，我不知道.jpg），微软已经撤包了
MAA 没有收到反馈我觉得可能是因为默认用的 CPU，而且界面上可选，大伙选了 GPU 发现不行又选回来了（？
但这个要更新一下 MaaDeps，流量消耗可能比较大，考虑要不要更新
> ci: update DirectML to 1.15.2 for Windows

- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
> fix: typo in[docs] 更新MuMu截图增强模式中端口的文本描述

- resource/global/YoStarEN/resource/tasks.json
- resource/global/YoStarJP/resource/tasks.json
- resource/global/YoStarKR/resource/tasks.json
- resource/global/txwy/resource/tasks.json
- resource/tasks.json
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.h
Fixes #10749
不太懂是不是应该这么改，等学姐看看。
我的理解是如果 MAA 因为什么延迟抽风的原因，点格子的时候点进了 <停止招募> 就退出来。
实际上开始招募按钮的 Task 后面已经有 500ms 的 postDelay 了，所以可能并不是这个问题。
roi 设置如下。
等学姐确认之后再考虑适配国际服。
> fix: 公开招募检测 Tag 失败时尝试识别 <继续招募> 按钮

- resource/global/YoStarKR/resource/tasks.json
``` python
[2024-10-20 11:57:32.113][TRC][Px311c][Tx87ac] asst::WordOcr [{ 지운유닛모집: [ 5, 10, 128, 25 ], score: 0.654263 }] by OCR Pipeline , cost 76 ms
[2024-10-20 11:57:32.114][INF][Px311c][Tx87ac] Assistant::append_callback | SubTaskError {"class":"asst::ProcessTask","details":{},"first":["Roguelike@RecruitSupportConfirm"],"pre_task":"","subtask":"ProcessTask","taskchain":"Roguelike","taskid":1,"uuid":""}
[2024-10-20 11:57:32.114][TRC][Px311c][Tx87ac] asst::ProcessTask::run | leave, 1694 ms
```
> fix: YostarKR add ocrReplace on RecruitSupportConfirm

- resource/tasks.json
- src/MaaCore/Task/Miscellaneous/CreditShoppingTask.cpp
Try fix #10888.
分析 Log 得知用户点击右下角 <加急许可> 时失败，未能识别到购买按钮，疑似因动画过渡导致点击未能失效。
现可重试 3 次（共尝试 4 次）。学姐之前写的 while 循环也没问题，只是条件里在`ProcessTask`前应该加一个`!`取反。
```
[2024-10-21 08:48:36.562][TRC][Px49d0][Tx1fa0] Click with scaled coordinates (916, 530) 1.5
[2024-10-21 08:48:36.562][TRC][Px49d0][Tx1fa0] minitouch click: (1374, 795)
[2024-10-21 08:48:36.663][TRC][Px49d0][Tx1fa0] asst::ProcessTask::run | enter
[2024-10-21 08:48:36.663][INF][Px49d0][Tx1fa0] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":1,"to_be_recognized":["CreditShop-BuyIt"]},"first":["CreditShop-BuyIt"],"pre_task":"","subtask":"ProcessTask","taskchain":"Mall","taskid":5}
[2024-10-21 08:48:36.693][INF][Px49d0][Tx1fa0] {"class":"asst::ProcessTask","details":{"cur_retry":1,"retry_times":1,"to_be_recognized":["CreditShop-BuyI …
```
> fix: 部分情况下信用购物因过度动画购买错误

- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Services/StageManager.cs
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
Linkstart 按钮现在替换成了更新关卡列表，可以通过改本地时间后点击来测试更新
使用`手动输入`时，只更新`关卡列表`，不更新`关卡选择`
使用`隐藏当日不开放`时，更新`关卡列表`，`关卡选择`为`未开放的关卡`时清空
使用`备选关卡`时，更新`关卡列表`，`关卡选择`为`未开放的关卡`时在`关卡列表`中添加对应`未开放关卡`，避免清空导致进入`当前/上次`
啥都不选时，更新`关卡列表`，`关卡选择`为`未开放的关卡`时在`关卡列表`中添加对应`未开放关卡`，避免清空导致进入`当前/上次`
除`手动输入`外所有情况下，如果`剩余理智`为`未开放的关卡`，会被清空
> perf: 调整关卡选择更新逻辑

- src/MaaCore/Task/Infrast/InfrastDormTask.cpp
Try fix #10682.
基建【不撤离进驻干员】功能是通过将宿舍的干员筛选条件设置为【未进驻】实现的。有专门的变量 `m_if_filter_notstationed_haspressed` 记录此筛选条件是否已经被设置。
由于基建插件的 on_run_fails 中的特殊设置，在【基建子任务】运行期间，无论因为什么原因退出基建系统，都能再次进入并继续该子任务。此时基建各设施的干员筛选条件将被重置，而 `m_if_filter_notstationed_haspressed` 变量却不会被重置。
学姐分析 Bug 极有可能因此产生。
此处修改逻辑，在每次进入宿舍后都会重新设置一遍筛选条件。
感谢学姐的指导。
> fix: 要求每次进入基建宿舍后都重新选择一遍筛选条件

- src/MaaWpfGui/Services/Notification/ServerChanNotificationProvider.cs
#10640
Server酱的title参数服务号通道不支持换行"\n"，在推送前删掉"\n"，并加入title的长度限制。
title: 消息标题，必填。最大长度为 32 。
> fix: Server酱通知推送无法正常推送到微信服务号

- resource/tasks.json
总得有人来当这个坏人，增加 postDelay 以防截图太快的用户。
Try fix #11051.
> fix: 为 PVChapterToPV 添加 1 秒的 postDelay

- src/MaaWpfGui/Helper/DataHelper.cs
- src/MaaWpfGui/Helper/ItemListHelper.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- src/MaaWpfGui/Views/UserControl/AutoRecruitSettingsUserControl.xaml
This PR replaces the existing `AutoRecruitHighPriority (公招三星优先tag)` textbox with a combination of `CheckComboBox` and `ListBox` for improved user interaction and better tag selection functionality.
- Replaced the `AutoRecruitHighPriority` textbox with a `CheckComboBox` to allow multi-tag selection.
- Implemented a `ListBox` to display the selected tags.
- Updated the data binding to ensure proper handling of selected tags.
- Refactored related event handling logic to integrate with the new components.
- Reword the tips and title for `AutoRecruitHighPriority`.
The previous implementation used a simple `TextBox` for selecting priority tags, which was not user-friendly, especially for selecting multiple tags. **Nobody wants to type those tags in string with no typo at all. 太不人性化了:(** 
This …
> perf: 公招三星优先tag 改为复选框

- src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp
Fix #10967 
闪退的触发原因是 process task 了一个不存在的任务
正在重构，不修 json 了，代码加点
> fix: 肉鸽不期而遇闪退

- src/MaaWpfGui/Services/Notification/SmtpNotificationProvider.cs
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.
部分邮件服务器不支持裸换行符 (https://learn.microsoft.com/en-us/exchange/troubleshoot/email-delivery/ndr/fix-error-code-550-5-6-11-in-exchange-online)
> fix: 移除了邮件通知中可能的非法字符

- maadeps-download.py
- tools/build_macos_universal.zsh
本地开发的时候偶尔要更新 maadeps，添加一个已下载的记录提高效率。
~这下每次 pull 后都无脑跑一遍 maadeps-download.py 也不成问题了~
> chore: 优化依赖下载脚本，避免重复下载

- src/MaaWpfGui/Services/Notification/SmtpNotificationProvider.cs
上一个修复中 （#11110） 的正则写错了，后来想了下 HTML 模板本来就不支持换行符，直接移除就行
> fix: 修改邮件通知中特殊字符的处理方式

- resource/tasks.json
> fix: 肉鸽构想不足过高阈值导致 mac 版无法识别

- src/MaaWpfGui/Views/UserControl/Settings/ConnectSettingsUserControl.xaml
这俩选项没对应到实际设置键值 也不会保存
我觉得应该只删 UI 就行了.jpg
> fix: 移除多余的阻止休眠设置选项

- src/MaaWpfGui/Main/AsstProxy.cs
Since the stage comes first for all languages it looks good.
> style: tweak unsupported level logging

- resource/tasks.json
> fix: 增加 Tales@RA@ResourceGained 任务的 roi

- resource/tasks.json
> fix: 进入去伪存真后识别太快导致错过 close collection 识别

- src/MaaCore/Config/TaskData.cpp
隐式声明导致以最小长度创建该vector，会存在一个时点是有越界风险的。
aarch64的严格检查会警告这一点。
尝试改为显式声明，就会直接创建合适长度的vector，从而回避这一点。
> Try to fix the compilation failure on aarch64

- resource/tasks.json
有用户反映生息演算确认离开当前区块后，会卡在战斗界面一小会儿，而 MAA 需要识别到“正在提交反馈至神经”这样的加载文字时才能一直等待，否则会在 20 次 retry 后停止任务。
这个 PR 通过在 `Tales@RA@PNS-ConfirmToLeaveNode` 任务的 `next` 中添加 `NextAfterMerelyWaiting` 项来允许无条件等待。
> fix: 生息演算无存档刷点模式，允许在确认离开当前区块后没有 Loading Text 的情况下等待

- docs/en-us/protocol/integration.md
- docs/ja-jp/protocol/integration.md
- docs/ko-kr/protocol/integration.md
- docs/zh-cn/protocol/integration.md
- docs/zh-tw/protocol/integration.md
- src/MaaCore/Task/Reclamation/ReclamationConfig.h
- src/MaaCore/Task/Reclamation/ReclamationCraftTaskPlugin.cpp
- src/MaaCore/Task/Reclamation/ReclamationCraftTaskPlugin.h
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
@Alan-Charred I started farming RA as I was very behind and this is my result in just about 1 hour:
Pretty good right?
But then I thought. What are the most efficient crafting recipes? And so I started crafting just the net hunter launcher thing. But I was leaving the run with 300 wood never to be used.
And so I thought about just copying the logic like a retard to use both rocks and wood (for very advanced players you could even use more crafting with metal)
Obviously my implementation is super bad and just an idea. But have we ever considered adding more crafting recipes / option to craft more stuff?
> feat: RA2 multiple crafting

- docs/en-us/manual/cli/install.md
- docs/ja-jp/manual/cli/install.md
- docs/ko-kr/manual/cli/install.md
- docs/zh-cn/manual/cli/install.md
- docs/zh-tw/manual/cli/install.md
Bump maa-cli to 0.5.2.
See [maa-cli changelog](https://github.com/MaaAssistantArknights/maa-cli/releases/tag/v0.5.2) for more details.
> chore: bump maa-cli to 0.5.2

- .github/workflows/smoke-testing.yml
Reduce path scoping for smoke-testing run requirements and implement global caching for all branches.
Save new cache only in dev.
> ci: smoke-testing cache + scope

- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.h
看错了，nothing to select这里原本就应该是用select_level的，但是上个版本改错用成confirm_level了，修正一下。
> fix:修正nothing to select情况下的判断逻辑

- resource/tasks.json
- src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp
- src/MaaCore/Task/Roguelike/RoguelikeConfig.h
- src/MaaCore/Task/Roguelike/RoguelikeLastRewardTaskPlugin.cpp
- src/MaaWpfGui/Constants/ConfigurationKeys.cs
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- src/MaaWpfGui/ViewModels/UserControl/TaskQueue/RoguelikeSettingsUserControlModel.cs
- src/MaaWpfGui/Views/UserControl/TaskQueue/RoguelikeSettingsUserControl.xaml
#11091 #11213
纯瞎搞。
目前的逻辑是，如果不选 `start_with_two_ideas`，那么刷的是 2 希望、热水壶、2 构想，3 选 1；反之则仅刷 2 构想。
要将每种奖励独立开来处理的话，得改写整个插件，目前精力不在这一块儿，先放放。
> feat: 萨卡兹肉鸽刷开局 2 构想

- .github/workflows/ci.yml
ccache completely pollutes the action cache.
- It's not easily manageable (keys, restore-keys etc)
- Every commit creates a new cache and older ones don't seem to get removed
- From 640MB we now have 800MB cache sizes
- And most importantly the build time reduction is minimal. We are talking at best 1 minute off the build time (When we are gate locked by the Windows build time anyway)
Without:
With:
But at least we don't go over by 15GB in the cache total (removing important cargo oxipng caches)
> ci: disable ccache

- resource/roguelike/Sarkaz/autopilot/卫士不语功.json
卫士不语功关卡的[9, 3]、[3, 4]、[2, 4]均为“启动！”装置，不可部署。
故修改为对应边上的高台。
> feat: 萨卡兹肉鸽卫士不语功战斗策略调整

- resource/infrast.json
- src/MaaCore/Task/Infrast/InfrastProcessingTask.cpp
语义问题，因为没有自定义配置时跳过加工站是正常的业务逻辑，不应该被当作错误来处理。避免了约 30 秒的无意义等待
返回 false时：
- 触发 `on_run_fails()`
- 执行 `InfrastBegin` 任务
- 导致重复执行 `InfrastBegin` -> `InfrastEnteredFlag` -> `Stop` 循环
- 每次循环大约需要 6-7 秒
因为加工站在 MAA 右边没有 log，容易被当作宿舍问题，如 #11415
- close #11499, close #7081
> fix: 修复基建排班错误和加工站卡住

- src/MaaWpfGui/Constants/UILogColor.cs
- src/MaaWpfGui/Main/AsstProxy.cs
- src/MaaWpfGui/Res/Themes/Dark.xaml
- src/MaaWpfGui/Res/Themes/Light.xaml
| ![image](https://github.com/user-attachments/assets/035b64d7-99e6-4ef1-9ae9-7a149e682c4c) | ![image](https://github.com/user-attachments/assets/7ffd223d-b45c-4a83-8b14-917667d60a0a) |
| -------- | ------- |
Missing log text stays as already defined previously (e.g. Trader investing, stage names, ...)
> feat(style): Colored logs for I.S.

- .github/workflows/website-workflow.yml
Build times are identical. Just wasted 100MB of cache for every "different" instance.
> ci: disable cache for pnpm

- src/MaaCore/Controller/MumuExtras.cpp
This is an attempt to resolve the issue for MumuExtras "MuMu截图增强模式" that the screen capture functionality fails indefinitely, but some manual operation on the GUI like stop and restart "一件长草“ still works without restarting either the MAA or the emulator.
Some logs of importance with issue:
gui.log
```
[2025-01-13 22:18:23.645][INF] <1><> 开始任务: Reclamation
[2025-01-13 22:45:05.370][INF] <1><> 截图失败，如反复出现请尝试重启或更换模拟器！
[2025-01-13 22:45:06.388][INF] <1><> 截图失败，如反复出现请尝试重启或更换模拟器！
[2025-01-13 22:45:07.405][INF] <1><> 截图失败，如反复出现请尝试重启或更换模拟器！
[2025-01-13 22:45:08.420][INF] <1><> 截图失败，如反复出现请尝试重启或更换模拟器！
[2025-01-13 22:45:09.435][INF] <1><> 截图失败，如反复出现请尝试重启或更换模拟器！
[2025-01-13 22:45:10.450][INF] <1><> 截图失败，如反复出现请尝试重启或更换模拟器！
[2025-01-13 22:45:11.466][INF] <1><> 截图失败，如反复出现请尝试重启或更换模拟器！
[2025-01-13 …
```
> fix: Attempt retry once screencap for MumuExtras

- src/MaaWpfGui/Views/UI/AnnouncementView.xaml
fix #11673 
有点没搞明白  
加上允许惯性滚动的属性就和其他页面一样了 把其他页面的惯性滚动去掉也会变得像公告一样超快  
感觉像handycontrol的实现有点问题 还是其他什么
但是这个惯性的速度曲线好奇怪啊
> fix: 公告窗口触控板滚动异常

- docs/en-us/manual/faq.md
- docs/ja-jp/manual/faq.md
- docs/ko-kr/manual/faq.md
- docs/zh-cn/manual/faq.md
- docs/zh-tw/manual/faq.md
替换.NET8 桌面运行时下载链接为直链
https://aka.ms/dotnet/8.0/windowsdesktop-runtime-win-x64.exe
方法来源https://github.com/dotnet/installer/issues/11040#issuecomment-874654711
因为纯网页端PR没整明白，所以clone下来改了其他语言，然后重新提了一个PR。之前的PR：https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11690
> docs: 替换.NET8 桌面运行时下载链接为直链

- resource/tasks.json
该弹窗在雷电模拟器的设置中无法关闭,但可以借助adb模拟点击关闭
配置文件已经经过测试，可以稳定使用
``` 
"StartUpThemes": {
"algorithm": "JustReturn",
"next": [
"LeidianGoogleFrameworkConfirm",
"GameStart",
"StartToWakeUp",
"StartToWakeUpOCR",
"StartLoginBServer",
"StartUpConnectingFlag",
"MainThemes#next",
"CloseAnnos#next",
"OfflineConfirm",
"GameStartUpdateOCR"
]
},
"LeidianGoogleFrameworkConfirm": {
"algorithm": "OcrDetect",
"action": "ClickSelf",
"text": [ "不安装" ],
"roi": [ 480, 410, 200, 50 ],
"maxTimes": 5,
"Doc": "用以关闭雷电模拟器启动外服明日方舟时弹出的未安装谷歌套件的提示",
"next": [ "StartUpThemes#next" ]
},
```
将`LeidianGoogleFrameworkConfirm`摆在`GameStart`之前是因为这个窗口在打开游戏的时候就会出现，不将其关闭将会导致GameStart卡住，从而导致StartUp失败
如果需要补充我可以提供
> perf: 开始任务自动关闭雷电模拟器 Google 套件窗口

- resource/tasks.json
目前已知的两个情况（都是傀影.jpg）都只提供了一个分队，随便选反正只能选一个
Fix #11839
> fix: 肉鸽未提供指挥分队时用OCR随便选一个

- src/MaaCore/Utils/Logger.hpp
> chore: 上调MaaCore Log Rotate阈值为64MB

- resource/tasks.json
修discord回报的无法选择干员，没能复现反而发现了这个
没能复现的问题大概nightly修好了，大概
> fix: Roguelike InitialDrop: SquadDefault -> Squad-EnterPoint

- .github/workflows/res-update-game.yml
- tools/ResourceUpdater/main.cpp
- tools/ResourceUpdater/version.ps1
@MistEO Ok, so shifting all logic to independent version.json modifications.
version.json will get modified when any file is modified except the tasks.json (follows [MaaResource files](https://github.com/MaaAssistantArknights/MaaResource))
~~Now I just need to revert and fix the logic to when we were previously checking for files differences and pngs, to correctly run the optimizations png step and then the commit and push.~~ DONE
Since I didnt completely understand the logic of when update-resources is run I will keep the bool that skips it, so for now the bool is directly connected to when version.json gets modified. If it gets modified, it will also run update-resources.
@AnnAngela After merge, do you think we delete validator.ps1 and mjs? Or do we keep them just in case?
> feat: script to update version.json

- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
- src/MaaCore/Task/Miscellaneous/AutoRecruitTask.h
- src/MaaCore/Vision/Miscellaneous/RecruitImageAnalyzer.h
按照执行结果来看
有问题的这个分支原本应该是为了在
有3星偏好TAG且招募最小等级是3星
的情况下，能够正常招募指定的3星tag。
但是逆否命题是
没有3星偏好tag或招募最小等级不是3星
就会导致错误地捕获5星的招募。
而且没有验证是否确认招募3星，顺便修了。
update 250214: 
有小猪（我
误操作卷回了修改 ，要重新开一个PR。
原PR#11855
> fix: 修复招募功能中的逻辑漏洞，并添加相应的测试函数

- src/MaaCore/Assistant.cpp
- src/MaaCore/Task/Roguelike/RoguelikeResetTaskPlugin.cpp
- 结合#11834 实施，分离PR仅用于后日revert
@ABA2396
> fix: Log Rotate 临时性检查措施

- .pre-commit-config.yaml
Why were we even using an alpha version of prettier? Especially when the mirror repo has been archived. (Especially when https://github.com/prettier/prettier/releases/tag/4.0.0-alpha.10 exists)
> ci: try to fix pre commit using an updated fork

- resource/global/YoStarKR/resource/tasks.json
```
StageDrops-TimesCheck: 连续, 成功, 代理, 作战
StageDrops-StageCF-FoodBonusFlag: 用, 餐, 加, 成
StageDrops-Stage12-TripleFlag: 后勤, 急派
GachaLastTenTimesResult2: 获得物资
Roguelike@NoneSelected: 不编入
```
Some items remain, but I don't know what they are :|
> fix: YostarKR missing tasks

- src/MaaCore/Task/Roguelike/RoguelikeIterateMonthlySquadPlugin.cpp
fix the fixable part of #11988
somehow CN can take it while EN can't, no idea why
> fix: add an missing @ for MonthlySquadCommsBackTwice

- src/MaaWpfGui/Res/Localizations/en-us.xaml
Yostar EN used investigation for both phantom and sami IS, but for Mizuki exploration; Originium, Originum Shards and Originite Prime were a bit mixed up
> chore: clarify different originium types and unify deep investigation in EN

- resource/tasks.json
Someone on discord had their MAA hung on team selection screen while MAA was in ```StageEnterBattleAgain```. We may also add ```Roguelike@ReturnToMap``` to ```StageEnterBattleAgain#next``` if need be, but I feel a simple preDelay is enough.
Discord那边有个报告MAA在选人界面（点进加号以后选择干员那个界面）挂起的，提供的log节选表明MAA卡在```StageEnterBattleAgain```里转了3w多圈，难以复现，先当成是没有足够的delay卡住了
> fix: stuck on StageEnterBattleAgain while in team selection screen

- src/MaaWpfGui/Main/AsstProxy.cs
This makes it crash apparentlty lol...
```py
[2025-03-01 13:33:50.490][ERR][Px3f84][Tx45dc] │││││││││ asst::TemplResource::get_templ templ not found act24side_melding_6
```
EDIT: Fixed
Before vs after
> fix: remove duplicate strings

- src/MaaCore/Task/Roguelike/RoguelikeResetTaskPlugin.cpp
- src/MaaCore/Utils/Logger.hpp
- close #11893 
分离日志翻转和业务逻辑，对日志流中字符计数，避免关闭时产生空日志文件
> fix: log rotate

- resource/tasks.json
ChangeToMoneyOrder任务在9ms的截图速度下，点击动作在游戏中无法生效，故添加一个任务前延时。 
顺便为ChangeToSyntheicJadeFlagOrder任务也添加一个前延时。
Co-authored-by: @Alan-Charred
> fix: 修复截图速度过快导致不能切换贸易站订单的问题

- resource/global/txwy/resource/tasks.json
fix: #12181 
神秘的 OCR 把 "空白" 認成 "空百" 了
> fix: 繁中服_生息演算組裝道具後卡住

- resource/global/YoStarKR/resource/tasks.json
log
``` python
[2025-03-16 15:57:49.944][TRC][Px6824][Tx470c] match_templ | StartToVisit.png score: 0.732708 rect: [ 1057, 148, 59, 34 ] roi: [ 952, 105, 267, 601 ]
```
> fix: YostarKR lower StartToVisit templThreshold

- resource/tasks.json
- src/MaaCore/Task/Roguelike/RoguelikeLevelTaskPlugin.cpp
将容易误识别的``-``换成数字，识别到数字就是没满
fix #12211
我没有jp客户端，希望原issue发布者测试一下稳定性，在CN上没有问题
> fix: CheckLevelMax ocr target "-" -> digits

- src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.cpp
- src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.h
提问：当 OcrDetect 任务的 text 为空数组时，这个任务能被成功执行吗？
答案：只要检测任何文字就会被成功执行。
所以当 difficulty 为 999 时，maa 设置 Roguelike@ChooseDifficulty_Specified 任务的 text 为空，会出现大大大大大问题。
> fix: mac下选择难度 999 导致卡死

- docs/en-us/manual/cli/config.md
- docs/en-us/manual/cli/install.md
- docs/ja-jp/manual/cli/config.md
- docs/ja-jp/manual/cli/install.md
- docs/ko-kr/manual/cli/config.md
- docs/ko-kr/manual/cli/install.md
- docs/zh-cn/manual/cli/config.md
- docs/zh-cn/manual/cli/install.md
- docs/zh-tw/manual/cli/config.md
- docs/zh-tw/manual/cli/install.md
Bump maa-cli to 0.5.4.
See [maa-cli changelog](https://github.com/MaaAssistantArknights/maa-cli/releases/tag/v0.5.4) for more details.
> chore: bump maa-cli to 0.5.4

- docs/staticwebapp.config.json
- website/apps/web/src/components/foundations/GlowButton/GlowButton.tsx
- website/apps/web/src/components/home/HomeActions/HomeActions.tsx
- website/apps/web/src/components/home/HomeActionsRelease/HomeActionsRelease.tsx
- website/apps/web/src/components/home/HomeHero.tsx
- website/apps/web/src/components/home/HomeLinks/HomeLinks.tsx
- website/apps/web/src/components/home/Screenshots/Screenshots.tsx
副驾驶新搞的代理模式好强 新时代摆完挂机超大杯
`GPT-4.1` `o4-mini` `Gemini 2.5 Pro` 用了一圈 还是 `Claude 3.7 Sonnet` 成功做出来了
随便糊的提示词：
```
请修改官网website中友情链接的位置。首先移除当前的友情链接触发方式和列表，之后在按钮的第二排”状态监测“右边新建一个友情链接按钮，并在点击后在屏幕右下角展示友情链接列表，按钮的样式需和其他按钮相同，列表的样式需和修改前相同。请将修改前的友情链接列表的出现和消失动画样式保留，不需要跟随鼠标，改为固定时长的动画即可。请注意屏幕中央的截图渲染。
```
感觉弹出的位置还可以再往下改改 改到角落那里 但先睡个觉先
---
浅色模式有问题 寄
---
新提示词
```
请修改官网website中友情链接的位置。首先移除当前的友情链接触发方式和列表，之后在按钮的第二排最右边”Github“右边新建一个友情链接按钮，并在点击后固定在友情链接按钮右边紧贴着展示友情链接列表，列表需尽可能与友情链接的按钮对齐，若无法对齐则让其低端固定在窗口底部以上，不要超出窗口范围，并根据内容列表长度调整窗口高度。按钮的样式需和其他按钮相同，列表的样式需和修改前相同。请将修改前的友情链接列表的出现和消失动画样式保留，不需要跟随鼠标，改为固定时长的动画即可。请注意屏幕中央的截图渲染，并注意同时修改暗色模式和亮色模式。
友情链接列表窗口出现的位置存在问题，应该在”友情链接“按钮的右边；截图的交互方式也存在问题，应不再和友情链接交互，请检查要求并继续修改
点击友情链接按钮后没有反应，请继续检查并修复
友情链接按钮问题仍未解决，请继续修复
同时，HomeActions.tsx的第86行存在(太长了复制不下)的问题，请一并修复
请为友情链接的列表添加另外的关闭方式，即点击除列表窗口以外的区域即关闭 …
```
> feat: 官网友链改为按钮

- src/MaaCore/Task/Interface/DebugTask.cpp
- src/MaaCore/Vision/Battle/BattlefieldClassifier.cpp
- src/MaaCore/Vision/Battle/BattlefieldClassifier.h
- **模型训练**  
- 使用 **MobileNetV4** 重新训练了技能识别模型。  
- 模型由原先的二分类升级为 **三分类**，其中新增 “可取消” 技能状态。
- **代码更新**  
- 在技能识别的 `analyze` 函数中，支持了新的模型前处理逻辑，并添加了三分类的判断逻辑。  
- 更新了 `debugtask` 中的技能识别测试用例，以适配新的三分类模型。
> feat: 优化技能识别模型

- resource/global/YoStarEN/resource/tasks/Roguelike/Sarkaz.json
issue reported from discord, current roi would cause a cutoff at ```Confi```, and only for EN since all other languages have their confirm in two wide characters
> fix: EN RoutingRefreshNodeConfirm roi too small

- resource/tasks/Roguelike/base.json
For whatever reason current dev complains about ```Duplicate key in json file: MaaAssistantArknights\x64\Debug\resource\tasks\Stages\SS.json SS-Open``` on my environment, so I'm unable to test this myself. Shouldn't really be a problem as a one-liner tho.
> fix: CheckLevelMax too fast without delay

- docs/zh-cn/develop/development.md
- docs/zh-tw/develop/development.md
Typo 位置在[文档此小节](https://maa.plus/docs/zh-cn/develop/development.html#%E6%88%91%E4%BC%9A%E7%BC%96%E7%A8%8B-%E4%BD%86%E6%B2%A1%E6%8E%A5%E8%A7%A6%E8%BF%87-github-c-%E8%A6%81%E6%80%8E%E4%B9%88%E6%93%8D%E4%BD%9C)的第 11 条。
简体中文：![image](https://github.com/user-attachments/assets/bd4ca1c7-96f9-4127-bea5-8608612d79cf)
繁体中文：![image](https://github.com/user-attachments/assets/26bc029c-a0e5-42ab-bb36-4d1a09cf1112)
很明显 `Rull Request` 应为 -> `Pull Request`。经检查，只有简中和繁中语言出现问题，其他语言包括英语都是正确的 `Pull Request`。
> 小声说：心血来潮看 MAA 文档的时候看到的，这是本人第一次给 MAA 提 PR，逃~
> fix: 修复开发者帮助文档内的 Typo

- src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
Fixed typo in variable name 'cur_score' (misspelled 'cur_socre')
> fix: correct variable name typo in cur_score

- resource/custom_infrast/old/153_layout_3_times_a_day_20231103.json
- resource/custom_infrast/old/153_layout_4_times_a_day_20241106.json
- resource/custom_infrast/old/243_layout_4_times_a_day_20240608.json
- resource/custom_infrast/old/243_layout_4_times_a_day_20241216.json
- resource/custom_infrast/old/243_layout_4_times_a_day_20250310.json
- resource/custom_infrast/old/243_layout_4_times_a_day_20250412.json
让见行者和信仰搅拌机到会客室上班 / Let Enforcer and Sankta Miksaparato work in the reception room
顺便补上了之前忘记备份到 old 子目录下的旧排班表（取 custom_infrast 目录内自 commit 3f858de 之后所有 feat 类改动的前一个版本，fix/chore 就不要了）
PS. 这次是我自己做的调整，公孙长乐的排班表并没有变化（他的视频不排会客室），不过还是把视频链接也更新了一下，另外考虑到用到了最新实装的干员，所以本 commit 也还是标记为 feat 吧
> feat: 更新 243 极限效率一天四换排班表（20250507 修订）

- src/MaaCore/Task/BattleHelper.cpp
- src/MaaCore/Task/Miscellaneous/BattleProcessTask.cpp
- src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
fix: 开始战斗前闪退无限循环识别，关卡名检查放宽至一分钟
> fix: 开始战斗前闪退无限循环识别，关卡名检查放宽至一分钟

- src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
- src/MaaCore/Task/Infrast/InfrastAbstractTask.h
- src/MaaCore/Task/Infrast/InfrastProductionTask.cpp
肉鸽用不了，没有对应职业的话是灰的，除非全部匹配一遍，反正不长，还是慢慢划吧
fix #11782
> perf: 基建使用切换职业栏返回列表最左侧

- .github/workflows/markdown-checker.yml
不知道是 Github 的 Rate limit 更低了还是怎么回事。最近 check dead links 就没通过过，所以暂时不检查 github 的链接来避免这个问题。
> ci: don't check github link

- resource/tasks/tasks.json
- src/MaaCore/Task/BattleHelper.cpp
- src/MaaCore/Task/BattleHelper.h
- src/MaaCore/Task/Experiment/CombatRecordRecognitionTask.cpp
- src/MaaCore/Task/Miscellaneous/BattleProcessTask.cpp
- src/MaaCore/Vision/Battle/BattlefieldMatcher.cpp
- src/MaaCore/Vision/Battle/BattlefieldMatcher.h
理想环境测试：待部署1，无技能检测，单步骤等费用
没上费用缓存
没开GPU加速
开了GPU加速
上费用ocr缓存
不开GPU加速
开GPU加速
> feat: 自动战斗费用识别缓存, 减少性能消耗

- docs/zh-cn/manual/cli/config.md
- docs/zh-cn/manual/cli/install.md
Bump maa-cli to 0.5.5.
See [maa-cli changelog](https://github.com/MaaAssistantArknights/maa-cli/releases/tag/v0.5.5) for more details.
主要就是加了个 Waydriod 支持以及适配了一下新版倍战。
> chore: bump maa-cli to 0.5.5

- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
由于在`连战次数(Series)`与`指定次数`联动后，存在以 `指定次数`=2，`连战次数`=3 运行MAA的情况，修改`连战次数`的中文描述以贴近游戏描述
@Constrat Need I modify EN's?
> i18n: wpf CN 修改描述`连战次数` -> `代理倍率`

- src/MaaWpfGui/Res/Localizations/en-us.xaml
i18n: 更正英文本地化文本中训练室提示文本的标点问题
i18n: 更正英文本地化文本中有关特别标记干员的语法问题
> i18n: 更正英文本地化文本中的两处错误

- src/MaaWpfGui/Views/UserControl/TaskQueue/InfrastSettingsUserControl.xaml
当基建模式设置为“队列轮换”时，高级设置中的“不将已进驻的干员放入宿舍”项旁的提示图标未正确隐藏
Resolves #12981
> fix: 基建高级设置中部分元素未正确隐藏

- docs/zh-cn/develop/linux-tutorial.md
只看主仓库的文档，不看 MaaMacGUI 项目的话，就不知道有这个自动化编译脚本可以用。所以在文档中添加这一段。建议 Mac 开发的直接去看 MaaMacGUI 项目。
> docs: 更新Linux开发环境配置教程 加入 Mac 开发建议

- resource/global/YoStarKR/resource/tasks/Stages/HS.json
iirc, SSReopen-HS required HS-OpenOpt. It could be the same for other global server.
log
``` python
[2025-07-03 22:44:14.211][TRC][Px4300][Tx6428] asst::ProcessTask::run | enter
[2025-07-03 22:44:14.211][INF][Px4300][Tx6428] {"class":"asst::ProcessTask","details":{"cur_retry":0,"retry_times":0,"to_be_recognized":["HS-OpenOpt"]},"first":["HS-OpenOpt"],"pre_task":"","subtask":"ProcessTask","taskchain":"Fight","taskid":4}
[2025-07-03 22:44:14.211][ERR][Px4300][Tx6428] Unknown task: HS-OpenOpt
[2025-07-03 22:44:14.211][ERR][Px4300][Tx6428] Task HS-OpenOpt not found
```
> fix: YostarKR HS rerun navigation

- src/MaaCore/Task/Interface/CopilotTask.cpp
- src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp
- src/MaaCore/Task/Miscellaneous/BattleFormationTask.h
- src/MaaWpfGui/Models/AsstTasks/AsstCopilotTask.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
- src/MaaWpfGui/Views/UI/CopilotView.xaml
给自动编队加了个选项，用来控制当模组不满足要求时是否忽略模组要求
checklist:
> perf: 添加自动编队选项 忽略干员属性要求

- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
I'm not sure if it seems well if doing same thing in overseas resource. like uppercase and plural forms
@HX3N @Manicsteiner 
checklist:
> i18n: wpf`干员`统一使用指定字符串资源

- src/MaaWpfGui/Constants/ConfigurationKeys.cs
- src/MaaWpfGui/Helper/AchievementTrackerHelper.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UserControl/Settings/AchievementSettingsUserControlModel.cs
- src/MaaWpfGui/Views/UserControl/Settings/AchievementSettings.xaml
在设置-成就设置中，添加设置勾选框选项：“禁用自动弹出成就气泡”
fix #13315 
“成就气泡弹出后一段时间关闭”（已摘到dev）
· 如果勾选了“成就气泡弹出后一段时间消失”：成就气泡弹出后 经过15s后消失
> feat: 禁用弹出成就气泡

- docs/zh-cn/protocol/integration.md
- resource/tasks/tasks.json
- src/MaaCore/Task/Infrast/InfrastReceptionTask.cpp
- src/MaaCore/Task/Infrast/InfrastReceptionTask.h
- src/MaaCore/Task/Interface/InfrastTask.cpp
- src/MaaWpfGui/Constants/ConfigurationKeys.cs
- src/MaaWpfGui/Models/AsstTasks/AsstInfrastTask.cs
- src/MaaWpfGui/Res/Localizations/en-us.xaml
- src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- src/MaaWpfGui/Res/Localizations/ko-kr.xaml
- src/MaaWpfGui/Res/Localizations/zh-cn.xaml
- src/MaaWpfGui/Res/Localizations/zh-tw.xaml
- src/MaaWpfGui/ViewModels/UserControl/TaskQueue/InfrastSettingsUserControlModel.cs
- src/MaaWpfGui/Views/UserControl/TaskQueue/InfrastSettingsUserControl.xaml
close #6210.
解耦线索赠送逻辑 默认启用线索交流时与之前的行为一致
关闭线索交流时不再赠送线索 仅尝试在线索未满时收取线索 若已满则跳过该步骤 以便用户手动处理线索
> feat: 新增是否进行线索交流选项

- src/MaaCore/Common/AsstBattleDef.h
- src/MaaCore/Task/Roguelike/RoguelikeConfig.h
修复了两处warning：
- missing field 'requirements' initializer 
- definition of implicit copy assignment operator for 'RoguelikeStatus' is deprecated because it has a user-declared copy constructor.
（其实并没有改变代码行为）
> fix: clang编译警告

- src/Python/asst/downloader.py
- src/Python/asst/updater.py
由于 http://ota2.maa.plus/ 无法连接，github需要重定向，无法直接获取文件头长度，导致原来的代码逻辑不可更新，会直接报错停止运行，于是进行了（临时性的，不是很优雅，每个分块都会被重定向一遍，但是要改好麻烦）的修复，使pyhon脚本支持从github获取文件长度并更新（需要代理）
> fix: 使 python 脚本支持从 github 获取文件长度并更新

- resource/tasks/RA/Tales.json
> fix: 修正生息演算中 "丰饶灌木林" 的 OCR 识别

- resource/tasks/MiniGame/ALL.json
{"class":"asst::ProcessTask","details":{"cur_retry":20,"retry_times":20,"to_be_recognized":["MiniGame@ALL@GreenGrass@DuelChannel@Begin","MiniGame@ALL@GreenGrass@DuelChannel@End"]},"first":["MiniGame@ALL@GreenGrass@DuelChannel@Begin"],"pre_task":"MiniGame@ALL@GreenGrass@DuelChannel@End","subtask":"ProcessTask","taskchain":"Custom","taskid":1}
这里容易超时。
> fix: 给 `MiniGame@ALL@GreenGrass@DuelChannel@End` 加点延迟

- cmake/config.cmake
由于多了一个大括号（}），导致 cmake 在找不到库时不会自动终止。
> fix: 修复 cmake copy_and_add_rpath_library 的失败逻辑

- docs/.vuepress/config.ts
通过将giscus的`strict`设置为`false`，暂时解决此问题
> fix: 暂时修复无法读取过去的评论的问题

- src/MaaWpfGui/States/RunningState.cs
0>RunningState.cs(49,46): Warning CS8622 : “void RunningState.TimeoutReminderTimer_Elapsed(object sender, ElapsedEventArgs e)”的参数“sender”类型中引用类型的为 Null 性与目标委托“ElapsedEventHandler”不匹配(可能是由于为 Null 性特性)。
0>RunningState.cs(41,17): Warning CS8618 : 在退出构造函数时，不可为 null 的 事件 "TimeoutOccurred" 必须包含非 null 值。请考虑添加 "required" 修饰符或将该 事件 声明为可为 null。
0>RunningState.cs(80,46): Warning CS8625 : 无法将 null 字面量转换为非 null 的引用类型。
0>RunningState.cs(80,52): Warning CS8625 : 无法将 null 字面量转换为非 null 的引用类型。
0>RunningState.cs(38,37): Warning CS8618 : 在退出构造函数时，不可为 null 的 字段 "_instance" 必须包含非 null 值。请考虑添加 "required" 修饰符或将该 字段 声明为可为 null。
> chore: fix build warning

- src/MaaCore/Controller/PlayToolsController.cpp
本次 PR 修复了在Mac端开始任务时明日方舟意外退出或连接断开由PlayToolsController 导致的程序崩溃问题
问题根源在于：~PlayToolsController() 调用 close()，而 close() 内部的 m_socket.shutdown() 和 m_socket.close() 在连接已经断开的情况下会抛出 boost::system::system_error。
在 C++ 析构函数中未捕获的异常会导致程序立即调用 std::terminate() 并退出。
修复措施： 在 close() 函数中，为 m_socket.shutdown() 和 m_socket.close() 操作添加了独立的 try-catch 块，确保在清理资源时，即使网络操作失败，也不会导致程序崩溃。
> fix: 增强playtools关闭连接时的异常处理，确保套接字安全关闭

- resource/tasks/RA/Tales.json
有用户反映，会随机在进入节点时卡住而导致任务失败。
怀疑进入任务后 MAA 识别过快导致在动画过渡阶段错误地以为编队人数超过 6 人，并尝试删除编队。
然后因为点击太快未能生效，于是卡在了点击确认这一步。
现尝试予以修复。
> fix: 尝试修复生息演算任务识别并删除编队时卡住的问题
