README.md
这怎么说啊。。。。。。
氵就硬氵
反正是 readme 不急着合并吧，我过段时间再翻修一下（试图
Allow edits by maintainers
=> docs.替换 Visual C++ Redistributable 链接

src/MeoAssistant/Linux编译教程.md
=> fix linux env

README.md
顺便好像还格式化了哪里？忘了
血糖低，干饭去了
Allow edits by maintainers
=> docs.修改闪退问题解决方案

README.md, src/MeoAsstGui/UserControl/VersionUpdateSettingsUserControl.xaml, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
=> perf.优化来自 #184 的问题，添加基于 C# 原生的下载方式

src/MeoAssistant/Assistant.cpp, src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/BattleImageAnalyzer.cpp, src/MeoAssistant/HashImageAnalyzer.cpp, src/MeoAssistant/InfrastControlTask.cpp, src/MeoAssistant/InfrastOfficeTask.cpp, src/MeoAssistant/InfrastPowerTask.cpp, src/MeoAssistant/InfrastProductionTask.cpp, src/MeoAssistant/OcrImageAnalyzer.cpp, src/MeoAssistant/RecruitTask.cpp, src/MeoAssistant/RoguelikeFormationImageAnalyzer.cpp, src/MeoAssistant/TemplResource.cpp
=> Boring revision

resource/tasks.json, src/MeoAssistant/AutoRecruitTask.cpp, src/MeoAssistant/AutoRecruitTask.h
恶劣的网络环境指高丢包低网速的网络（也就是我们晚上的校园网_(:3」∠)_）
在这种情况下由于游戏加载速度太慢，MAA 除了刷理智功能外，其他功能基本都存在各种问题。
由于只能在晚上进行测试，所以先开个 draft。
=> fix. 网络环境较为恶劣时无法正常执行

src/MeoAsstGui/Helper/ToastNotification.cs, src/MeoAsstGui/MeoAsstGui.csproj, src/MeoAsstGui/UserControl/ToastSettingsUserControl.xaml, src/MeoAsstGui/UserControl/ToastSettingsUserControl.xaml.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/Views/SettingsView.xaml
* 通知显示可以设置为屏幕任意 8 个位置的其中一个位置、也可以设置为不显示
* 增加通知时任务栏闪烁提醒
> 看了 `dev` 分支里已经不再更新界面了、只好更新还有界面的 `master` 分支
> 这也许是最后一次为旧版WPF界面做的贡献了、为旧版界面退休前尽最后一份力
> 同时也祝新版界面早日完成上线、为大佬加油 \_(:з」∠)\_
=> feat. 增加通知显示位置的设置选项 (#348)

resource/tasks.json
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/400
=> fix.修复打开`愚人号`关卡时，各种任务出错的问题

src/MeoAssistant/Assistant.cpp, src/MeoAssistant/ProcessTask.cpp, src/MeoAssistant/ProcessTaskImageAnalyzer.cpp
增加一些日志输出
- [在因配置错误导致的指针失效时向日志输出信息](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e5fce05360b4ef5fd8b035ad3e57fe3f83409185)
- [把`append_fight`的参数输出到日志](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/a74ceac11608bf85885d9d90c10ecd4925973d07)（ #427）
~~我又来水pr啦~~
=> perf.增加一些日志

README.md, appveyor.yml
=> chore. Update appveyor config

resource/tasks.json, src/MeoAssistant/TaskData.cpp
总结一下
1. [修复`残阳`章节没有开启导致的关卡`1-7`导航失效问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/450/commits/301a282f96fac0c16cb9a9fa19857d487fcf1a4e)
2. [修复把关卡`1-1*`识别成关卡`1-1`的bug](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/450/commits/7ea44668b008629ca0862617bcd681a297ff97af)
3. 加快关卡`1-7`导航速度（[`1db9e79`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/450/commits/1db9e797dc73c5aa562160abcd945f7c7c275eca)，[`43177d9`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/450/commits/43177d9bc19567693a18555a8a4e640d2fdd2340)）
4. 其他（[`ff79ca0`](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/450/commits/ff79ca0a07276a5802733ddcaa230652ef99732b)，[`778888b`](https://github.com/MaaAssistantArknights/MaaAssi …
=> fix.修复已知的1-7导航失效问题

3rdparty/include/penguin-stats-recognize/result.hpp
This error seems caused by gnustl vector, I do not know
how to fix it, so I use macro to change container to deque
under gnustl, use deque under other STL library will also
cause problem.
=> fix: Fix build error on Linux with gnustl

.github/workflows/maa-doc-azure-deploy.yaml, docs/Linux编译教程.md
=> chore.优化文档CI/CD使得在fork上不运行

src/MeoAssistant/Logger.hpp
=> 修复了linux编译Logger.hpp报错

src/MeoAsstGui/UserControl/FightSettingsUserControl.xaml, src/MeoAsstGui/UserControl/VersionUpdateSettingsUserControl.xaml, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
=> feat.优化检查更新的UI

src/MeoAssistant/MeoAssistant.vcxproj, src/MeoAssistant/Version.h, tools/build_release.bat, tools/version.sh
u1s1, 之前替换文件有点 low
~~就是不知道会不会炸了 CICD~~
=> perf.以一种更加优雅的方式生成版本号

tools/CopilotDesinger/CopilotJsonConverter.html
feature: 
1. 修改action Table干员field 成auto complete（发现会有非出击干员比如海嗣，温蒂的小人等等）
2.干员新增判定，不能同干员增加两次
3. 修改出击干员同步修改action Table
4. Edit 会滑到改动区域（简易版）应对太多Action的情况
5. 修复一些bug（主要来自玛丽背刺）
=> 新增N个feature

src/MeoAsstGui/ViewModels/SettingsViewModel.cs
=> 修复无法保存adb连接地址的bug

src/MeoAsstGui/ViewModels/CopilotViewModel.cs, src/MeoAsstGui/ViewModels/RootViewModel.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/Views/RootView.xaml
fix.规避自动战斗作业文件不能用中文路径文件名的bug; 
feat.标题栏增加显示模拟器和连接地址
=> fix.规避自动战斗作业文件不能用中文路径文件名的bug; feat.标题栏增加显示模拟器和连接地址

tools/CopilotDesinger/CopilotDesinger.py, tools/CopilotDesinger/main.py
写了个自动生成作业json文件的py脚本
写完才发现有现成的(为什么不在文档里提一下啊喂,写了好久的说
main.py里是示例,可能就比那个html版的多个能生成可替换干员的功能吧
用python写是为了好以后写爬虫自动生成作业做准备(不是
=> 添加自动生成作业工具

tools/CopilotDesinger/index.js
=> 为群组添加“新增干员”按钮

tools/CopilotDesinger/index.js, tools/CopilotDesinger/自动战斗作业生成器.html
1. 添加了自动完成
2. 添加了上移/下移按钮
3. 调整了UI位置
=> 添加重构后丢失的功能

docs/模拟器支持.md
=> docs.更新HyperV的操作描述

tools/CopilotDesinger/index.js
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/692
=> Hotfix Issue 692

docs/模拟器支持.md
update 模拟器支持.md 更人性化的表达方式对于Bluestack for hyperv
=> update 模拟器支持.md 更人性化的表达方式对于Bluestack for hyperv

README.md, src/Java/Maaj/Readme.md, src/Java/Maaj/src/main/java/com/iguigui/maaj/dto/request.kt, src/Java/Maaj/src/main/java/com/iguigui/maaj/routing/HttpRouting.kt, src/Java/Maaj/src/main/java/com/iguigui/maaj/service/MaaInstance.kt, src/Java/Maaj/src/main/java/com/iguigui/maaj/service/MaaService.kt
1. 增加了一个getImage接口。
2. 微调了主页文档增加了HTTP接口部分内容。
=> doc.HTTP接口相关文档优化

src/MeoAssistant/AutoRecruitTask.cpp, src/MeoAssistant/RecruitCalcTask.cpp, src/MeoAssistant/RecruitCalcTask.h, src/MeoAsstGui/Helper/AsstProxy.cs, src/MeoAsstGui/Helper/ToastNotification.cs
=> [Enhancement] 小车提示

README.md
=> 更新 Readme.md 加入fastgit镜像渠道

src/MeoAsstGui/Helper/AsstProxy.cs
TODO: 把"darkred"和"darkgoldenrod"分别存成error和warning的default color string
=> [Perf] 改进了颜色

src/MeoAsstGui/ViewModels/CopilotViewModel.cs, src/MeoAsstGui/Views/CopilotView.xaml
=> [New Feature] 允许拖拽导入作业

src/MeoAsstGui/ViewModels/SettingsViewModel.cs
Reverts MaaAssistantArknights/MaaAssistantArknights#824
=> Revert "解决无法带命令启动模拟器"

tools/MaaBuilder/Build.cs
=> fix. 修复 CI 的一堆问题

resource/config.json, src/MeoAssistant/Assistant.cpp, src/MeoAssistant/CloseDownTask.cpp, src/MeoAssistant/CloseDownTask.h, src/MeoAssistant/Controller.cpp, src/MeoAssistant/Controller.h, src/MeoAssistant/GeneralConfiger.cpp, src/MeoAssistant/GeneralConfiger.h, src/MeoAssistant/MeoAssistant.vcxproj, src/MeoAssistant/MeoAssistant.vcxproj.filters, src/MeoAssistant/StopGameTaskPlugin.cpp, src/MeoAssistant/StopGameTaskPlugin.h, src/MeoAsstGui/Helper/AsstProxy.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
=> add: 增加了任务完成关闭游戏的功能

src/MeoAsstGui/UserControl/TimerSettingsUserControl.xaml, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
This PR adds multiple timers support, in case users wish to set a more granular timer schedule.
In the future, we could use a more advanced cronjob-like scheduler, allowing users to add arbitrary triggers for their needs.
=> feat: add multiple timers support (up to 8)

src/MeoAsstGui/Views/CopilotView.xaml
=> [New Feature] 现在Copilot界面支持拖拽文件至面板中任意位置

src/MeoAsstGui/UserControl/FightSettingsUserControl.xaml, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
=> feat: 优化`吃理智药`和`吃石头`的相关选项

src/MeoAssistant/Logger.hpp
- 去除日志行尾多余的空格
- 去除 `| enter` 和 `| leave` 前多余的空格
- 文件流失败时也尝试重新打开
- ...
=> 对 Logger 的一些修改

src/MeoAsstGui/Bootstrapper.cs, src/MeoAsstGui/Helper/TrayIcon.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
顺便减轻了传错SetTrayIconInSettingsViewModel参数的后果，不抛异常了，最多打Log（感觉直接抛异常崩程序有点不友好
=> 任务栏图标支持 开始长草 和 全部停止

src/MeoAssistant/AsstTypes.h, src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1158
=> feat: 修复并优化部分肉鸽代码

src/MeoAsstGui/Helper/AsstProxy.cs, src/MeoAsstGui/Helper/ToastNotification.cs, src/MeoAsstGui/Helper/TrayIcon.cs, src/MeoAsstGui/ViewModels/RootViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs, src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs
=> fix: 修复完成任务后的退出不会销毁托盘的问题

src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
=> fix: 修复关卡选择时间错误

src/MeoAssistant/AsstTypes.h, src/MeoAssistant/BattleProcessTask.cpp, src/MeoAssistant/RoguelikeBattleTaskPlugin.cpp
- 简化肉鸽干员朝向评分
- 增加了 `asst::Point` 相关的函数
- 修改部署干员时拖动的距离的计算方法
看上去 `BattleProcessTask` 和 `RoguelikeBattleTaskPlugin` 有些重复的代码? 还有 `duration` 是应该乘以 1000 还是乘以 800 (
=> 简化肉鸽干员朝向评分等

resource/roguelike_recruit.json, tools/ResourceUpdater/ResourceUpdater.vcxproj, tools/ResourceUpdater/main.cpp, tools/RoguelikeResourceUpdater/generate_roguelike_recruit.py
=> feat: 修复几个肉鸽干员等级错误，增加新干员的信息

src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs, src/MeoAsstGui/Views/VersionUpdateView.xaml
主要是加了个贡献者的超链接
<div align=center><img src="https://user-images.githubusercontent.com/74587068/181817248-bcfd8fc4-4660-41bc-915a-ac8c7b8ca471.png" width=75% /></div>
（图上 Markdown 部分可以滚动）
=> feat: 优化更新时的 Changelog 弹窗样式

src/MeoAssistant/RoguelikeRecruitTaskPlugin.cpp
肉鸽招募券支持翻页三次。
- 可以改善希望不足6点时，某些招募券会取消招募的问题（重装、先锋、特种）
可能存在的问题：
- 翻页可能卡在干员头像中间（只显示了一半），导致某些干员不能识别。
=> feat: 肉鸽招募券支持翻页

README_ja-JP.md, resource/tasks.json, src/MeoAssistant/AsstConf.h, src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/Controller.cpp, src/MeoAssistant/Controller.h
=> Release v4.2.1

src/MeoAssistant/AbstractTask.h, src/MeoAssistant/Assistant.cpp, src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/TaskData.h
=> perf: 使用 concept 优化代码

resource/roguelike_recruit.json, src/MeoAssistant/AutoRecruitTask.cpp, src/MeoAsstGui/Resources/Localizations/en-us.xaml, src/MeoAsstGui/Resources/Localizations/ja-jp.xaml, src/MeoAsstGui/Resources/Localizations/ko-kr.xaml, src/MeoAsstGui/Resources/Localizations/pallas.xaml, src/MeoAsstGui/Resources/Localizations/zh-tw.xaml, src/MeoAsstGui/UserControl/AboutUserControl.xaml, src/MeoAsstGui/UserControl/RoguelikeSettingsUserControl.xaml, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs, src/MeoAsstGui/Views/CopilotView.xaml
=> Release v4.2.2

.github/workflows/dev-build.yml, tools/MaaBuilder/Builder/CI/Build.CI.GitHubActions.DevBuild.cs, tools/MaaBuilder/Builder/Job/Build.Job.Bundle.cs
=> 修复 MaaBuilder 的一些错误

.github/labeler.yml, .github/workflows/labeler.yml
**尽量不要手动给一个 issue 增加/删除分类标签，因为手动增加/删除的分类标签在修改 issue 后会被 labeler 恢复原样**
新特性：
- 在 issue 里加上 ``add `LABEL` `` 可以强制加上一个标签，    
加上``remove `LABEL` `` 可以强制去掉一个标签，    
加上`remove all labels` 可以强制去掉所有标签。    
（新评论没用，建议放在 `` 里）
- 每次修改 issue 都会触发 labeler（新评论/修改新评论 不会触发）
~~正则表达式写的很屎，能不看尽量别看~~
=> chore: 调整 labeler

.github/labeler.yml
- 把 labeler 日文字符集改用 `[\u3040-\u30ff]`
- 增加 labeler 标签 `MAA Team`
- 调整格式
=> chore: 改进 labeler

.github/labeler.yml, .github/workflows/labeler.yml
=> chore: 使用 zzyyyl/issue-checker

.github/issue-checker.yml, .github/workflows/issue-checker.yml, .github/workflows/labeler.yml
- 尝试给 pr 增加权限（之前不能给 pr 加 labels，会报 `Resource not accessible by integration`）（草，怎么还是没有权限）
- 用新特性 `disabled-if` 取代大部分原来复杂的正则匹配
- 用新特性 `author_association`， 包含 `MEMBER` 的作者全部加上 `MAA Team` 的标签
=> chore: 更新 issue-checker

.github/issue-checker.yml, .github/workflows/issue-checker.yml
- 增加 处理事件 `issue_comment`
- 增加 某个 commit `fixed`/`close` 某个 issue 时自动给对应 issue 打上 `fixed` 标签
=> chore: 更新 zzyyyl/issue-checker

src/MeoAsstGui/Helper/AsstProxy.cs, src/MeoAsstGui/Helper/LogColor.cs, src/MeoAsstGui/Helper/LogItemViewModel.cs, src/MeoAsstGui/MeoAsstGui.csproj, src/MeoAsstGui/ViewModels/CopilotViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
=> refactor. uniform color style

docs/集成文档.md, resource/tasks.json, src/MeoAssistant/FightTask.cpp, src/MeoAssistant/FightTask.h, src/MeoAssistant/MeoAssistant.vcxproj, src/MeoAssistant/MeoAssistant.vcxproj.filters, src/MeoAssistant/StageNavigationTask.cpp, src/MeoAssistant/StageNavigationTask.h
=> feat: 支持全部主线关卡导航（仅 core 部分）

src/MeoAssistant/Assistant.cpp, src/MeoAssistant/Controller.cpp, src/MeoAssistant/CreditShopImageAnalyzer.cpp, src/MeoAssistant/DepotRecognitionTask.cpp, src/MeoAssistant/InfrastFacilityImageAnalyzer.cpp, src/MeoAssistant/InfrastOperImageAnalyzer.cpp, src/MeoAssistant/InfrastPowerTask.cpp, src/MeoAssistant/ItemConfiger.cpp, src/MeoAssistant/OcrImageAnalyzer.cpp, src/MeoAssistant/RecruitConfiger.cpp, src/MeoAssistant/RoguelikeRecruitImageAnalyzer.cpp, src/MeoAssistant/StageDropsImageAnalyzer.cpp
=> perf: 简化部分 lambda 表达式的写法

src/MeoAsstGui/Resources/Localizations/en-us.xaml, src/MeoAsstGui/Resources/Localizations/ja-jp.xaml, src/MeoAsstGui/Resources/Localizations/ko-kr.xaml, src/MeoAsstGui/Resources/Localizations/pallas.xaml, src/MeoAsstGui/Resources/Localizations/zh-cn.xaml, src/MeoAsstGui/Resources/Localizations/zh-tw.xaml, src/MeoAsstGui/UserControl/FightSettingsUserControl.xaml, src/MeoAsstGui/UserControl/GUISettingsUserControl.xaml, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
稍微测试了下导航应该是没什么问题，但是这个控件是否显示不能实时切换，试了下绑定到Idle是可以实时隐藏的，应该是少了啥东西
=> feat: 增加备选关卡功能

.github/issue-checker.yml, docs/IssueBot使用方法.md
=> docs: 更新 issue-checker 文档

src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/AutoRecruitTask.cpp
=> chore: 修复 Windows 下公招结果上传失败的问题

src/MeoAsstGui/.editorconfig, src/MeoAsstGui/Helper/AsstProxy.cs, src/MeoAsstGui/ViewModels/CopilotViewModel.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs
修复 warnings & suggestions：指把警告等级降低（x
=> perf: fix c# warnings & suggestions

src/MeoAsstGui/ViewModels/RootViewModel.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/Views/RootView.xaml
=> feat: 在标题栏上添加版本号

.github/issue-checker.yml
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1622#issuecomment-1221493877
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1622#issuecomment-1221494498
自动增加/删除 `incomplete`。
可能有点问题（应该没问题了？），有没有人帮我看看正则写的对不对（？
加 `incomplete` 时判断是否匹配 `\[Uploading asst(?:.bak|)(?: - 副本|).(?:zip|log)…\]\(\)`
去 `incomplete` 时判断是否匹配 `\[asst(?:.bak|)(?: - 副本|).(?:zip|log)\]\([^\)]+\)`
ps: 什么，我的 action 功能居然这么强？增删居然能分开判断！
=> chore: 增加 issue-checker 标签 `incomplete`

resource/roguelike_recruit.json
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1633
=> feat: 不再在肉鸽招募 `行商` 干员，加入一些 `傀儡师` 和 `伏击客` 干员

src/MeoAssistant/Logger.hpp
之前的 Logger 是 @horror-proton 基于 c++17 的语法修改的，不支持 `ranges`。
现在把 `is_range_expression` -> `ranges::input_range`，应该支持了 `ranges`。
把之前 `requires` 回退了一下，看上去还是 `if constexpr` 比较好理解（
=> feat: 更新 Logger

src/MeoAsstGui/Helper/DragItemViewModel.cs, src/MeoAsstGui/Helper/ViewStatusStorage.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
=> feat: 统一gui.json保存的内容，解决本地化不兼容问题

src/MeoAsstGui/UserControl/FightSettingsUserControl.xaml, src/MeoAsstGui/Views/TaskQueueView.xaml
=> feat: 优化图形化界面

src/MeoAsstGui/Helper/DragItemViewModel.cs, src/MeoAsstGui/Helper/ViewStatusStorage.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
Reverts MaaAssistantArknights/MaaAssistantArknights#1652
=> Revert "feat: 统一gui.json保存的内容，解决本地化不兼容问题"

src/MeoAsstGui/Helper/LogItemViewModel.cs, src/MeoAsstGui/UserControl/FightSettingsUserControl.xaml, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs, src/MeoAsstGui/Views/RootView.xaml, src/MeoAsstGui/Views/TaskQueueView.xaml
1. **修复** 某些语言下 界面消息栏显示不全的问题 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1648
2. 合并 `LinkStart` 和 `停止` 按钮 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1648#issuecomment-1227206510
3. 禁止缩小界面 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1648#issuecomment-1226769109
4. 增加 `修改` 按钮宽度
5. 调整 一些 UI 控件
=> feat: 优化图形化界面 (fix #1648)

README.md, README_en-US.md, README_ja-JP.md, README_zh-TW.md, src/MeoAssistant/MeoAssistant.vcxproj, tools/ResourceUpdater/ResourceUpdater.vcxproj, tools/TestCaller/TestCaller.vcxproj
~~2000 年了，~~ VS 终于把 Image Watch 的崩溃问题修掉了，升！！！
=> build: update to v143

src/MeoAsstGui/Helper/AsstProxy.cs, src/MeoAsstGui/Helper/ToastNotification.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs, src/MeoAsstGui/ViewModels/VersionUpdateViewModel.cs, src/MeoAsstGui/Views/TaskQueueView.xaml
主要两个修改：
1. `SetInited` [view](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c8086a0bcac2195dfb4a8812ad683798ceedcb4c#diff-c015324aff727c922690e0e5496a48f683b4f1069977adea2f961bab55f44cf3R1273)
2. `InverseShowVisibility` [view](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c8086a0bcac2195dfb4a8812ad683798ceedcb4c#diff-c015324aff727c922690e0e5496a48f683b4f1069977adea2f961bab55f44cf3R595)
其他部分基本上是格式优化。
=> perf: c# 代码逻辑&格式优化

docs/模拟器支持.md
=> docs: Update 模拟器支持.md

README.md
=> docs. 最近大陆地区镜像站网页打不开但下载正常，添加一个readme提示

README.md
Reverts MaaAssistantArknights/MaaAssistantArknights#1705
markdown 格式有问题，另外这种 Corner case 的操作细节，不要放在主文档里，不然主文档成垃圾场了
而且描述太反直觉了，比如我看到这段话，我第一反应是点这里，觉得需要一个更好的话术引导用户
=> Revert "docs. 最近大陆地区镜像站网页打不开但下载正常，添加一个readme提示"

src/MeoAssistant/AsstHttp.hpp, src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/MeoAssistant.vcxproj, src/MeoAssistant/MeoAssistant.vcxproj.filters, src/MeoAssistant/ReportDataTask.cpp, src/MeoAssistant/ReportDataTask.h
=> feat: 重构 Response 类

resource/config.json, src/MeoAssistant/AsstHttp.hpp, src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/AutoRecruitTask.cpp, src/MeoAssistant/AutoRecruitTask.h, src/MeoAssistant/MeoAssistant.vcxproj, src/MeoAssistant/MeoAssistant.vcxproj.filters, src/MeoAssistant/ReportDataTask.cpp, src/MeoAssistant/ReportDataTask.h, src/MeoAssistant/StageDropsTaskPlugin.cpp, src/MeoAssistant/StageDropsTaskPlugin.h
=> refactor: 重构数据汇报模块，新增支持企鹅物流的幂等机制

src/MeoAssistant/Controller.cpp, src/MeoAssistant/Controller.h
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1719
=> fix: 尝试修复部分模拟器行尾变化的问题

README.md, docs/开发相关.md
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1676#issuecomment-1236077085
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1727#issuecomment-1233793269
=> docs: 整理开发相关文档，增加 clang-format 配置相关文档

3rdparty/include/zlib/decompress.hpp, src/MeoAssistant/AbstractImageAnalyzer.cpp, src/MeoAssistant/AbstractTask.cpp, src/MeoAssistant/AbstractTask.h, src/MeoAssistant/AsstHttp.hpp, src/MeoAssistant/AsstTypes.h, src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/Controller.cpp, src/MeoAssistant/Controller.h, src/MeoAssistant/DepotImageAnalyzer.h, src/MeoAssistant/HashImageAnalyzer.cpp, src/MeoAssistant/InfrastAbstractTask.h, src/MeoAssistant/InfrastClueVacancyImageAnalyzer.h, src/MeoAssistant/InfrastOperImageAnalyzer.h, src/MeoAssistant/OcrPack.cpp, src/MeoAssistant/OcrPack.h, src/MeoAssistant/RecruitConfiger.h, src/MeoAssistant/ReportDataTask.cpp, src/MeoAssistant/StageDropsImageAnalyzer.cpp, src/MeoAssistant/Version.h
1. [继续优化行尾检测](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c95a0cf1e7e6a36dcce1d547d22bca24fde71bc2)。link to #1728 
2. [用 string 代替 vector<uchar> 进行数据处理](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/488f5070b55928fbeb033dcedad9dfcbf53c74f1)。
3. [perf: 优化 Utils](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/1741/commits/48d319d5e52ab3d5dac6ed7e90b1c74e9850a679) 
- `string_replace_all` 系列支持基础类型不一定为 char 的字符串
- `load_file_without_bom` 小优化
建议 review 的时候 commits 分开看（
=> perf: 整理并优化

src/MeoAssistant/AsstUtils.hpp
=> fix: fix linux build error

README_ja-JP.md
Japanese Tweaked（直訳っぽい日本語を調整）/ Unsupport text add（未対応部分に注釈追加）
=> docs: Update README_ja-JP.md

src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
The text was cut down to fit the UI.(一部をUIの表示幅に合わせて微調整) / Fixed wrong argument.（公開求人タブの項目が新規UIの引数に替わっていなかったのを修正）/　Added Depot Recognition was missing in its entirety.（Depot Recognitionがまるまる抜け落ちていたのを追加。）
=> Fixed and Tweaked.

src/MeoAssistant/Controller.cpp
=> fix: 修复连接时间过长的问题

src/MeoAssistant/AsstUtils.hpp, src/MeoAssistant/Logger.hpp
=> chore: 用 `operator<<` 重构 Logger

.github/issue-checker.yml
labeler 关键词好久没更新了，issue 里有没有能参考的关键词也可以加上
（要是不知道怎么改正则，来 comment 也行，我来加）
=> chore: 优化 labeler

src/MeoAssistant/Logger.hpp
=> perf: 让代码更加优雅

README_ja-JP.md
Text fix(一部テキスト修正) / Text tweak(リードミー回りの文章整形) /  4.4.1 Add Depot Recognition Line(倉庫アイテム認識の説明追加) / Screenshot change for 4.4.1
=> Doc:Text tweak Ver4.4.1

src/MeoAsstGui/Helper/AsstProxy.cs, src/MeoAsstGui/Helper/ComboBoxExtensions.cs, src/MeoAsstGui/Helper/StageInfo.cs, src/MeoAsstGui/UserControl/FightSettingsUserControl.xaml, src/MeoAsstGui/ViewModels/CopilotViewModel.cs, src/MeoAsstGui/ViewModels/DepotViewModel.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
主要就加点注释
然后 `NotCustomStageCode` 可以直接 `!CustomStageCode`
=> perf: fix c# warnings & suggestions，优化代码

docs/ja-jp/3.1-統合ドキュメント.md, docs/ja-jp/3.2-コールバックAPI.md
Move text 3-2 to 3-1
and 3-2 English document base text added
=> doc:japanese text fixed and added

CMakeLists.txt
=> chore: 修改 `CMakeLists.txt`

src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
"RemainingSanityStage" add Base EN.
=> doc:ja-jp.xaml add line.

src/MeoAssistant/Controller.cpp
=> fix: 修复 hProcess 返回值 259（STILL_ACTIVE）导致重连的问题

src/Java/Maaj/src/main/java/com/iguigui/maaj/easySample/MeoAssistant.java
=> fix: java doc集成文档地址

resource/roguelike_copilot.json
添加了新字段支持，优化站位，尝试解决 #1991 问题
希望格式没搞错
=> feat: Update `roguelike_copilot.json` [Skip module label]

src/MeoAsstGui/Bootstrapper.cs, src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
每次 GUI 启动时，若超过 16M, `gui.log` -> `gui.bak.log`
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/434
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/1939
=> feat: 界面上的日志保存到 `gui.log`

src/MeoAssistant/Task/Plugin/RoguelikeRecruitTaskPlugin.cpp
=> Improve Roguelike Recruitment

resource/tasks.json, src/MeoAssistant/Task/FightTask.cpp
1. fix #1468 
2. 在橙色开始行动界面进入任务时直接开始行动。
3. 一并支持在行动完成界面进入刷理智任务
=> fix: 修复在战斗中进入刷理智任务时任务崩溃的问题

src/MeoAsstGui/Resources/Localizations/en-us.xaml, src/MeoAsstGui/Resources/Localizations/ja-jp.xaml, src/MeoAsstGui/Resources/Localizations/zh-cn.xaml, src/MeoAsstGui/Resources/Localizations/zh-tw.xaml
fix: update roguelike mode text for the change at 4.6.0.alpha.8
=> fix: update roguelike mode text for the change at 4.6.0.alpha.8

resource/tasks.json, src/MeoAssistant/Task/Plugin/RoguelikeRecruitTaskPlugin.cpp
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2081
=> Release v4.6.0-beta.2

src/MeoAssistant/Task/Plugin/RoguelikeBattleTaskPlugin.cpp
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2065
=> fix: [workaround] 修复往水上放东西的问题

resource/roguelike_recruit.json
修改了水月肉鸽更适合的干员 提高了水月肉鸽对策卡的优先级，增加了全六星优先级
具体改动很多增加了不少干员 以及调整了优先级
=> feat: 优化水月肉鸽招募逻辑

src/MeoAsstGui/Views/TaskQueueView.xaml
=> perf: 将GUI日志信息改为上对齐

resource/tasks.json, src/MeoAssistant/Task/Sub/InfrastReceptionTask.cpp, src/MeoAssistant/Task/Sub/InfrastReceptionTask.h
=> fix: 修复了会客室把可以挂上的线索送出的问题

.gitmodules, CMakeLists.txt, src/Python/asst.py
为了方便编译，直接添加了 git submodule，不加的话要不就之后写到教程里。如果需要，我也可以把这个 repo 直接 transfer ownership 到 Maa organization（写的时候也没打算给别的项目用）。
总之这样终于可以编译出一个 macOS 能跑的版本了🎉
=> feat: 在 Apple 平台上使用 Vision 框架提供的 OCR

src/MeoAsstGui/Helper/ViewStatusStorage.cs
=> feat: 添加配置文件每日备份机制

package-definition.json, tools/MaaBuilder/Builder/Helper/Build.Helper.Bundler.cs, tools/MaaBuilder/Builder/Job/Build.Job.Bundle.cs
=> feat: package debug symbols

src/MeoAsstGui/Helper/TrayIcon.cs
=> perf: Hide MAA from the Windows Task Switcher when it is minimized

src/MeoAsstGui/ViewModels/TaskQueueViewModel.cs
=> fix: period设定时间不能准时开始

resource/tasks.json, src/MeoAssistant/Task/Plugin/RoguelikeSkillSelectionTaskPlugin.cpp
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2280
=> Release v4.6.2 fix

src/MeoAssistant/Task/Plugin/RoguelikeBattleTaskPlugin.cpp, src/MeoAssistant/Task/Plugin/RoguelikeBattleTaskPlugin.h
fix: 修复了远程/近战位干员无空位时不能部署任何干员的问题
=> fix: 修复了远程/近战位干员无空位时不能部署任何干员的问题

src/MeoAssistant/Task/Plugin/DrGrandetTaskPlugin.cpp, src/MeoAssistant/Task/Plugin/GameCrashRestartTaskPlugin.cpp, src/MeoAssistant/Task/Plugin/StageDropsTaskPlugin.cpp, src/MeoAssistant/Task/Sub/AbstractTask.cpp, src/MeoAssistant/Task/Sub/AbstractTask.h, src/MeoAssistant/TaskData.h
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2284
=> fix: 修复 reduce_other_times 不能正常工作的问题

docs/3.2-回调消息协议.md
=> docs: Update 3.2-回调消息协议.md

src/MeoAsstGui/Helper/StageManager.cs
=> fix: 移除长夜临光关卡选择

.github/workflows/dev-build-mac.yml, .github/workflows/release-maa-mac.yml, .gitmodules, CMakeLists.txt, include/AsstCaller.h, include/module.modulemap
- .github/workflow/*.yml
- 添加 macOS 编译的 CI
- 发布 MeoAsstMac App
- .gitmodules
- 添加 MeoAsstMac submodule
- 3rdparty/VisionOCR
- 使用预编译 opencv2.xcframework
- CMakeLists.txt
- 添加 macOS 相关编译设置
- 调整依赖，OpenCV 使用上述静态库
- include/AsstCaller.h
- 头文件兼容 C
- include/module.modulemap
- macOS 模块定义文件
CI 预览: [dev-build-mac](https://github.com/hguandl/MaaAssistantArknights/actions/workflows/dev-build-mac.yml), [release-maa-mac](https://github.com/hguandl/MaaAssistantArknights/actions/workflows/release-maa-mac.yml)
[Release 预览](https://github.com/hguandl/MaaAssistantArknights/releases/tag/v4.6.4-fork-2)
=> feat: 构建 macOS App

src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
=> doc: JP Add update line

src/MeoAssistant/Task/Plugin/StageDropsTaskPlugin.cpp, src/MeoAsstGui/Helper/AsstProxy.cs
=> feat: 合并本次掉落和掉落统计

docs/glossary/operators.md
Chapter 10(EN & JP)  + 狂人号(JP Only)
=> doc : Add operator

src/MeoAsstGui/Bootstrapper.cs, src/MeoAsstGui/Helper/MaaHotKeys/IMaaHotKeyActionHandler.cs, src/MeoAsstGui/Helper/MaaHotKeys/IMaaHotKeyManager.cs, src/MeoAsstGui/Helper/MaaHotKeys/MaaHotKey.cs, src/MeoAsstGui/Helper/MaaHotKeys/MaaHotKeyAction.cs, src/MeoAsstGui/Helper/MaaHotKeys/MaaHotKeyActionHandler.cs, src/MeoAsstGui/Helper/MaaHotKeys/MaaHotKeyManager.cs, src/MeoAsstGui/MeoAsstGui.csproj, src/MeoAsstGui/Resources/Localizations/en-us.xaml, src/MeoAsstGui/Resources/Localizations/ja-jp.xaml, src/MeoAsstGui/Resources/Localizations/ko-kr.xaml, src/MeoAsstGui/Resources/Localizations/pallas.xaml, src/MeoAsstGui/Resources/Localizations/zh-cn.xaml, src/MeoAsstGui/Resources/Localizations/zh-tw.xaml, src/MeoAsstGui/UserControl/HotKeyEditorUserControl.xaml, src/MeoAsstGui/UserControl/HotKeyEditorUserControl.xaml.cs, src/MeoAsstGui/UserControl/HotKeySettingsUserControl.xaml, src/MeoAsstGui/UserControl/HotKeySettingsUserControl.xaml.cs, src/MeoAsstGui/ViewModels/SettingsViewModel.cs, src/MeoAsstGui/Views/SettingsView.xaml
=> feat: 实现MAA基础热键

src/MeoAsstGui/Bootstrapper.cs, src/MeoAsstGui/Helper/IMainWindowManager.cs, src/MeoAsstGui/Helper/MaaHotKeys/MaaHotKeyActionHandler.cs, src/MeoAsstGui/Helper/MainWindowManager.cs, src/MeoAsstGui/Helper/TrayIcon.cs, src/MeoAsstGui/MeoAsstGui.csproj, src/MeoAsstGui/ViewModels/SettingsViewModel.cs
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/2379#issuecomment-1287973151
=> fix: 引入 `IMainWindowManager` 并修正 #2379 唤起MAA热键失效问题

src/MeoAssistant/Task/Sub/ProcessTask.cpp, src/MeoAssistant/TaskData.cpp, src/MeoAssistant/TaskData.h, src/MeoAssistant/Utils/AsstTypes.h, src/MeoAssistant/Utils/Logger.hpp, src/MeoAssistant/Utils/StringMisc.hpp
回调有修改，但是我看 action 和 algorithm 字段都没人用（
=> feat: 为部分枚举类型增加与字符串类型的互转函数

.github/workflows/release-ota.yml, tools/OTAPacker/build.sh, tools/OTAPacker/makeota.sh
=> chore: 更新 OTA 脚本, 同步 Pre-release 类型

tools/MaaBuilder/Builder/Job/Build.Job.Version.cs
in case I want custom tag name in nightly build
=> feat: 在 MaaBuilder 中允许通过环境变量手动设置 CommitVersion 的版本号

resource/tasks.json
- 删除章节导航的“未解锁”并使用 CharOcr
- 按照 Chapter - Episode - Stage 的顺序重新排序关卡导航相关 json
- 重命名了一些 task，合并了一些 task
=> feat: 优化关卡导航

src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
Hasn't this part of the argument changed?
この部分引数変わってないですか？
`<system:String x:Key="IdentifyTheMistakes">识别错误</system:String>`
=> doc: tweak and translation JP lines

src/Java/Maaj/Maa-HTTP-Server-startup.bat, src/Java/Maaj/src/main/java/com/iguigui/maaj/service/MaaService.kt
=> fix: 修复 javaPath 路径错误; 修复 maaPath 路径错误

resource/tasks.json, src/MeoAssistant/ImageAnalyzer/BattleImageAnalyzer.cpp, src/MeoAssistant/ImageAnalyzer/DepotImageAnalyzer.cpp, src/MeoAssistant/ImageAnalyzer/General/OcrImageAnalyzer.cpp, src/MeoAssistant/ImageAnalyzer/General/OcrImageAnalyzer.h, src/MeoAssistant/ImageAnalyzer/ProcessTaskImageAnalyzer.cpp, src/MeoAssistant/ImageAnalyzer/ProcessTaskImageAnalyzer.h, src/MeoAssistant/ImageAnalyzer/RoguelikeRecruitImageAnalyzer.cpp, src/MeoAssistant/ImageAnalyzer/StageDropsImageAnalyzer.cpp, src/MeoAssistant/Task/Plugin/DrGrandetTaskPlugin.cpp, src/MeoAssistant/Task/Sub/AutoRecruitTask.cpp, src/MeoAssistant/Task/Sub/CreditShoppingTask.cpp
=> feat: 优化 isAscii、withoutDet 参数的处理

resource/custom_infrast/243_layout_3_times_pre_day.json
=> feat: Update 243_layout_3_times_pre_day.json

src/MeoAssistant/Controller.cpp, src/MeoAssistant/Controller.h
~~有一个很严重的问题是我没有 MacOS 设备测不了~~
是不是还得手动把 `3rdparty/resource/minitouch/` 加到包里面
=> feat: 尝试为 MacOS 增加 minitouch 支持

src/MeoAsstGui/Resources/Localizations/ja-jp.xaml
=>  Doc: JP Missing text add and tweak.

resource/tasks.json, src/MeoAssistant/Task/Miscellaneous/CreditFightTask.cpp
修复了借助战作战失败后会卡在“任务失败”的界面的问题
自动作战偶尔会有放人放不上去的情况
=> fix: 修复借助战作战失败后卡住的问题

docs/1.3-模拟器支持.md
原来的 `同目录` 让我一开始以为是蓝叠的目录，找了半天没发现，后来才反应过来是MAA的目录
=> 修改可能产生歧义的语句

.github/workflows/dev-build-mac.yml, .github/workflows/release-maa-mac.yml, CMakeLists.txt, cmake/macos.cmake
- 更新 CMake 文件，从依赖仓库 [maa-deps](https://github.com/hguandl/maa-deps) 自动下载预编译库。
- 更新 CI，修改 App 名称。
- 为 App 添加触控方式选项。
=> feat / macOS: 支持 FastDeploy 和 MaaTouch

src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
fix #2693 
另一种方案是再向左划一下，或点两下按心情排序。请大佬斟酌用哪种。
=> fix: 宿舍内sort和autofill同为true时的选人bug #2693

src/Python/asst.py
=>  fix pr#3086 && 添加Python环境变量设置流程

resource/global/YoStarEN/resource/tasks.json
=> 修复EN服自动基建卡在控制中心&领取任务奖励失败以及刷理智无法回到上次作战的问题

resource/global/YoStarEN/resource/tasks.json
=> 修正肉鸽DF关卡标题

docs/glossary/operators.md
=> Doc: JP Update 塵影に交わる残響

resource/global/YoStarEN/resource/tasks.json
=> 国际服更新干员和肉鸽内容拓展2

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Main/SettingsViewModel.cs, src/MaaWpfGui/Main/TaskQueueViewModel.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
想起肉鸽助战的GUI还没做，添加了  “开局干员”使用助战 、可以使用非好友助战 两个选项
还有那个pallas.xaml里面是啥（
=> feat: WpfGUI 添加肉鸽助战选项

src/MaaWpfGui/Helper/LogItemViewModel.cs, src/MaaWpfGui/Helper/UILogColor.cs, src/MaaWpfGui/Main/VersionUpdateViewModel.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml
输出至一键长草的UI Log，~~就不用管如何设计进度条了（但糊得更乱了）~~
close #3271 #2990 #2799
=> feat: 显示后台下载进度

src/MaaWpfGui/Helper/StageManager.cs, src/MaaWpfGui/Helper/WebService.cs, src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/Main/SettingsViewModel.cs, src/MaaWpfGui/Main/VersionUpdateViewModel.cs
土法子真好用.jpg
[Repo](https://github.com/MaaAssistantArknights/MaaRelease/tree/main/MaaAssistantArknights/api), [API](https://ota.maa.plus/MaaAssistantArknights/api/) 
学姐带带（
=> feat: 从 web 获取部分 UI 所需信息

src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
=> 修复肉鸽助战翻页后不识别的问题

docs/2.1-Linux编译教程.md, docs/en-us/2.1-LINUX_TUTORIAL.md
写了简体中文和英文的, 其他语言怎么搞, ~~deepL 吗~~
=> docs: 更新 Linux 平台编译教程

3rdparty/include/Arknights-Tile-Pos/TileCalc.hpp, src/MaaCore/Config/Miscellaneous/TilePack.cpp, src/MaaCore/Config/Miscellaneous/TilePack.h, src/MaaCore/Task/BattleHelper.cpp, src/MaaCore/Task/BattleHelper.h
还没研究过引航者试炼, 有大佬帮忙测一下吗, 我感觉什么地方会差个负号
=> feat: 更新摄像机移动方法

src/MaaWpfGui/Helper/MessageBoxManager.cs, src/MaaWpfGui/Helper/WindowManager.cs, src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Main/RootViewModel.cs, src/MaaWpfGui/Main/SettingsViewModel.cs
同步更改后自动关闭了，继承自：#3412
close #3270 #2980
=> feat: 记住主界面的位置和大小

resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp, src/MaaCore/Vision/Roguelike/RoguelikeRecruitSupportAnalyzer.cpp
#3375 
调整肉鸽助战刷新次数，从3调整为5
修正了助战页面干员识别 Log.info 传参错误
=> 调整肉鸽助战刷新次数

resource/custom_infrast/243_layout_4_times_a_day.json
修复两个问题：1，文字错误，两个A+B班的文本写成了16H，应为8H；
2，肥鸭应该每8h用一次，原排班有一次时间排错了。把原排班在A+C组时候使用一次肥鸭调整到了在B+C组的时候使用。
=> 243一天4换排班错误修复

src/Python/asst.py, src/Python/sample.py
土制的MAA更新器
Nightly部分因为最近没有Nightly版本，所以无法进行测试
在本地进行了非常有限的测试，不敢保证没有bug，也没有做太多的异常处理
由于有数位其他大师愿意进行优化，我就不再班门弄斧了
=> feat: Python接口的MAA更新器

resource/tasks.json
=> feat: 统一资源本和芯片本进入方式为ocr以支持外服

resource/tasks.json
我对任务流程协议看完文档还是一知半解，尝试修改了一下自测正常，请审阅
=> 仓库识别任务前先返回到首页再开始，增强任务启动时的可靠性

docs/2.3-IssueBot使用方法.md
=> doc: 修正文档错误引用

src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
=> fix: all_melee_retreat 在使用迭代器遍历的同时删除元素导致segmentation fault

src/MaaCore/Task/Infrast/InfrastProductionTask.cpp
`Analyzer` 应该先加载图片再设置task info
=> fix: `Analyzer` should constructor with image and then set task info

resource/tasks.json
=> fix: 生息演算 关卡导航

src/MaaWpfGui/Main/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/FightSettingsUserControl.xaml, src/MaaWpfGui/Views/UserControl/FightSettingsUserControl.xaml.cs
=> feat: 实时更新战斗设置

src/MaaWpfGui/Res/Localizations/ja-jp.xaml
いくらか抜けていた部分や翻訳抜けを修正。
Some omissions and missing translations were corrected.
=> doc : Config JP text translate

src/MaaCore/Config/Miscellaneous/TilePack.cpp
一个超级 overkill 的修改, 在性能不好的 Linux 系统下能减少 10-20% 的耗时, Windows 系统下有文件缓存的情况下能减少 30-40%, 但是对耗时最长的第一次加载没啥作用 (可能瓶颈在硬盘)
=> perf: read tile data concurrently

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Views/VersionUpdateView.xaml
=> feat: localization of VersionUpdateView

src/MaaCore/Task/Infrast/InfrastDormTask.cpp
=> fix: #3816

.github/workflows/release-nightly-ota.yml, .github/workflows/release-ota.yml, src/MaaWpfGui/Main/VersionUpdateViewModel.cs
=> fix: 修复 WpfGui 自动更新时 x64 也下载 arm64 的 ota 的问题

docs/glossary/operators.md
Add JP 翠玉の夢 / Chinese Up to the current event
=> Doc : Update JP 翠玉の夢 and add Operators

src/MaaWpfGui/Helper/WebService.cs, src/MaaWpfGui/Main/CopilotViewModel.cs
Add HttpClient and basic request functions to WebService, and apply them to copilot fetching
=> perf: First step to async web service

resource/global/YoStarEN/resource/tasks.json
=> 添加一些EN服务器翻译

.github/workflows/ci.yml, CHANGELOG.md, resource/tasks.json, src/MaaWpfGui/Main/RootViewModel.cs, src/MaaWpfGui/Main/SettingsViewModel.cs, src/MaaWpfGui/Main/VersionUpdateViewModel.cs
=> Release v4.12.2

.github/workflows/ci.yml, .github/workflows/release-ota.yml
- macOS 上的 MaaCore 采用 matrix 并行编译 arm64 和 x86_64，加快构建速度。
- 为 macOS 版 MAA 添加自动更新功能。
- 添加 macOS 的 OTA 上传 workflow。
=> chore: Support macOS OTA

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Main/SettingsViewModel.cs, src/MaaWpfGui/Main/TaskQueueViewModel.cs
fix #4014
~~等个有缘人优化下_taskQueueViewModel的显示和点击停止按钮取消等待~~
=> feat: 在模拟器启动期间可取消任务

src/MaaWpfGui/Helper/WebService.cs, src/MaaWpfGui/Main/CopilotViewModel.cs
Reverts MaaAssistantArknights/MaaAssistantArknights#4065
=> Revert "feat: 增加json请求超时限制"

src/MaaWpfGui/Helper/WindowManager.cs, src/MaaWpfGui/Services/Web/HttpService.cs
=> fix: proxy default protocol / start location

src/MaaWpfGui/Services/StageManager.cs, src/MaaWpfGui/Services/Web/HttpService.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
=> fix: deadlock in UI thread

docs/glossary/operators.md
=> Doc : Update 夕景に影ありて + また会えたね (JP)

resource/roguelike/recruitment.json
=> fix: 修复傀影肉鸽开局招募闪退问题

resource/tasks.json
=> fix: 修复收藏品二选一卡死问题

src/MaaWpfGui/Helper/ToastNotification.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/ViewModels/UI/DepotViewModel.cs, src/MaaWpfGui/ViewModels/UI/RecruitViewModel.cs, src/MaaWpfGui/ViewModels/UI/RootViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
=> fix: 再次尝试修复 UI 线程死锁

README.md
=> doc: 同步官网修改

src/MaaWpfGui/App.xaml.cs, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/GUISettingsUserControl.xaml
=> Add auto dark mode

tools/ResourceUpdater/main.cpp
=> fix: 过滤中坚信物

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Helper/MessageBoxHelper.cs, src/MaaWpfGui/Helper/WindowManager.cs, src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/RootViewModel.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/StartSettingsUserControl.xaml
=> feat: 启动MAA后直接最小化 & fix: 修复MAA主窗口最小化后弹窗位置错误

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
=> fix: 修复DarkMode跟随系统时的颜色错误

resource/tasks.json, src/MaaCore/Task/Fight/StageDropsTaskPlugin.cpp
=> fix: 修复12章活动期间需要确认两次 & StartButton2偶尔点不上

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
=> fix: 修复UI Theme跟随应用模式后的非预期同步

resource/roguelike/copilot.json, resource/roguelike/recruitment.json
1. 修复无法正确识别关卡“命运的宠儿”的问题；
2. 修复无法正确部署鸿雪“打字机”的问题；
3. 更新了肉鸽新增地图
=> fix: 肉鸽骑士结局无法自动作战（Issue #4320），更新了新地图

resource/copilot/SSS_约翰老妈新建地块.json
=> perf: 更新内置保全作业JSON

docs/glossary/operators.md
=> Doc : JP Update EPISODE11「淬火煙塵」

docs/glossary/items.md
=> Doc : Add EPISODE11 Depot

src/MaaCore/Config/Miscellaneous/AvatarCacheManager.cpp, src/MaaCore/Config/Miscellaneous/AvatarCacheManager.h, src/MaaCore/Config/Miscellaneous/OcrPack.cpp, src/MaaCore/Config/Miscellaneous/StageDropsConfig.cpp, src/MaaCore/Config/ResourceLoader.cpp, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Services/StageManager.cs
```log
asst::ResourceLoader::load | leave, 36 ms
```
=> perf: 更多的惰性加载！

resource/copilot/SSS_约翰老妈在建地块_浊蒂水陈版.json
=> chore: 保全派驻 新增_约翰老妈在建地块_浊蒂水陈版

docs/1.4-Mac模拟器支持.md
添加最小化 playcover 安装的游戏窗口时 maa 无法正常工作问题的说明
=> docs: Update 1.4-Mac模拟器支持.md

docs/2.2-开发相关.md
不会只有我第一次没找到这个 maadeps-download.py 文件吧，不会吧。😅
=> docs: 文档补充 maadeps-download.py 位置

docs/3.3-战斗流程协议.md
=> docs: 修正战斗流程协议链接

src/MaaWpfGui/Helper/ApplicationExtensions.cs, src/MaaWpfGui/Helper/LocalizationHelper.cs, src/MaaWpfGui/Helper/MessageBoxHelper.cs, src/MaaWpfGui/Helper/WindowHandle.cs, src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Services/Managers/IMainWindowManager.cs, src/MaaWpfGui/Services/Managers/MainWindowManager.cs, src/MaaWpfGui/Services/TrayIcon.cs, src/MaaWpfGui/ViewModels/UI/RootViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UI/RootView.xaml, src/MaaWpfGui/Views/UI/VersionUpdateView.xaml, src/MaaWpfGui/app.manifest
=> chore: UI improvements

docs/glossary/operators.md
Add JP name Operator IL SIRACUSANO
=> Doc : JP シラクザーノ

src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
=> 肉鸽中不再进阶未精二的干员

docs/1.2-常见问题.md
=> docs: 对蓝叠模拟器Hyper-V的补充说明(#4806)

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
Translations update from [MAA Weblate](https://weblate.maa-org.net) for [MaaAssistantArknights/MAA WPF Gui](https://weblate.maa-org.net/projects/maa-assistant-arknights/maa-wpf-gui/).
Current translation status:
=> i18n: Translations update from MAA Weblate

docs/1.5-Linux模拟器支持.md
=> docs: typo & code block

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
=> 将运行完成后选项中不便理解的*修改为更易懂的文本

docs/maa_tasks_schema_en.json
Lazily machine translated maa_tasks_schema.json from CN to EN just to have a little help in the tasks.json
=> Translated json schema for tasks.json

src/MaaWpfGui/Res/Localizations/en-us.xaml
Changed "Addiction Command arguments" to "Additional command arguments"
=> Typo on en-us.xaml

src/MaaCore/Assistant.cpp, src/MaaCore/Assistant.h, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/TimerSettingsUserControl.xaml
=> feat: 定时任务强制启动

resource/config.json, src/MaaCore/Config/GeneralConfig.cpp, src/MaaCore/Config/GeneralConfig.h, src/MaaCore/Task/AbstractTask.cpp, src/MaaCore/Task/AbstractTask.h
=> feat: 肉鸽debug日志写入图片前限制文件夹内图片数量

resource/roguelike/shopping.json
=> feat: 初步完成对诡异行商商品的标记

resource/roguelike/stage_encounter.json
更新不期而遇选项与默认选项，其中部分选项数量可能发生变化，可能需要更新点击逻辑
=> Stage encounter update

resource/roguelike/stage_encounter.json
#5416 的跟进
choice_require：
|       key         |      意思        |
| -------------- | ------------ |
| ChaosLevel     | 坍缩等级     |
| LivePoint      | 目标生命     |
| LivePointCap   | 目标生命上限 |
| OriginiumIngot | 源石锭       |
| Relic          | 收藏品       |
| Vision         | 抗干扰指数   |
命名均来自于 Gamedata 或是 Arknights Fandom
=> 扩充不期而遇选项标记

src/Python/downloader.py
尝试使用某种歪门邪道的下载方式，目前效果还行，可以规避那些速度极慢或者连接不上的下载渠道。缺点就是请求数和流量消耗更高。
file_download(urlist=[url1, url2, url3], filepath=filepath)
非必要参数 proxies 代理地址
=> 同时请求多个url下载

include/AsstCaller.h
=> refactor: fix typo in AsstCaller.h

resource/roguelike/copilot.json
=> 增加萨米肉鸽战斗关卡作业

resource/roguelike/copilot.json
合并萨米肉鸽中相同关卡的自动战斗逻辑
#5430 #5433
=> 合并萨米肉鸽中相同关卡的自动战斗逻辑

resource/roguelike/recruitment.json
=> Fix 絮雨在肉鸽中想使用3技能的bug

.github/workflows/gen-changelog.yml, .github/workflows/pr-auto-tag.yml, .github/workflows/release-nightly-ota.yml, .github/workflows/release-ota.yml, .github/workflows/smoke-testing.yml
=> ci: 规范化step name

src/MaaCore/Common/AsstConf.h
See https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5509
=> AsstConf.h 对 clang-tidy 不友好的问题

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
=> fix: 0时的定时任务无法提前重启

docs/glossary/operators.md
=> JP : add Operators 登臨意

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Views/UI/RecognizerView.xaml
第一个 commit 实现了基本的彩虹色和阴影效果
第二个 commit 实现了变色效果
如果需要的话我还可以再加特效 ~~太创人了（~~
=> feat: 给牛牛抽卡提示增加阴间特效

.github/workflows/qodana.yml, qodana.yaml, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
=> Ci: qodana

src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
无聊时发现 MAA 更新突然出现毛病，检查代码发现一个逻辑小错误
=> fix: 更新的逻辑小错误

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
=> feat:自动检测特定目录下的bluestacks.conf

resource/roguelike/copilot.json
=> feat：适配萨米肉鸽关卡“豪华车队”

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
revert #5751
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/5751#issuecomment-1663210410 可能需要一个更好的解决方法
=> Revert "feat:自动检测特定目录下的bluestacks.conf"

.github/workflows/qodana.yml
在之前的 MR 中，MR流程没有配置基线。
在这个MR 中，暂时以 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/4e15ae3077b95d7f97538e6d5d464eef3ea8b9a0
这个Commit作为了基线
=> CI-在静态分析中增加基线

.gitignore, docs/.gitignore, docs/.vuepress/config.ts, docs/.vuepress/plugins/search.ts, docs/.vuepress/plugins/sitemap.ts, docs/package-lock.json, docs/package.json, docs/tsconfig.json
[DocSearch](https://v2.vuepress.vuejs.org/zh/reference/plugin/docsearch.html) 配合 [Sitemap](https://plugin-sitemap2.vuejs.press/zh/) 可以为用户提供更加良好的文档内容搜索体验
搜索插件的繁中/日文/韩文部分需要翻译跟进
合的时候要不要squash你们定（
=> feat(docs): 为文档添加docsearch和sitemap支持

resource/roguelike/Sami/encounter.json
=> feat: 萨米不再进入三个不期而遇战斗

resource/global/YoStarJP/resource/tasks.json
=> fix: add ocr replace for YostarJP

src/Golang/conf/config.go
=> perf(Golang): 从io/ioutil包更新为os包

docs/3.1-集成文档.md, docs/en-us/3.1-INTEGRATION.md, docs/ja-jp/3.1-統合ドキュメント.md, docs/zh-tw/3.1-集成文件.md
=> Update(docs): 3.1-Integration.md

resource/tasks.json, src/MaaCore/MaaCore.vcxproj, src/MaaCore/MaaCore.vcxproj.filters, src/MaaCore/Task/Fight/SanityBeforeStagePlugin.cpp, src/MaaCore/Task/Fight/SanityBeforeStagePlugin.h, src/MaaCore/Task/Interface/FightTask.cpp, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> feat: 增加刷理智每次打关卡之前时的理智剩余量输出

README.md, src/Woolang/.gitignore, src/Woolang/README.md, src/Woolang/demo.wo, src/Woolang/maa.wo, src/Woolang/package.json
利用woffi，包装了一下MAA的C-API，使用起来基本和C-API一致
（估计没有人用，逃）
=> feat: 支持woolang绑定

docs/1.2-常见问题.md, docs/1.3-模拟器支持.md
=> docs: 跟进蓝叠Hyper-V的连接指导 (#6083)

src/MaaCore/Config/Miscellaneous/TilePack.cpp, src/MaaCore/Config/ResourceLoader.cpp, src/MaaWpfGui/Main/AsstProxy.cs
=> Release v4.23.2

src/MaaCore/Config/ResourceLoader.cpp
=> Release v4.23.3

docs/3.1-集成文档.md, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, tools/AutoLocalization/example/en-us_force.xaml, tools/AutoLocalization/example/zh-cn.xaml, tools/AutoLocalization/example/zh-cn_new.xaml
=> 尽可能稳定的打更多层数 -> 尽可能稳定地打更多层数

resource/tasks.json
=> fix: 尝试修复网络波动造成的碎石不用问题

.github/workflows/res-update-game.yml, src/MaaWpfGui/Helper/ETagCache.cs, src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Models/ResourceUpdater.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Services/Web/HttpService.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs, tools/ResourceUpdater/main.cpp
=> feat: update local resource by etag

src/MaaCore/Config/Miscellaneous/StageDropsConfig.h, src/MaaCore/Task/Fight/StageDropsTaskPlugin.cpp, src/MaaCore/Task/Fight/StageDropsTaskPlugin.h
link to #5837 #6306 
(not fix)
=> feat: 增加未通过企鹅检查的掉落截图，增加 UnknownStage 时的难度回调

src/MaaWpfGui/Views/UI/CopilotView.xaml
=> perf: 优化自动战斗-自动编队-追加自定干员选项UI，当选项禁用时，居中CheckBox

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
Translations update from [MAA Weblate](https://weblate.maa-org.net) for [MaaAssistantArknights/MAA WPF Gui](https://weblate.maa-org.net/projects/maa-assistant-arknights/maa-wpf-gui/).
Current translation status:
=> [skip ci] i18n: Translations update from MAA Weblate

resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarJP/resource/tasks.json
顺便修复了美服生息演算的配置上的小问题
注:仅仅测试了稳定性
另一位贡献者:@Manicsteiner
=> feat: 添加日服生息演算翻译

resource/tasks.json, src/MaaCore/Task/Miscellaneous/AccountSwitchTask.cpp, src/MaaCore/Task/Miscellaneous/AccountSwitchTask.h
=> fix: 将账号切换输出文本中的目标账号由输入文本改为OCR结果，尝试修复账号切换出错

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Services/Notification/ExternalNotificationService.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
=> fix: 修复外部通知错误

src/MaaCore/Assistant.cpp, src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp
=> fix: 修复Status缓存跨任务清理在任务链正常完成情况下失效的错误

resource/roguelike/Sami/autopilot/公司纠葛.json, resource/roguelike/Sami/autopilot/生人勿近.json, resource/tasks.json
=> feat: 适配高规格分队开局

src/MaaCore/Task/Roguelike/RoguelikeControlTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeControlTaskPlugin.h
=> feat: 投资达到上限后退出到肉鸽主界面

qodana.yaml
参考：https://youtrack.jetbrains.com/issue/QD-7060/Please-reconsider-qodana-cloud-requirement
对目前主分支上出现的跨仓库 Pull-Request 场合 Qodana 分析错误的问题进行修正。
在这个 Issue 中提到，对于跨仓库 Pull-Request 的 QODANA-TOKEN 问题，可以通过使用不需要这个 Token 的 EAP 版本来解决。
=> 更新qodana配置

src/Python/sample.py
=> chore: 在Python脚本中添加活动关导航下载与加载的示例 (#3916)

src/MaaWpfGui/Main/AsstProxy.cs
=> fix: 修复 理智获取数据格式错误 导致的崩溃

src/MaaCore/Assistant.cpp, src/MaaCore/Task/Fight/SanityBeforeStagePlugin.cpp, src/MaaCore/Task/Fight/SanityBeforeStagePlugin.h, src/MaaWpfGui/Main/AsstProxy.cs
=> fix: 修改理智数据格式

docs/3.1-集成文档.md, docs/zh-tw/3.1-集成文件.md, src/MaaCore/Task/Interface/CopilotTask.cpp, src/MaaCore/Task/Miscellaneous/BattleProcessTask.cpp, src/MaaCore/Task/Miscellaneous/BattleProcessTask.h, src/MaaWpfGui/Views/UI/CopilotView.xaml
=> fix: 自动战斗-战斗列表启用时，对所有作业追加摆完挂机选项操作

src/MaaCore/Assistant.cpp, src/MaaCore/Status.h, src/MaaCore/Task/Fight/SanityBeforeStagePlugin.cpp, src/MaaWpfGui/Helper/Instances.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
=> perf: Core不再缓存理智结果，Gui缓存理智读取结果，刷理智合并理智输出和战斗次数输出

docs/1.3-模拟器支持.md
#6570 
有时间还得把hyperv这段拆一下 感觉太长了
以及 那个随机排序 真的有必要吗 旁边mac和linux文档也没有
vscode的markdown语法检测和预览都摆烂了 全靠脑测
=> doc: 补充 Hyper-V 说明

src/MaaCore/Task/Fight/SanityBeforeStagePlugin.cpp, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
- close #6550 
revert some changes in b2f9f25
=> fix: 修复自动战斗-战斗列表拖拽导致崩溃

resource/tasks.json, src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Roguelike/RoguelikeShoppingTaskPlugin.cpp
=> perf: 优化 刷源石锭模式是否进入第二层 的实现方式

resource/tasks.json
用插件在LevelName任务触发修改Stages的next?
=> feat: 增加不同层数的stages策略

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
- close #6567 
1. 自动战斗-战斗列表结束时
2. 自动战斗发生错误时
=> fix: 修复任务链结束后操作会在错误情况下被触发的错误

src/MaaWpfGui/Main/AsstProxy.cs
=> fix: 修复连接错误

docs/3.4-任务流程协议.md, resource/global/YoStarKR/resource/tasks.json, resource/tasks.json, src/MaaCore/Config/TaskData.cpp, src/MaaCore/Config/TaskData.h, src/MaaCore/Task/Interface/RoguelikeTask.cpp
这个 PR 也包含了一些其它肉鸽相关的修改
例子：[refactor: 使用新特性修改 LevelName 相关代码](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/693bcf361d44620e67ed84568a9faa3a06afced1)
- `tasks.json`:
```json
"A": {
"baseTask": "A_default"
},
"A_default": {
"next": [ "xxx" ]
},
"A_mode1": {
"next": [ "yyy" ]
},
"A_mode2": {
"next": [ "zzz" ]
}
```
- 代码：
```cpp
Task.set_task_base("A", "A_mode1");
```
更加复杂的更改可以通过 `Task.lazy_parse()` 实现。
=> feat: 运行期修改任务内容

resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
=> fix: 修复肉鸽助战招募卡住放弃的问题

src/MaaWpfGui/FodyWeavers.xml, src/MaaWpfGui/MaaWpfGui.csproj
将 FodyWeavers 配置移到了 csproj 中来启用条件判断
=> fix: 修复Costura未正常启用的问题

src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
=> fix: 修复肉鸽自动撤退字段引发闪退的问题

resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarKR/resource/tasks.json, resource/global/txwy/resource/tasks.json, resource/tasks.json, src/MaaCore/MaaCore.vcxproj, src/MaaCore/MaaCore.vcxproj.filters, src/MaaCore/Status.h, src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Interface/RoguelikeTask.h, src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeLastRewardTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeLastRewardTaskPlugin.h, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStrategyChangeTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStrategyChangeTaskPlugin.h
例子：[refactor: 使用新特性修改 LevelName 相关代码](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6508/commits/5b3400035b748b7a07d132ada636d1df0a26bc00)
- `tasks.json`:
```json
"A": {
"baseTask": "A_default"
},
"A_default": {
"next": [ "xxx" ]
},
"A_mode1": {
"next": [ "yyy" ]
},
"A_mode2": {
"next": [ "zzz" ]
}
```
- 代码：
```cpp
Task.set_task_base("A", "A_mode1");
```
更加复杂的更改可以通过 `Task.lazy_parse()` 实现。
示范：[test: 肉鸽分辨层数](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6508/commits/5137973a8491e33e392adcd1ac3dc2c3e6f8e194)
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6508#issuecomment-1732475627
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6508#issuecomment-1732476270 …
=> feat: 肉鸽不同层数逻辑

src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
=> fix: 修复错误条件下UI显示"投资后进入第二层"按钮的问题

docs/.vuepress/sidebar/zh-cn.ts, docs/.vuepress/styles/palette.scss, docs/2.6-文档编写指南.md, docs/ja-jp/readme.md
+ 初步添加文档编写指南
+ 多语言字体配置
+ 加大文档的显示区域
=> docs: 优化文档视觉效果，添加文档编写指南

src/MaaWpfGui/Main/AsstProxy.cs
=> fix: 修复CloseDown任务导致的不执行完成后操作

src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6659#issuecomment-1743606118
=> perf: 对DEBUG VERSION禁用版本更新及资源更新检查

src/MaaCore/Config/TaskData.cpp
参考了一点 fw 的 pipeline
https://github.com/MaaAssistantArknights/MaaFramework/blob/c572948bd40a90899354b10257e4ad7b92d3c021/source/MaaFramework/Resource/PipelineResMgr.cpp#L152-L167
=> rft: 优化 TaskData 的 json 解析

src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/ViewModels/UI/AnnouncementViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs, src/MaaWpfGui/Views/UI/AnnouncementView.xaml, src/MaaWpfGui/Views/UI/VersionUpdateView.xaml
> [!Warning]
MdXaml的早期版本在少数人电脑上会出现渲染问题，现版本不知道是否已经修复
要合的话记得发版测试 崩溃的人多的话revert
=> feat: 使用MdXaml来提升Markdown渲染表现

src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/ViewModels/UI/AnnouncementViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs, src/MaaWpfGui/Views/UI/AnnouncementView.xaml, src/MaaWpfGui/Views/UI/VersionUpdateView.xaml
Reverts MaaAssistantArknights/MaaAssistantArknights#6723
=> Revert "feat: 使用MdXaml来提升Markdown渲染表现"

src/MaaWpfGui/Configuration/ConfigFactory.cs, src/MaaWpfGui/Configuration/GUI.cs, src/MaaWpfGui/Configuration/SpecificConfig.cs
link #6752 
link #6776 
caused by https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/42e9542cd1914193f49afdd6435c2b1a8b6eef22#diff-8f68e6988b089efca72b7954862a47442ec7eb08b37bde5a0c0f072cf4488dd3L9
无语，睡觉去了
=> Fix #6752 & Fix #6776

src/MaaWpfGui/Main/AsstProxy.cs
=> perf: WpfGui关卡掉落输出增加千分位分隔符

docs/3.2-回调消息协议.md, docs/en-us/3.2-CALLBACK_SCHEMA.md, docs/ja-jp/3.2-コールバックAPI.md, docs/ko-kr/3.2-콜백_스키마.md, docs/zh-tw/3.2-回呼訊息協議.md, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
fix #6732 
还没测试（因为没有要过期的药了
只是简单的单独列出来使用快过期的药，并没有和原来的合并在一起 ~~(我不会~~
看看怎么改更好罢
=> feat: 输出“使用 48 小时内过期的理智药”消息

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> style: 更正变量名

src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> fix: zh-tw 变量名错误

src/MaaCore/Config/Miscellaneous/OcrConfig.h, src/MaaCore/Vision/Config/OCRerConfig.cpp, src/MaaCore/Vision/Config/OCRerConfig.h, src/MaaCore/Vision/OCRer.cpp, src/MaaCore/Vision/OCRer.h
=> fix: 修复因 ocr_replace 与 m_eq_classes 冲突导致的 ocr 识别失效的问题

src/MaaWpfGui/Helper/Instances.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
中文输出理智、药、石头3个都在的时候应该能一行装下，其他语言随他吧
=> feat: WpfGui 刷理智开始行动输出新增 每次开始行动时输出理智药和碎石次数（不记录临期药品使用次数）

src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
=> fix: 修复WpfGui肉鸽 等待&停止 重复调用AsstStop的错误

resource/tasks.json, tools/CropRoi/main.py, tools/GetImageFromROI/main.py, tools/GetImageFromROI/requirements.txt, tools/GetImageFromROI/start.bat
=> feat: 用于快速适配新页面主题的小工具

resource/custom_infrast/243_layout_4_times_a_day.json
=> feat: 更新内置243一天四换极限效率

src/MaaCore/Assistant.cpp, src/MaaCore/Common/AsstTypes.h, src/MaaCore/Config/Miscellaneous/OcrPack.cpp, src/MaaCore/Config/Miscellaneous/OcrPack.h
https://github.com/MaaAssistantArknights/FastDeploy/pull/4
=> feat: support GPU OCR

resource/tasks.json, src/MaaCore/Task/Miscellaneous/AccountSwitchTask.cpp
=> fix: 修复账号切换时可能卡在选择账号之后的错误

3rdparty/include/meojson/bitops.hpp, 3rdparty/include/meojson/json.hpp, 3rdparty/include/meojson/packed_bytes.hpp, 3rdparty/include/meojson/packed_bytes_arm.hpp, 3rdparty/include/meojson/packed_bytes_x86.hpp
=> feat: update meojson to v3.1.1

resource/global/txwy/resource/tasks.json
fix #6952
招募好友的某些干员的时候ocr会识别错误
tested on local
=> fix:台服肉鸽模式无法招募某些好友干员

tools/ChangelogGenerator/changelog_generator.py
=> refactor: 重构 changelog_generator.py 部分内容

resource/tasks.json, src/MaaCore/Task/BattleHelper.cpp
凭感觉写的，晚上再测测
fix #6803
close #6929
=> fix: 修复干员头像保存错误

src/MaaWpfGui/Helper/Instances.cs, src/MaaWpfGui/Main/AsstProxy.cs
=> perf: 修改刷理智每次开始战斗时输出：不再显示理智药、碎石的设定上限值，增加临期理智药使用次数

resource/global/YoStarEN/resource/tasks.json, resource/tasks.json, src/MaaCore/MaaCore.vcxproj, src/MaaCore/MaaCore.vcxproj.filters, src/MaaCore/Task/AbstractTask.h, src/MaaCore/Task/Infrast/InfrastAbstractTask.h, src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Interface/RoguelikeTask.h, src/MaaCore/Task/Miscellaneous/BattleFormationTask.h, src/MaaCore/Task/Miscellaneous/ScreenshotTaskPlugin.cpp, src/MaaCore/Task/Miscellaneous/ScreenshotTaskPlugin.h
link to #6966 
link to #6975 (this PR is not a fix for it, but to add debug screenshots for similar issues)
这个插件可以被用在任意 Task，现在只有 RoguelikeTask 注册了
=> feat: 增加任务截图插件

resource/tasks.json, src/MaaCore/Config/TaskData.cpp, src/MaaCore/Config/TaskData.h, src/MaaCore/MaaCore.vcxproj, src/MaaCore/MaaCore.vcxproj.filters, src/MaaCore/Utils/JsonMisc.hpp
1. 调整 TaskData 的部分内部函数，增加注释
2. 从 TaskData 中拆出 JsonMisc
3. 增加一个任务 MainThemes，表示任务链入口
=> perf: TaskData 优化

src/MaaWpfGui/Helper/ConfigurationHelper.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
=> fix: fix some warnings from visual studio

src/MaaCore/Task/Interface/RecruitTask.cpp, src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp, src/MaaCore/Task/Miscellaneous/AutoRecruitTask.h, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/AutoRecruitSettingsUserControl.xaml
fix #92, fix #3819
这个应该不用做成选项罢 ~~（真的有人在乎那140龙门币吗~~
=> feat: 公招出高星干员时选中多个tag

docs/en-us/1.6-USER_GUIDE_FOR_CLI.md
=> docs: fix code block in user guide  for CLI

src/MaaWpfGui/Services/StageManager.cs
这玩意看上去重要程度最低，先干掉这个（比划
- link to #6666
=> perf: 优化Wpf关卡数据更新提示，改为Growl.Info

resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> feat: 肉鸽增加不期而遇事件名输出

.github/workflows/ci.yml
https://github.com/AppImage/appimage.github.io/pull/3270#issuecomment-1783756048
=> 在 AppImage 中添加 `Terminal=true`

resource/global/txwy/resource/tasks.json
有時只會訪問一人
Fix #6041 , Fix #7013 , Fix #7107
=> 繁中服 訪問好友修正

resource/roguelike/Mizuki/recruitment.json, resource/roguelike/Phantom/recruitment.json, resource/roguelike/Sami/recruitment.json
=> perf: 肉鸽适配新干员默认技能

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> fix: 移除游戏资源更新中提示信息的`请勿关闭MAA`说明

src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
This looks ugly.
These two should be the only string references (I hope)
EDIT: technically to make this consistent, this would need a complete i18n localization maybe using Res/Localization, but I'm lazy
=> feat: Furniture Drop localization

resource/tasks.json
fix #7175
fix #7226
This should do the trick.
=> fix: Missing Text OCR when Limited + Expire monthly

docs/glossary/operators.md
=> Update JP/LONETRAIL 孤星

resource/tasks.json, src/MaaCore/Task/Fight/MedicineCounterPlugin.cpp
=> fix: 修复吃理智药在网络波动时可能产生重复使用的错误

.devcontainer/devcontainer.json, docs/2.2-开发相关.md, docs/en-us/2.2-DEVELOPMENT.md, docs/ja-jp/2.2-プルリクエスト.md, docs/ko-kr/2.2-개발_환경_구축하기.md, docs/zh-tw/2.2-開發相關.md
平时不怎么使用 vscode, MAA 编辑 json 是应该用哪个 vscode 插件 :thinking:
=> chore: 增加 devcontainer 配置文件用于创建 GitHub codespace

src/MaaCore/Status.h, src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp, src/MaaCore/Task/Roguelike/RoguelikeConfig.h, src/MaaCore/Task/Roguelike/RoguelikeCustomStartTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeFoldartalGainTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeFoldartalUseTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeLastRewardTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeShoppingTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeSkillSelectionTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStrategyChangeTaskPlugin.cpp
=> refactor: 迁移肉鸽部分数据

.github/workflows/res-update-game.yml, tools/ResourceUpdater/main.cpp
@tsuk1ko This is the implementation of the repository, 
~but I noticed that not all files are update, for instance (the most important) [character_table.json](https://github.com/arkntools/arknights-toolbox-update/blob/data/tw/excel/character_table.json) does not have the new operators (From Ines --> today)~
I'm a dumbass, dont' mind me. I forgot txwy is in "the past" hence, doesn't have access to these operators yet.
=> feat: txwy resource updater

src/MaaCore/MaaCore.vcxproj.filters
=> fix: 移动cpp文件的位置

resource/tasks.json, src/MaaCore/Task/Interface/CopilotTask.cpp, src/MaaCore/Task/Interface/CopilotTask.h, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Styles/MdXaml.xaml, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/Views/UI/CopilotView.xaml
=> feat: 自动战斗-战斗列表新增无限吃理智药选项

src/MaaCore/Task/Interface/RoguelikeTask.cpp
fix #7267
重构肉鸽 `set_params` 相关内容
- [fix: 修复肉鸽修改参数后不生效的问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7289/commits/6713f8b34c0190cc275517abd5f52ca82d70b396)：部分参数在 ”修改前不是默认值，修改后是默认值” 时不生效
fix #7267
=> fix: 修复肉鸽修改参数后不生效的问题

src/MaaWpfGui/Models/ResourceUpdater.cs, src/MaaWpfGui/ViewModels/UI/AnnouncementViewModel.cs
Enhanced Resource Retrieval with 'using' and Retry
fix #7261
fix #7321
=> fix: 游戏资源下载失败

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
=> fix: 修复使用临期理智药设置无法在任务中修改的错误

resource/Arknights-Tile-Pos/level_crisis_v2_01-01-obt-crisis-v2-level_crisis_v2_01-01.json, resource/Arknights-Tile-Pos/level_crisis_v2_01-02-obt-crisis-v2-level_crisis_v2_01-02.json, resource/Arknights-Tile-Pos/level_crisis_v2_01-03-obt-crisis-v2-level_crisis_v2_01-03.json, resource/Arknights-Tile-Pos/level_crisis_v2_01-04-obt-crisis-v2-level_crisis_v2_01-04.json, resource/Arknights-Tile-Pos/level_crisis_v2_01-05-obt-crisis-v2-level_crisis_v2_01-05.json, resource/Arknights-Tile-Pos/level_crisis_v2_01-06-obt-crisis-v2-level_crisis_v2_01-06.json, resource/Arknights-Tile-Pos/level_crisis_v2_01-07-obt-crisis-v2-level_crisis_v2_01-07.json, resource/Arknights-Tile-Pos/overview.json
=> resource: 更新新版危机合约地图

.github/workflows/res-update-game.yml, resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarJP/resource/tasks.json
ref:
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e5be6a64f76d811d7641d0c71333a83eb5c04bf6#commitcomment-133674922
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e5be6a64f76d811d7641d0c71333a83eb5c04bf6#commitcomment-133704379
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/e5be6a64f76d811d7641d0c71333a83eb5c04bf6#commitcomment-133707192
=> ci: line overwrite bypass in res-update

src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.h
我推测问题出在 team_complete_condition 里加了重复的干员，但是没日志不好判断，因此加了点日志
另外用 ranges 重构了一点
link to #7038 
fix #7379
=> fix: 修复肉鸽编队时选择干员重复点击导致未选中的问题

.github/workflows/pr-checker.yml
合并后在rule里面添加这个检查就能达成效果
- link to #7296
=> ci: 对PR提交的commit名进行检查

src/MaaCore/Controller/AdbController.cpp, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> feat: 新增检测最快截图方式后输出截图方法和截图测试耗时

.github/workflows/qodana.yml, qodana.yaml
close #7177
顺带改了下平台
等 2023.3 EAP 发布了就能重新启用 Qodana 了
=> chore: 更新 Qodana 版本到 2023.3 EAP

.github/workflows/pr-checker.yml
=> ci: PR Checker在Merge之后不再运行

.github/workflows/pr-checker.yml
Reverts MaaAssistantArknights/MaaAssistantArknights#7457
=> Revert "ci: PR Checker增加合并检查，合并后不再检查commit message"

src/MaaCore/Controller/AdbController.cpp, src/MaaCore/Controller/AdbController.h
refs:
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7473#issuecomment-1838440548
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7473#issuecomment-1838446255
=> perf: reduced screencap timeout

.github/workflows/pr-checker.yml
=> ci: 优化pr-checker的评论及日志格式，并自动删除先前的评论

.github/workflows/res-update-game.yml
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/f8169983e998ee9e5d66ad165a77b110328fe2d3
=> chore: 更新日志跳过资源更新

resource/tasks.json
=> fix(roguelike): 尝试修复肉鸽策略未随层数改变的问题

resource/tasks.json
- fix #7570
- fix #7428
- fix #6459
- fix #6275
- fix #5956
- ......
=> fix(roguelike): 尝试修复肉鸽 OptionUnknown 引起的卡住的问题

tools/ChangelogGenerator/changelog_generator.py
如题，有时候会出现同一个用户为多个 coauthor 的情况
=> chore: 更改changelog生成时检查coauthor的逻辑

resource/copilot/SSS_塔山农业实验平台_浊蒂纯艾澄闪银灰+提丰.json, resource/copilot/SSS_塔山农业实验平台_浊蒂纯艾澄闪银灰+能天使.json, resource/copilot/SSS_自走机械搏斗场_浊蒂重岳重岳星熊+塞雷娅棘刺（伪核）.json
新增三个保全脚本
[SSS_自走机械搏斗场_浊蒂重岳重岳星熊+塞雷娅棘刺（伪核）.json]
[SSS_塔山农业实验平台_浊蒂纯艾澄闪银灰+能天使.json]
[Create SSS_塔山农业实验平台_浊蒂纯艾澄闪银灰+提丰.json]
版本号已修改为4.28.2
=> feat: 新增 自走机械搏斗场、塔山农业实验平台 保全作业

resource/tasks.json
统一降低 StageEncounterOptionUnknown 的优先级
fix #7658
=> fix(roguelike): 修复肉鸽 OptionUnknown 引起的卡住的问题

resource/tasks.json, src/MaaCore/Task/ProcessTask.cpp, src/MaaCore/Task/Roguelike/RoguelikeStrategyChangeTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStrategyChangeTaskPlugin.h
=> fix(roguelike): 修复水月肉鸽策略未随层数改变的问题

resource/tasks.json
=> fix: 修复肉鸽商店投资退出过快卡在 `StageTraderInvestSystemLeave` 的问题

.github/ISSUE_TEMPLATE/cn-bug-report.yaml, .github/ISSUE_TEMPLATE/en-bug-report.yaml
=> feat: 提交 issue 时要求检查置顶议题

resource/global/YoStarEN/resource/tasks.json, resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeSettlementTaskPlugin.cpp
- close #7479
未测试EN服情况下的运行情况，而且代码看起来有优化的空间
=> fix: 修复部分情况下错误替换肉鸽结算中难度识别的文本

src/MaaCore/Task/Interface/StartUpTask.cpp, src/MaaCore/Task/Miscellaneous/AccountSwitchTask.cpp, src/MaaCore/Task/Miscellaneous/AccountSwitchTask.h
=> perf: 账号切换 取消B服客户端检测流程

resource/global/YoStarJP/resource/tasks.json
=> feat: custom ocr range detection for JP

src/MaaCore/Controller/Platform/PosixIO.cpp, src/MaaCore/Utils/Logger.hpp
~~尝试挖掘屎山~~
strace 了一下感觉 waitpid 循环太忙了, ~~加了个 epoll_wait, 应该有更好的解决方法~~
寄, MacOS 没有 epoll, 那我还是用回 select/poll 之类的吧
=> perf: update `PosixIO::call_command`

resource/copilot/SSS_自走机械搏斗场_浊蒂重岳塞雷娅泥岩_速冷
feat: 新增 自走机械搏斗场_浊蒂重岳塞雷娅泥岩_速冷 保全作业
=> feat: 新增 自走机械搏斗场_浊蒂重岳塞雷娅泥岩_速冷 保全作业

resource/copilot/SSS_自走机械搏斗场_浊蒂重岳星熊塞雷娅棘刺_音响.json
=> perf: 优化搏斗场保全音响元件脚本打法及修改脚本名称

src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.cpp
=> fix: 修复部分情况下，关卡掉落识别关卡名出错

qodana.yaml
=> chore: 更新 qodana 配置，忽略部分报错

src/MaaCore/Controller/Platform/Win32IO.cpp, src/MaaCore/Utils/Platform/PlatformWin32.cpp, src/SyncRes/SyncRes.csproj
=> fix: subprocess handle leak

src/MaaCore/Controller/AdbController.cpp, src/MaaWpfGui/Helper/Instances.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> perf: 优化截图耗时额外提示文本触发条件，改为由平均耗时触发

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
改完之后好像又和自己冲了（
目前是 `当前理智: 当前量/上限, 药: 已使用的普通药(已使用的临期药)`
要不改成:n ? ,n ? {n} ? [n] ?
=> perf: 优化刷理智-已开始战斗x次时临期理智药使用输出以增加可读性

src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
補更新繁中服生息演算最後一天的日期
龍成一開始少給十天 QQ
從 2024/01/06 改成 2024/01/16
=> chore: 更新繁中服生息演算最後一天的日期

docs/协议文档/集成文档.md, src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Roguelike/RoguelikeConfig.h, src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
close #7795
在原有的模式上进行了分离来更高效率的凹直升
~忘开新分支了~
=> feat: 增加肉鸽刷开局模式下只凹精二选项

src/MaaCore/Task/Miscellaneous/ScreenshotTaskPlugin.cpp, src/MaaCore/Task/Miscellaneous/ScreenshotTaskPlugin.h
=> feat: 减少重复截图

resource/tasks.json
=> fix: 修复肉鸽烧水选择难度可能不对的问题

docs/glossary/operators.md
YoStarKR operator added on "SO LONG ADELE"
=> docs: add korean operator name for so long adele

resource/global/YoStarKR/resource/tasks.json
remove StageEncounterOptionFree as it is no longer used
Added Mizuki@Roguelike@DataTraceback to fix screen stuck issue on DataTraceback screen.
=> chore: YoStarKR modifiy tasks.json

src/MaaWpfGui/Res/Localizations/ko-kr.xaml
fixed the translation for newly added and awkward sections
=> docs: YoStarKR translation modify

resource/global/YoStarKR/resource/tasks.json
added missing tasks and corrected some incorrect text
=> chore: YoStarKR added some missing task

docs/用户手册/CLI使用指南.md
我看有不少人想要多天排班，所以我给CLI实现了一个 `DayMod` 条件来实现多天换班。其他的改动不包含功能，所以我直接吧 commit message 写了 feat。
=> feat: CLI 支持多天排班

src/MaaWpfGui/Res/Localizations/ko-kr.xaml
=> docs: modified ko-kr.xaml

resource/tasks.json
=> fix: 修复没有赠送次数时单抽任务报错的问题

resource/config.json, src/MaaWpfGui/Helper/WinAdapter.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
https://mumu.163.com/update/win/
半年了 官网前端都改了
maa是时候删掉辣
=> chore: 移除mumu6

docs/en-us/3.1-INTEGRATION.md, docs/ja-jp/3.1-統合ドキュメント.md, docs/ko-kr/3.1-연동.md, docs/zh-tw/3.1-集成文件.md, docs/协议文档/集成文档.md, src/MaaCore/Task/Interface/ReclamationTask.cpp, src/MaaCore/Task/Interface/ReclamationTask.h, src/MaaWpfGui/Main/AsstProxy.cs
也许应该增加一个选项来选择原来的 *沙中之火* 主题? :thinking: 
@ABA2396 能帮忙改下 WPF 那边吗
=> feat: 运行 `ReclamationAlgorithm` 时默认运行 `Reclamation2` 而不是旧演算

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Helper/WindowManager.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/TextDialogWithTimerUserControl.xaml, src/MaaWpfGui/Views/UserControl/TextDialogWithTimerUserControl.xaml.cs, src/MaaWpfGui/Views/UserControl/TimerSettingsUserControl.xaml
=> feat: 强制定时启动添加提示对话框并可选是否显示窗口

src/MaaCore/Task/BattleHelper.cpp
BestMatch先识别一次上次的待部署区，没识别到再走原来的缓存识别
修改后，可见update_deployment中相较于BattleFieldMatcher，BestMatcher的占用大幅度下降
=> perf: 优化待部署区识别，减少CPU占用

src/MaaWpfGui/Main/AsstProxy.cs
=> fix: 修复自动检测失败时可能导致WpfGui崩溃

src/MaaCore/Task/Roguelike/RoguelikeInvestTaskPlugin.cpp, src/MaaWpfGui/Views/UserControl/RoguelikeSettingsUserControl.xaml
=> fix: 修复投资系统出错时，余额ocr可能出错

resource/tasks.json, src/MaaCore/Vision/Battle/BattlefieldMatcher.cpp
=> fix: 修复部分情况下待部署区干员无法正确识别为冷却中

src/MaaCore/Task/BattleHelper.cpp
=> perf: 如果待部署区未识别干员全部为冷却中，则跳过暂停识别

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Res/Styles/MdXaml.xaml, src/MaaWpfGui/ViewModels/CopilotItemViewModel.cs, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/Views/UI/CopilotView.xaml
`(突袭)` for chinese
`(Raid)` for other languages
=> fix: 自动战斗-战斗列表的突袭关描述从`Adverse`修正为`Raid`

resource/tasks.json, src/MaaCore/Vision/Battle/BattlefieldMatcher.cpp
=> fix: 修复部分角色冷却识别错误

resource/tasks.json
=> fix: 修复未识别到幸运墙时报错的问题

resource/config.json
=> chore: 增加连接配置项 CompatPOSIXShellWithoutScreencapErr

resource/roguelike/Sami/encounter.json, resource/tasks.json, src/MaaCore/Config/Roguelike/RoguelikeStageEncounterConfig.cpp, src/MaaCore/Config/Roguelike/RoguelikeStageEncounterConfig.h, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.h
- fix #5442 
- fix #7789 
- fix #7800 
- fix #7900 
- fix #7938
- fix #7943
=> feat: 支持肉鸽事件choice_require解析

src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
=> perf: 结束后动作`仅一次`在执行后不恢复为`无动作`，而是上一次的选择项

docs/glossary/operators.md
=> chore: update operator.md

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
=> refactor: 调整SettingsViewModel的init

resource/roguelike/Phantom/encounter.json
=> fix: 傀影肉鸽选项造成的卡死

resource/global/txwy/resource/tasks.json
fix #8502 
跟著 #8502 下面 @Manicsteiner 大佬提供的方法就可以正常刷理智了
感謝 ❤️
=> chore: 繁中服「愚人號」復刻活動導航

resource/global/YoStarKR/resource/tasks.json
referenced 3e3c2450c80631720ee7d1ad21d2fdadd8a04748
=> chore: YoStarKR ROI for StartToVisit

src/MaaCore/Task/Interface/CopilotTask.cpp, src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp, src/MaaCore/Task/Miscellaneous/BattleFormationTask.h, src/MaaCore/Task/Miscellaneous/BattleProcessTask.cpp, src/MaaCore/Task/Miscellaneous/BattleProcessTask.h
=> perf: 自动战斗-自动编队存储编队信息

.github/workflows/release-nightly-ota.yml
=> ci: nightly auto changelog

src/Python/asst/updater.py
修复linux下MAA更新压缩包下载错误问题（下载成.AppImage了）
=> fix: match the correst file suffix

resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarJP/resource/tasks.json, resource/global/YoStarKR/resource/tasks.json, resource/global/txwy/resource/tasks.json
=> fix: custom ROI and notes for StartToVisit txwy

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/Notification/DiscordNotificationProvider.cs, src/MaaWpfGui/Services/Notification/ExternalNotificationService.cs, src/MaaWpfGui/Services/Notification/SmtpNotificationProvider.cs, src/MaaWpfGui/Services/Notification/TelegramNotificationProvider.cs, src/MaaWpfGui/Services/Web/HttpService.cs, src/MaaWpfGui/Services/Web/IHttpService.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/ExternalNotificationSettingsUserControl.xaml
Procedural:
1. Get the bot token from discord application.
1.1 Create application at https://discord.com/developers/applications.
1.2 Go to `Bot` tab at https://discord.com/developers/applications/{your_app}/bot.
1.3 Get your bot token (reset or visible first visit).
2. Get your user id from discord web, https://discord.com/channels/@me.
2.1 Visit your `Settings-> Advance Settings`.
2.2 Enable the `Developer mode`.
2.3 Back to home page click your avatar.
2.4 Click the last row at the pop up panel called `Copy user id`.
3. Go to your Maa GUI.
3.1 Fill up the required info:
4. Test by click `Test` button.
=> feat: add multi external notifications

README.md
应使用合法的SPDX标识符，否则下游打包者将无法打包
https://gitlab.archlinux.org/archlinux/rfcs/-/blob/master/rfcs/0016-spdx-license-identifiers.rst
https://github.com/NixOS/nixpkgs/pull/297173
=> docs: declare license AGPL-3.0-only

3rdparty/include/Arknights-Tile-Pos/TileCalc2.hpp, src/MaaCore/Config/Miscellaneous/TilePack.cpp, src/MaaCore/Config/Miscellaneous/TilePack.h, src/MaaCore/Task/BattleHelper.cpp, src/MaaCore/Task/BattleHelper.h, src/MaaCore/Task/Experiment/CombatRecordRecognitionTask.cpp, src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
- 根据摄像机数据求出撤退和技能图标的位置
- 其实没改这么多, 有好多是 clang-format 改的格式化
=> feat: calculate position of skill & retreat button

.github/workflows/release-nightly-ota.yml, tools/ChangelogGenerator/changelog_generator.py
=> chore: 修复changelog_generator编码问题，以及部分重构

.github/workflows/gen-changelog.yml
=> ci: 修复gen_changelog的错误操作

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/Notification/BarkNotificationProvider.cs, src/MaaWpfGui/Services/Notification/ExternalNotificationService.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/ExternalNotificationSettingsUserControl.xaml
What is Bark?
https://bark.day.app/
=> feat: Add Bark notification provider

resource/copilot/old/SSS_阿尔斯特甜品制作平台_浊蒂艾丽妮版.json, resource/copilot/old/SSS_阿尔斯特甜品制作平台_浊蒂重岳版.json, resource/copilot/old/SSS_阿尔斯特甜品制作平台_浊蒂锏版.json
=> feat: 阿尔斯特甜品制作平台追加作业

resource/copilot/SSS_多索雷斯商业地块_浊心斯卡蒂+纯烬艾雅法拉+剑豪系（锏艾丽妮陈）+塞雷娅+澄闪_法术调和能量场.json
=> feat: 新增 多索雷斯商业地块 保全派驻作业

resource/copilot/SSS_边地移动城镇_浊心斯卡蒂+纯烬艾雅法拉or流明or闪灵+重岳or煌or水月+塞雷娅+提丰or早露_声波记录扩音器.json
perf: 优化边城保全声波记录扩音器脚本打法及修改脚本名称
=> perf: 优化边城保全声波记录扩音器脚本打法及修改脚本名称

resource/copilot/SSS_边地移动城镇_浊心斯卡蒂+纯烬艾雅法拉or流明or闪灵+重岳or煌or水月+塞雷娅+提丰or早露_可充能督战音响.json, resource/copilot/SSS_边地移动城镇_浊心斯卡蒂+纯烬艾雅法拉or流明or闪灵+重岳or煌or水月+塞雷娅+提丰or早露_尖端研究成果共享终端.json
=> feat: 新增 边地移动城镇另外两个元件的保全派驻作业

README.md, docs/en-us/1.1-USER_MANUAL.md, docs/en-us/3.2-CALLBACK_SCHEMA.md, docs/en-us/readme.md, docs/ja-jp/readme.md, docs/ja-jp/プロトコルドキュメント/コールバックAPI.md, docs/ja-jp/使用説明/詳細説明.md, docs/ko-kr/readme.md, docs/ko-kr/사용자설명서/사용자설명서.md, docs/ko-kr/스키마/2.콜백.md, docs/readme.md, docs/zh-tw/1.1-詳細介紹.md, docs/zh-tw/3.2-回呼訊息協議.md, docs/zh-tw/readme.md, docs/协议文档/回调消息协议.md, docs/用户手册/详细介绍.md, src/MaaCore/Task/Miscellaneous/DepotRecognitionTask.cpp
=> docs: 更新明日方舟工具箱地址

resource/tasks.json
fix #8890 
@Constrat 
I made modifications to `resource/tasks.json`. 
Would it be better to add it to `resource/global/YoStarKR/resource/tasks.json`? (to prevent any issues from arising...)
=> fix: Copilot Combatlist H-1x-x Stage recognition

src/MaaCore/Task/BattleHelper.cpp
=> fix: 增加对地图文件检查，避免只存在索引

.github/workflows/ci.yml, .github/workflows/smoke-testing.yml, .gitmodules, CMakeLists.txt, include/AsstCaller.h, src/MaaCore/AsstCaller.cpp, src/MaaCore/Config/AbstractResource.h, src/MaaCore/Config/GeneralConfig.cpp, src/MaaCore/Config/GeneralConfig.h, src/MaaCore/Config/ResourceLoader.cpp, src/MaaCore/Config/ResourceLoader.h, src/MaaCore/Controller/AdbController.cpp, src/MaaCore/Controller/AdbController.h, src/MaaCore/Controller/MumuExtras.cpp, src/MaaCore/Controller/MumuExtras.h, src/MaaCore/MaaCore.vcxproj, src/MaaCore/MaaCore.vcxproj.filters, src/MaaCore/Utils/LibraryHolder.hpp, src/MaaCore/Utils/Logger.hpp, src/MaaCore/Utils/Platform/PlatformWin32.cpp, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/MaaService.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/ConnectSettingsUserControl.xaml
- fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8784
=> feat: mumu extras

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Views/UI/RecognizerView.xaml
Hopefully reduce duplicate wontfix issue count by reminding users to remove favourite operators before detection
=> i18n: add favourite tip for i18n

src/MaaCore/Task/BattleHelper.cpp
- fix #9096
- fix #9079
- fix #9024
=> fix: 部署失败后不清除已占用格子

src/MaaCore/Controller/Controller.cpp, src/MaaCore/Controller/Controller.h, src/MaaCore/Controller/PlayToolsController.cpp, src/MaaCore/Task/Miscellaneous/StartGameTaskPlugin.cpp, src/MaaCore/Task/Miscellaneous/StartGameTaskPlugin.h
=> perf: auto start optimization + MAC fix 

resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
fix #9146 fix #8623 fix #8161 清除全部再选择， analyze之后有概率识别为已经选择，加了个重置
fix #9008 页码在2页时也会滑动出错，3页滑到最底改成了2页
=> fix: 尝试修复肉鸽编队不选干员

src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp
有没有用 Mumu 的看看能不能降低一点 CPU 占用, 感觉之后应该要改成更科学的方法
=> feat: 限制肉鸽截图速度

docs/协议文档/回调消息协议.md
In addition to commit 1f9aa4c7a79f7527c2e9d22df6f6aa9e4b31b97a
=> docs(回调消息协议): 增加「实例已销毁」

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/ConnectSettingsUserControl.xaml
#9072 ，在一些特定环节增加执行启动前/后脚本的环节，以便在Android实体设备等情况下，任务流程能正常进行。
=> feat:在特定环节执行启动前/后脚本

src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
=> fix: 尝试修复肉鸽编队错误,max page误判时仍然重置回最左边

src/MaaCore/Task/Fight/StageDropsTaskPlugin.cpp, src/MaaCore/Vision/Miscellaneous/StageDropsImageAnalyzer.h
=> perf: 在掉落不超出一页时，不额外滑动掉落列表及截图拼接

docs/readme.md
=> docs: fix a wrong link

src/MaaWpfGui/Main/AsstProxy.cs
=> feat: 在理智恢复满时推送信息

.github/ISSUE_TEMPLATE/cn-feature-request.yaml, .github/ISSUE_TEMPLATE/cn-mumu-report.yaml, .github/ISSUE_TEMPLATE/cn-others.yaml
顺便改了几个大小写(
不知道这东西需不需要 如果合并的话记得新建一个叫 `mumu api` 的 label √
=> chore: issue模板添加mumu反馈

resource/roguelike/Sami/encounter_for_deposit.json
=> refactor: 继续#7904的重构

src/Python/asst/asst.py, src/Python/asst/utils.py
The following interfaces are supported via this pr：
- set_connection_extras
- set_static_option
=> chore: update python API

src/MaaCore/Config/Roguelike/RoguelikeStageEncounterConfig.cpp, src/MaaCore/Config/Roguelike/RoguelikeStageEncounterConfig.h, src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Interface/RoguelikeTask.h, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.h
=> refactor: 肉鸽资源加载逻辑及目录结构重构 + 1

src/MaaCore/Task/Fight/MedicineCounterTaskPlugin.cpp
=> perf: add log output

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
=> feat: 由ci生成的非正式/公测/内测版判断为调试版本并且不再检查更新

src/MaaCore/Config/TaskData.cpp
=> feat: cache 统一默认为 false

src/MaaCore/Controller/Controller.cpp
=> fix: 修复连接前同步参数时日志报错的问题

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
feat: WPF Gui support for roguelike collapsal paradigm task plugin
=> feat: WPF Gui support for roguelike collapsal paradigm task plugin

src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.h
=> perf: 复用RoguelikeCollapsalParadigmTaskPlugin插件

tools/CropRoi/main.py
Read the commit messages for details.
=> perf(tools): do the name and cropping direction feat with the CropRoi tool

resource/roguelike/Sarkaz/autopilot/拆东补西.json, resource/tasks.json
=> fix: 修复萨卡兹肉鸽卡死在思绪界面

resource/tasks.json
=> fix: 修复肉鸽主题选择的导航问题

docs/zh-cn/protocol/task-schema.md, src/MaaCore/Common/AsstTypes.h, src/MaaCore/Config/TaskData.cpp, src/MaaCore/Vision/Config/MatcherConfig.cpp, src/MaaCore/Vision/Config/MatcherConfig.h, src/MaaCore/Vision/Matcher.cpp
匹配方法
- 3: 效果一般颜色敏感 TM_CCORR_NORMED
- 5: 效果较好颜色不敏感 TM_CCOEFF_NORMED
=> feat: 支持自定义 MatchTemplate 匹配算法

.github/workflows/res-update-game.yml
Maybe something better can be used as cache key, but tbf I don't really care too much. Prettier is prettier, what's important is the config.
=> perf: cache and targeting for prettier res update game

docs/zh-cn/protocol/task-schema.md, src/MaaCore/Common/AsstTypes.h, src/MaaCore/Config/TaskData.cpp, src/MaaCore/Vision/Config/MatcherConfig.cpp, src/MaaCore/Vision/Config/MatcherConfig.h, src/MaaCore/Vision/Matcher.cpp
Reverts MaaAssistantArknights/MaaAssistantArknights#9769
=> Revert "feat: 支持自定义 MatchTemplate 匹配算法"

.github/issue-checker.yml
现在只想到了个 GPU 加速 看看还有没有别的
正则里面写了个转义 应该是需要的吧
=> chore: issue-bot 增加关键词

resource/tasks.json, src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaWpfGui/Main/AsstProxy.cs
=> feat: 第五层boss停止

docs/.vuepress/plugins/search.ts
=> fix: 修正文档网页右上角search组件本地化显示问题

docs/maa_tasks_schema.json, docs/maa_tasks_schema_en.json, docs/zh-cn/protocol/task-schema.md, resource/tasks.json, src/MaaCore/Common/AsstTypes.h, src/MaaCore/Config/TaskData.cpp, src/MaaCore/Config/TaskData.h, src/MaaCore/Task/Infrast/InfrastProductionTask.cpp, src/MaaCore/Vision/Infrast/InfrastOperImageAnalyzer.cpp
=> feat: 删除 HashTaskInfo 相关

src/MaaCore/Task/AbstractTask.h
=> feat: AbstractTask新增附加已有插件、插件查找

.github/workflows/res-update-game.yml
- 开始前打印 actor 与 token 持有者信息
- committer 为 token 持有者
- 更准确的 email
- 修改 ResourceUpdater 和 res-update-game.yml 时也触发流程
=> chore: 优化资源更新流程

.github/dependabot.yaml
Pretty much identical to https://github.com/MaaAssistantArknights/MaaRelease/blob/main/.github/dependabot.yaml.
=> ci: dependabot gh actions automation

src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Roguelike/AbstractRoguelikeTaskPlugin.h, src/MaaCore/Task/Roguelike/Sami/RoguelikeCollapsalParadigmTaskPlugin.cpp, src/MaaCore/Task/Roguelike/Sami/RoguelikeCollapsalParadigmTaskPlugin.h
拆分自https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/9833 ,根据@zzyyyl老师的指导，改为disable插件。
=> feat: 肉鸽插件添加设置参数功能，设置失败的插件会被自动disable

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/Managers/IMainWindowManager.cs, src/MaaWpfGui/Services/Managers/MainWindowManager.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UI/NotifyIcon.xaml, src/MaaWpfGui/Views/UI/NotifyIcon.xaml.cs, src/MaaWpfGui/Views/UserControl/GUISettingsUserControl.xaml
=> feat: 隐藏托盘图标选项

resource/tasks.json
=> fix: 合成思绪出现藏品二选一时卡住

.github/workflows/stale.yml
=> chore: dont close issue too early

.github/workflows/stale.yml
=> chore: dont close stale issue too late

.github/workflows/optimize-templates.yml, tools/OptimizeTemplates/requirements.txt
Reverts MaaAssistantArknights/MaaAssistantArknights#9928
=> Revert "ci: optimize templates perf and fixes"

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/ViewModels/UI/RecognizerViewModel.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/ConnectSettingsUserControl.xaml
=> perf: Mumu截图增强设置增加测试按钮

src/MaaCore/Task/Interface/RoguelikeTask.cpp, src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalStartTaskPlugin.cpp, src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalStartTaskPlugin.h, src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalUseTaskPlugin.cpp, src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalUseTaskPlugin.h
由于插件 load_param返回值仅决定自身是否启用，反复读取参数进行验证
=> perf: 简化RoguelikeTask set_param

resource/tasks.json
=> fix: 肉鸽部分范围点击任务点进萨卡兹肉鸽思绪界面

resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarJP/resource/tasks.json, resource/global/YoStarKR/resource/tasks.json
They pre-installed this new interface
=> chore: StartToVisit ROI for Yostar servers

resource/roguelike/Sarkaz/recruitment.json, resource/tasks.json, src/MaaCore/Config/Roguelike/RoguelikeRecruitConfig.cpp, src/MaaCore/Config/Roguelike/RoguelikeRecruitConfig.h, src/MaaCore/MaaCore.vcxproj, src/MaaCore/MaaCore.vcxproj.filters, src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp, src/MaaCore/Task/Roguelike/RoguelikeConfig.h, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeShoppingTaskPlugin.cpp, src/MaaCore/Vision/Roguelike/RoguelikeParameterAnalyzer.cpp, src/MaaCore/Vision/Roguelike/RoguelikeParameterAnalyzer.h, src/MaaWpfGui/Main/AsstProxy.cs
=> feat: 增加一些肉鸽参数

docs/en-us/manual/introduction/combat.md, docs/en-us/manual/introduction/copilot.md, docs/en-us/manual/introduction/credit.md, docs/en-us/manual/introduction/infrastructure.md, docs/en-us/manual/introduction/integrated-strategy.md, docs/en-us/manual/introduction/reclamation-algorithm.md, docs/en-us/manual/introduction/recruit.md, docs/en-us/manual/introduction/rewards.md, docs/en-us/manual/introduction/startup.md, docs/en-us/manual/introduction/tools.md
just a test
i'm using `/docs/glossary/en-us.json`
the current glossary and wpf language files are not suitable for gpt
they often ignore the content :/
prompt:
```
我想请你翻译一下 MAA 软件的文档，MAA 全称为 MaaAssistantArknights，是一个在 GitHub 上开源的明日方舟自动化助手。我会提供给你一个文件，这个文件中记录了明日方舟游戏的专有名词术语表，术语表中的词汇有可能有 `class-` `general-` `items-` 等技术性前缀，请无视这些前缀。当你翻译的时候，请将这张术语表当作翻译词典，优先使用其中的翻译内容。由于我并没有给你提供 MAA 的专有名词术语表，所以当你遇到你认为是 MAA 专有名词的词语时，请将它们保持原样，不要翻译。我现在需要你从中文(zh-cn)翻译为英文(en-us)，请将翻译后的内容包含在代码块中，并保留原本的 Markdown 格式。需要翻译的内容如下：
```
```
我想请你翻译一下 MAA 软件的文档，MAA 全称为 MaaAssistantArknights，是一个在 GitHub 上开源的明日方舟自动化助手。由于我并没有给你提供明日方舟的专有名词术语表和 MAA 的专有名词术语表，所以当你遇到你认为是明日方舟游戏专有名词或 MAA 专有名词的词语时，请将它们保持原样，不要翻译。我现在需要你从中文(zh-cn)翻译为英文(en-us)，请将翻译后的内容包含在代码块中，并保留原本的 Markdown 格式。需要翻译的内容如下：
```
```
我想请你翻译一下 MAA 软件的文档，MAA 全称为 …
```
=> docs: use gpt to translate zh-cn to en-us

resource/config.json
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9396
Tested on raspberry pi 5 (Debian 12) with waydroid 1.4.2
=> feat: Add connection config for waydroid emulator

.github/workflows/ci.yml
=> ci: stop running ci test workflow when new changes are pushed in a branch

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/MallSettingsUserControl.xaml
If I remember correctly this was something that @status102 proposed a while back. (Can't remember the issue #) I had some time so I wrote some stuff. I tested everything and it's working as expected
(Since it's basically just a copy of the CreditFightTask).
If changes are needed, feel free to directly commit (no git push --force please :)
=> feat: visiting only once a day logic and gui

src/MaaWpfGui/Res/Localizations/en-us.xaml
EN translate for reclamation algorithm.
=> i18n: EN translate for reclamation

resource/tasks.json
=> fix: 识别思绪太快导致无法点击驮兽归队

src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.h
此段代码在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10116 添加。现补上注释，并删除多余的分号（
=> chore: 为肉鸽编队滑页触底判定的代码添加注释

resource/global/txwy/resource/tasks.json
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10181
不知道能不能行，我没台服号
=> fix: 台服目前坍縮值改为當前坍縮值

resource/tasks.json
=> chore: added regex for EX stages

resource/tasks.json
- 主页面
- 点击开始演算后的进入后舍教程界面
- 第一关教程关对话界面
- 可自由移动镜头的游戏内选关界面
=> refactor: 允许用户在不同位置开始生息演算任务

resource/copilot/SSS_交战荒野_澄闪+塞雷娅+纯烬艾雅法拉or流明+重岳or水月or阿斯卡纶_皇家科学院望远镜.json, resource/copilot/SSS_玉门市集_澄闪+塞雷娅+维什戴尔+纯烬艾雅法拉+重岳or水月or阿斯卡纶_攀云机.json
=> feat: 新增 交战荒野、玉门市集 保全派驻作业

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Services/Web/HttpService.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/VersionUpdateSettingsUserControl.xaml
=> feat: 增加SOCKS5支持

resource/copilot/SSS_交战荒野_澄闪+塞雷娅+纯烬艾雅法拉or流明+重岳or水月or阿斯卡纶_皇家科学院望远镜.json, resource/copilot/SSS_玉门市集_澄闪+塞雷娅+维什戴尔+纯烬艾雅法拉+重岳or水月or阿斯卡纶_攀云机.json
=> perf: 优化 交战荒野、玉门市集 保全派驻作业

resource/copilot/SSS_玉门市集_澄闪+塞雷娅+维什戴尔+纯烬艾雅法拉+重岳or水月or阿斯卡纶_攀云机.json
=> perf: 优化 玉门市集 保全派驻作业

src/MaaCore/Common/AsstBattleDef.h, src/MaaCore/Common/AsstTypes.h, src/MaaCore/Config/Miscellaneous/SSSCopilotConfig.cpp, src/MaaCore/Task/SSS/SSSBattleProcessTask.cpp
Reverts MaaAssistantArknights/MaaAssistantArknights#10284
不该是chore吧，要发版了等发版完再进
=> Revert "chore: 保全作战相同location以json写的策略顺序执行、全局保留core干员不作为过牌干员"

resource/tasks.json, src/Cpp/main.cpp
=> chore: tasks及smoking-test样例优化

src/MaaCore/Common/AsstBattleDef.h, src/MaaCore/Common/AsstTypes.h, src/MaaCore/Config/Miscellaneous/SSSCopilotConfig.cpp, src/MaaCore/Task/SSS/SSSBattleProcessTask.cpp
This reverts commit d57e74a.Reverts MaaAssistantArknights/MaaAssistantArknights#10299
=> Revert "feat: 保全作战保留core不过牌且放置core后回到待部署则重放工具人和core"

src/MaaWpfGui/Res/Themes/Dark.xaml, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
非功能性改动 by @ABA2396 
拆分自 #9457 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/212209172fda8dc463a8c2dec68a7e1114ee8c16
=> perf: CopilotViewModel

README.md, docs/en-us/develop/pr-tutorial.md, docs/en-us/readme.md, docs/ja-jp/develop/pr-tutorial.md, docs/ja-jp/readme.md, docs/ko-kr/develop/pr-tutorial.md, docs/ko-kr/readme.md, docs/zh-cn/develop/pr-tutorial.md, docs/zh-cn/readme.md, docs/zh-tw/develop/pr-tutorial.md, docs/zh-tw/readme.md
=> docs: 贡献者头像添加 105 上限

resource/tasks.json
=> fix: 生息演算2"Reclamation2StageEnter"->next纠正

.gitmodules
=> chore: remove MaaDeps submodule

src/MaaWpfGui/Extensions/DateTimeExtension.cs, src/MaaWpfGui/Extensions/Win32Extension.cs, src/MaaWpfGui/Helper/GpuOption.cs, src/MaaWpfGui/Helper/MessageBoxHelper.cs, src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/NativeMethods.txt
=> chore: use CsWin32 source generator instead of random pinvoke library

.github/ISSUE_TEMPLATE/cn-bug-report.yaml, .github/ISSUE_TEMPLATE/en-bug-report.yaml
=> chore: 更新 bug issue 模板

.gitignore
=> chore: ignore MaaDeps

src/MaaWpfGui/Main/Bootstrapper.cs
=> fix: DoDragDrop 拖动操作已在进行中

src/MaaCore/Task/Roguelike/RoguelikeFormationTaskPlugin.cpp
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10386
上次改的时候大概脑子抽了。怎么会犯那么低级的错误……
=> fix: 肉鸽编队检测在未触底时返回 true

src/MaaWpfGui/Configuration/AnnouncementInfo.cs, src/MaaWpfGui/Configuration/ConfigFactory.cs, src/MaaWpfGui/Configuration/Root.cs, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/ViewModels/UI/AnnouncementViewModel.cs
=> refactor: 迁移公告相关配置

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/FightSettingsUserControl.xaml
=> refactor: 重构 FightSettingsUserControl

src/MaaWpfGui/Services/Notification/ExternalNotificationService.cs, src/MaaWpfGui/Services/Notification/TelegramNotificationProvider.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/ExternalNotificationSettingsUserControl.xaml, src/MaaWpfGui/Views/UserControl/GUISettingsUserControl.xaml
=> feat: 外部通知支持多选

resource/roguelike/Mizuki/recruitment.json, resource/roguelike/Phantom/recruitment.json, resource/roguelike/Sami/recruitment.json
=> perf: 全肉鸽招募适配娜仁图亚、艾拉

tools/RoguelikeOperSearch/.gitignore, tools/RoguelikeOperSearch/RoguelikeOperSearch.py
查找当前recruitment.json中未出现的干员。当前结果如下。
```
Phantom: 阿米娅-WARRIOR , 崖心 , 暗索 , 雪雉 , 海霓 , 杏仁 , 维荻 , 露托 , 深巡 , 乌尔比安 , 妮芙 , 渡桥 , 锡人 , 阿罗玛
Mizuki: 芙兰卡 , 白雪 , 摩根 , 守林人 , 崖心 , 慕斯 , 安哲拉 , 陨星 , 暗索 , 红豆 , 宴 , 熔泉 , 慑砂 , 雪雉 , 子月 , 空构 , 铅踝 , 明椒 , 截云 , 海霓 , 杏仁 , 双月 , 露托 , 深巡 , 乌尔比安 , 妮芙 , 渡桥 , 锡人 , 远牙 , 松果 , 阿罗玛 , 绮良 , 刺玫
Sami: 阿米娅-WARRIOR , 崖心 , 暗索 , 雪雉 , 杏仁 , 锡人 , 阿罗玛
Sarkaz: 阿米娅-WARRIOR , 崖心 , 暗索 , 雪雉 , 杏仁 , 阿罗玛
```
跑pre-commit初始化半小时了还没动静，先直接网页端add-files了，应该没啥问题。顺便，这个东西或许该改个名字。
=> chore(tools): 查找肉鸽招募中未提及的干员

tools/ResourceUpdateValidator/index.mjs
Fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10453#issuecomment-2330932839
=> ci: 修复 bug

.github/ISSUE_TEMPLATE/cn-bug-report.yaml, .github/ISSUE_TEMPLATE/cn-mumu-report.yaml, .github/ISSUE_TEMPLATE/en-bug-report.yaml, MAA.sln.DotSettings, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Extensions/DateTimeExtension.cs, src/MaaWpfGui/Helper/LocalizationHelper.cs, src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/Properties/BuildDateTimeAttribute.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/RemoteControl/RemoteControlService.cs, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UserControl/VersionUpdateSettingsUserControl.xaml, src/MaaWpfGui/Views/UserControl/VersionUpdateSettingsUserControl.xaml.cs
c479834d38822ed43c8d2f2df3e3d7ba1154256e
=> feat: date format language based

resource/roguelike/Phantom/autopilot/从众效应.json, resource/roguelike/Phantom/recruitment.json
=> perf: 优化傀影肉鸽招募策略、“从众效应”部署策略

src/MaaCore/Task/ProcessTask.cpp, src/MaaCore/Task/ProcessTask.h
- 删除了 ProcessTask 中 on_run_fails() 相关逻辑
- 修改了对 on_error_next 的处理
=> refactor: 重构 ProcessTask

src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Views/UI/ErrorView.xaml.cs
@MaaAssistantArknights/global-support-team 
有时候我们可能真的~~低~~高估了用户使用电脑的水平）
=> chore: 添加移动 MAA.exe 的解决方案

docs/en-us/manual/device/windows.md, docs/zh-cn/manual/device/windows.md
https://github.com/MaaAssistantArknights/maa-website/discussions/174#discussioncomment-10564128
=> docs: 更新 google play beta 开发者模拟器相关文档

resource/tasks.json
Fixes #10539 
此处感谢用户 @yuanlemon 帮忙测试。
=> fix: 修正生息演算滑动参数，为离开区域节点相关任务添加回滚

src/MaaCore/Config/GeneralConfig.cpp, src/MaaCore/Config/GeneralConfig.h, src/MaaCore/Controller/AdbController.cpp, src/MaaCore/Controller/AdbController.h
=> perf: 使用 devices 判断是否需要连接

MAA.sln.DotSettings, src/MaaCore/Controller/AdbController.cpp, src/MaaCore/Controller/AdbController.h, src/MaaCore/LDExtras.cpp, src/MaaCore/LDExtras.h, src/MaaCore/MaaCore.vcxproj, src/MaaCore/MaaCore.vcxproj.filters, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Constants/UILogColor.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Res/Themes/Dark.xaml, src/MaaWpfGui/Res/Themes/Light.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/ConnectSettingsUserControl.xaml
=> feat: LD 截图

resource/tasks.json, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/RemoteControl/RemoteControlService.cs, src/MaaWpfGui/ViewModels/UI/RecognizerViewModel.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UI/RecognizerView.xaml
=> perf: 优化 RecognizerViewModel

resource/tasks.json
=> fix: 降低 Tales@RA@LeaveCurrentZone 任务的 templThreshold

.github/ISSUE_TEMPLATE/cn-bug-report.yaml, .github/ISSUE_TEMPLATE/en-bug-report.yaml, resource/tasks.json
- close #10643 
cc @Constrat 
`MB` for overseas, not sure if it would run steady. merge it yourself if you like
=> perf: 开始唤醒增加资源更新Ocr

tools/ResourceUpdater/main.cpp
Reverts MaaAssistantArknights/MaaAssistantArknights#10683
Issue also happens on GH runner
=> Revert "feat(perf): multithreaded resource updater"

resource/roguelike/Sami/recruitment.json, resource/roguelike/Sarkaz/recruitment.json
=> perf: 萨米/萨卡兹肉鸽招募适配维娜 · 维多利亚

src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/Views/UI/CopilotView.xaml
=> feat: 自动战斗-战斗列表增加单任务作业查看

src/MaaWpfGui/Views/UserControl/TimerSettingsUserControl.xaml
=> fix: 修复错误的`定时 7`分钟最大值

src/MaaWpfGui/Services/Notification/ServerChanNotificationProvider.cs
新增server酱3（APP端）的推送逻辑（通过 sendkey 判断）
=> feat: 新增server酱3的推送逻辑

resource/tasks.json
=> fix: GO 识别错误

src/MaaWpfGui/Res/Localizations/zh-cn.xaml
=> docs: 更新MuMu截图增强模式中端口的文本描述

src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs
【原方案已废弃】
重启 mutex 单路径MAA多开限制
close #3767
close #5171
=> feat(#3767):restricted multi-instance under same MAA

resource/tasks.json
=> fix: 降低 肉鸽投资确认 模板匹配阈值

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> docs: 更正错误说明

tools/ChangelogGenerator/changelog_generator.py
=> fix: 错误分类 changelog

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
看到 B 站那条吐槽于是连夜（？）更新了一下提示语句。
中文（简体）和英文是我自己写的，日文，韩文和中文繁体使用了百度翻译，也许需要 global team 去校对一下。
=> chore: MAA 多开限制提示优化

src/MaaCore/Controller/AdbController.cpp, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/Views/UserControl/ConnectSettingsUserControl.xaml
=> fix: MuMu bridge connection

.github/ISSUE_TEMPLATE/cn-feature-request.yaml, .github/ISSUE_TEMPLATE/en-feature-request.yaml
=> chore: 更新 Feature request 模板

resource/Arknights-Tile-Pos/level_act38side_01.json, resource/Arknights-Tile-Pos/level_act38side_02.json, resource/Arknights-Tile-Pos/level_act38side_03.json, resource/Arknights-Tile-Pos/level_act38side_04.json, resource/Arknights-Tile-Pos/level_act38side_05.json, resource/Arknights-Tile-Pos/level_act38side_06.json, resource/Arknights-Tile-Pos/level_act38side_07.json, resource/Arknights-Tile-Pos/level_act38side_08.json, resource/Arknights-Tile-Pos/level_act38side_09.json, resource/Arknights-Tile-Pos/level_act38side_10.json, resource/Arknights-Tile-Pos/level_act38side_sp01.json, resource/Arknights-Tile-Pos/level_act38side_sp02.json, resource/Arknights-Tile-Pos/level_act38side_sp03.json, resource/Arknights-Tile-Pos/level_act38side_tr01.json, resource/Arknights-Tile-Pos/overview.json
=> chore: PV 关卡地图数据

resource/tasks.json
=> fix: 为生息演算无存档刷点模式，点击区域节点任务加上 1 秒的 postDelay

resource/tasks.json
=> fix: enlarge rectMove offset for PV-10

resource/custom_infrast/153_layout_4_times_a_day.json, src/MaaWpfGui/Views/UserControl/ExternalNotificationSettingsUserControl.xaml
=> fix: ExternalNotificationTips 未居中

src/MaaWpfGui/Models/ResourceUpdater.cs, src/MaaWpfGui/Services/Web/HttpService.cs, src/MaaWpfGui/ViewModels/UI/RootViewModel.cs, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs, src/MaaWpfGui/ViewModels/UserControl/VersionUpdateSettingsUserControlModel.cs, src/MaaWpfGui/Views/UI/SettingsView.xaml, src/MaaWpfGui/Views/UserControl/VersionUpdateSettingsUserControl.xaml, src/MaaWpfGui/Views/UserControl/VersionUpdateSettingsUserControl.xaml.cs
=> rft: 拆分设置-软件更新

resource/tasks.json
=> fix: 萨卡兹肉鸽降低 Sarkaz@Roguelike@CloseCollectionContinue 阈值

MAA.sln.DotSettings, src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs
=> fix: 从 wpf 层面上不再允许用户在萨卡兹肉鸽用奇怪的分队刷源石锭

src/MaaWpfGui/MaaWpfGui.csproj, src/MaaWpfGui/ViewModels/UI/RootViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/Views/UI/RootView.xaml
=> perf: WpfGui优化任务进度显示

resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeDifficultySelectionTaskPlugin.cpp
Fixes #11128.
虽然和这个 Issue 无直接联系，但是相关 bug 是在检查这个 issue 的 Log 时发现的。
=> fix: 修复肉鸽选难度的若干 Bug

resource/tasks.json
=> fix: 完成招募后点击进入但无响应

resource/tasks.json
This reverts commit a8c04a4b1719ebcca0298db576aee38e1f7b04a9.
=> Revert "fix: 刷理智失败次数限制未生效"

tools/build_macos_universal.zsh
- 调整肉鸽参数 #11215
- 添加不同版本客户端对应的 iOS 包名 #9878
- 改进 macOS 上的编译脚本
=> fix: macOS 肉鸽参数&客户端包名

tools/build_macos_universal.zsh
- 支持 GUI 日志
- 小幅重构导航布局
- 设置肉鸽最高难度为999
=> fix: 限制Mac GUI肉鸽最高难度数值

src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Utilities/AutoStart.cs, src/MaaWpfGui/ViewModels/UserControl/Settings/StartSettingsUserControlModel.cs
cc @MaaAssistantArknights/global-support-team
=> chore: 管理员权限启动无法使用开机自启

resource/tasks.json
=> fix: 萨卡兹肉鸽点刺成锭分队开局思维阻塞

resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarJP/resource/tasks.json, resource/global/YoStarKR/resource/tasks.json
=> chore: remove Yostar servers reclamation algorithm temp edits

website/apps/web/src/App.tsx, website/apps/web/src/components/foundations/GlowButton/GlowButton.tsx, website/apps/web/src/components/home/AnimatedBlobs/AnimatedBlobs.tsx, website/apps/web/src/components/home/HomeActions/HomeActions.tsx, website/apps/web/src/components/home/HomeHero.tsx, website/apps/web/src/components/home/HomeHeroHeader/HomeHeroHeader.tsx
你好！我稍微更改了一下MAA官网的动画表现，集中在刚打开官网时的动画，之前没有太多的动画，现在看起来更加优雅。改动一般都是再各个组件上应用frame motion的blur淡入效果以及一些小的移动动画，希望你们能够喜欢！祝能够有一个美好的一天
=> feat: enhance MAA website animation for a more elegant appearance

resource/custom_infrast/243_layout_4_times_a_day.json
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.
根据[公孙长乐 2024-12-16 新视频](https://www.bilibili.com/video/BV13gBwYbEG5/?t=158)制作。
变化不大，只是用引星棘刺替换掉了斑点。
Spot -> Thorns the Lodestar for gold manufacture
=> feat: 更新 243 极限效率一天四换排班表（20241216 修订）

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/Notification/DiscordWebhookNotificationProvider.cs, src/MaaWpfGui/Services/Notification/ExternalNotificationService.cs, src/MaaWpfGui/ViewModels/UserControl/Settings/ExternalNotificationSettingsUserControlModel.cs, src/MaaWpfGui/Views/UserControl/Settings/ExternalNotificationSettingsUserControl.xaml
一個比較簡單的Discord外部通知方法，不用建立bot就能用
=> feat: add discord webhook external notification

.github/workflows/markdown-checker.yml
- **test: remove cache from markdown checker**
- **chore: remove caching from markdown-checker**
=> ci: remove cache from markdown-checker

resource/global/txwy/resource/tasks.json
=> fix: tw OcrReplace 肉鸽招募助战

resource/roguelike/Phantom/autopilot/远方来客.json
=> fix: 删除傀影肉鸽远方来客意义不明的撤退

resource/tasks.json
=> feat: 萨卡兹内容拓展II点刺进入商店获得构想

resource/roguelike/Sarkaz/autopilot/冰川期.json, resource/roguelike/Sarkaz/recruitment.json
=> feat: 萨卡兹肉鸽冰川期作战策略

docs/zh-cn/protocol/integration.md
=> docs: 为肉鸽参数 start_with_seed 添加文档

resource/config.json
=> fix: get display for General

resource/tasks.json
自动肉鸽中选中萨卡兹肉鸽，如此时存在未结束的对局，maa会卡死
=> fix: 修复肉鸽种子模式引起的异常卡死

resource/roguelike/Sarkaz/encounter/default.json, resource/roguelike/Sarkaz/encounter/deposit.json
=> perf: 肉鸽优先拿美愿

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/ViewModels/TaskViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/StartUpSettingsUserControlModel.cs
=> rft: WpfGui重构 一键长草任务callback拆分

tools/RoguelikeRecruitmentTool/roguelike/config/main.py, tools/RoguelikeRecruitmentTool/roguelike/recruitment/export.py, tools/RoguelikeRecruitmentTool/roguelike_recruitment_tool/main_window.py
清理 branch 的时候发现了这个。感觉好像没啥问题，水一个 PR 吧。
=> refactor: [ recruitment tool ] use StrEnum instead of Enum for Theme

resource/global/txwy/resource/tasks.json
剛好目前有繁中服有幸運牆活動
又剛好發現這部分還沒補上 (x
=> feat: 繁中服 抽幸運牆的功能

README.md, docs/en-us/readme.md, docs/ja-jp/readme.md, docs/ko-kr/readme.md, docs/zh-cn/readme.md, docs/zh-tw/readme.md
=> docs: README 移除 MaaX，更换前端仓库地址

resource/global/txwy/resource/tasks.json
=> fix: 繁中服 生息演算讀檔畫面卡住

resource/global/txwy/resource/tasks.json
=> feat: 繁中服更新活動導航"懷黍離"

resource/global/txwy/resource/tasks.json
fix: #11647 
順便增加了一些很有可能會被認錯字的東西
~~提高容錯~~
=> fix: 繁中服-生息演算中，完成生存週期畫面、大地圖畫面卡住

resource/global/txwy/resource/tasks.json
=> chore: 繁中服「懷黍離」導航入口更動

resource/roguelike/Sarkaz/encounter/default.json, resource/roguelike/Sarkaz/encounter/deposit.json
This reverts commit 8f5ee4819e247091b2035f6046c6e6ec7757fe8e, reversing changes made to 0b0486a4ee20baf2531c64d20cdfcc11b2fc1b2c.
=> Revert "perf: 肉鸽优先拿美愿 (#11558)"

src/MaaWpfGui/Views/UserControl/Settings/GameSettingsUserControl.xaml
=> chore: 修改划火柴设置界面布局

README.md, docs/en-us/readme.md, docs/ja-jp/readme.md, docs/ko-kr/readme.md, docs/zh-cn/readme.md, docs/zh-tw/readme.md
=> feat: discord link for website docs

resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp, src/MaaCore/Task/Roguelike/RoguelikeConfig.h, src/MaaCore/Task/Roguelike/RoguelikeLastRewardSelectTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeLastRewardSelectTaskPlugin.h
=> rft: 调整肉鸽选择烧水奖励任务链，重新将Roguelike@LastRewardConfirm并入主任务链

src/MaaCore/Assistant.cpp, src/MaaCore/Utils/Logger.hpp
顺带改改文件大小限制 
@Saratoga-Official @ABA2396 @Alan-Charred 
看看多大比较好，4mb太小，Github单文件应该在25mb左右，然后压缩应该能去到100mb盲猜
=> rft: 任务执行期间Log Rotate增加检查，并上调阈值至64MiB

resource/roguelike/Sarkaz/autopilot/存亡之战.json
=> perf: 优化存亡之战部署策略

CHANGELOG.md, src/MaaCore/Vision/Miscellaneous/RecruitImageAnalyzer.cpp
=> Release v5.13.0-beta.4

src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp
=> fix：招募测试函数修复

resource/global/txwy/resource/tasks.json
之前不小心把 "記錄" 選成 "紀錄" 了 
哭啊 :(
問題來源 (已解決) :
https://discord.com/channels/1326213891176271934/1326223367161905163/1334755546712248350
=> fix: 繁中服無法進入薩米肉鴿

src/MaaCore/Task/Roguelike/RoguelikeBattleTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp, src/MaaCore/Task/Roguelike/RoguelikeConfig.h, src/MaaCore/Task/Roguelike/RoguelikeCustomStartTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeShoppingTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeSkillSelectionTaskPlugin.cpp, src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalGainTaskPlugin.cpp, src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalStartTaskPlugin.cpp, src/MaaCore/Task/Roguelike/Sami/RoguelikeFoldartalUseTaskPlugin.cpp
原本想跟RoguelikeConfig放到同一层的，再看看.jpg
=> rft: 简化肉鸽局中数据存储

src/MaaWpfGui/Constants/MaaUrls.cs, src/MaaWpfGui/Models/ResourceUpdater.cs
=> feat: 添加mirror酱备用线路

resource/tasks.json
@Daydreamer114 来看眼这个行不行，我萨卡兹没满
=> fix: CheckLevelMax: OCR["MAX"]->OCR["-/-"]

resource/global/YoStarKR/resource/tasks.json
ref 34acb5b739a82a697279fcefa682509c1dce23bd
=> chore: add missing text for YostarKR

src/MaaWpfGui/Utilities/AutoStart.cs
=> chore: using

resource/tasks.json, src/MaaCore/Task/Miscellaneous/AccountSwitchTask.cpp
beabba92e3033d50e6d1c83aca9ec88094ab3742
=> fix: 移除账号切换中不必要的任务

src/MaaWpfGui/ViewModels/UI/SettingsViewModel.cs, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/FightSettingsUserControlModel.cs, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/InfrastSettingsUserControlModel.cs
=> fix: null check

docs/zh-cn/protocol/integration.md
=> feat(mac): 肉鸽参数配置新参数

resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarJP/resource/tasks.json, resource/global/YoStarKR/resource/tasks.json, resource/global/txwy/resource/tasks.json, resource/tasks.json, src/MaaCore/Task/Roguelike/RoguelikeCustomStartTaskPlugin.cpp
need some help with Ocr content and Roi
对应选择分队界面 顶部中间
=> fix: 肉鸽开局无法选择指挥分队时放弃探索

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Services/MaaService.cs, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
参照 https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/zh-cn/protocol/integration.md 引入AsstTaskType
=> rft: WpfGui引入AsstTaskType代替硬编码

resource/roguelike/Sarkaz/encounter/default.json
=> fix: JP 事件译名重复

src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp, src/MaaCore/Task/Miscellaneous/AutoRecruitTask.h, src/MaaCore/Vision/Miscellaneous/RecruitImageAnalyzer.h
=> fix: 3星招募逻辑修复

tools/ResourceUpdater/main.cpp
@HX3N So, I've made some optimizations as well. Have you ever used the ResourceUpdater?
I would like you to test if what is done is what you want / expect it to.
=> feat: remove spaces for all ocrReplaces for KR + various optimizations

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/RoguelikeSettingsUserControlModel.cs
cc @MaaAssistantArknights/global-support-team
=> feat: Sarkaz extend II 专业人士分队

resource/roguelike/Sarkaz/autopilot/公害.json
=> perf: IS4 调整公害ew部署

src/MaaWpfGui/ViewModels/UserControl/TaskQueue/RoguelikeSettingsUserControlModel.cs
=> perf: 肉鸽难度选项降到18个

src/MaaCore/Config/TaskData.cpp
用于解决 a8d68dd72df6eef1d2f8feed3883299922ec1a17 类似的问题
=> chore: TaskData增加OcrTask的ocrReplace合法性检查

src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> perf: 肉鸽为识别错误的事件也添加 callback

src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeStageEncounterTaskPlugin.h
=> fix: 狭路相逢遇到构想卡死

src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp, src/MaaCore/Task/Infrast/InfrastOfficeTask.cpp
=> fix: 会客室进入失败

resource/tasks.json
@dragonheart107 You can use this if you want.
Make delay changes as you wish if they are working correctly
=> fix: fast forward text in encounter

src/MaaWpfGui/Helper/CopilotHelper.cs, src/MaaWpfGui/Models/CopilotModel.cs, src/MaaWpfGui/Models/SSSCopilotModel.cs, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs
重构作业、作业集解析，移除部分全局变量状态
~~移除关卡名正则~~，使用地图数据
修复作业名重复时，文件覆盖
开始执行时，检查地图是否存在，不存在将无法开始
（拉了坨大的
（等这个合完，再加作业集的干员检测
=> rft: Wpf自动战斗重构

src/MaaWpfGui/Helper/ConfigurationHelper.cs
=> feat(wpf): Wpf旧Config增加int读取

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Services/Notification/SmtpNotificationProvider.cs, src/MaaWpfGui/ViewModels/UserControl/Settings/ExternalNotificationSettingsUserControlModel.cs, src/MaaWpfGui/Views/UserControl/Settings/ExternalNotificationSettingsUserControl.xaml
=> feat: ExternalNotification 可选输出详细信息

.github/workflows/release-nightly-ota.yml, .github/workflows/release-ota.yml
Reverts MaaAssistantArknights/MaaAssistantArknights#12024
=> Revert "ci: 临时措施"

src/MaaCore/Task/Miscellaneous/AutoRecruitTask.cpp, src/MaaCore/Vision/Miscellaneous/RecruitImageAnalyzer.h
=> fix: 修复不自动招募4星干员时，执行空招募的问题

resource/global/YoStarEN/resource/tasks.json, resource/global/YoStarJP/resource/tasks.json, resource/global/YoStarKR/resource/tasks.json
@Constrat I don't have EN client or account so uh, does this work?
If it does work we might consider push this to all global clients
=> fix: Sarkaz MS unable to progress from post StartExplore

.github/workflows/release-nightly-ota.yml
=> ci: nightly版本打包tag获取

src/MaaCore/Task/Roguelike/RoguelikeIterateMonthlySquadPlugin.h
@Constrat global has only one MS for IS5 still, does it break
=> fix: sarkaz MS count 1->8

resource/global/YoStarJP/resource/tasks.json
=> chore: YostarJP DT テラ飯 preload

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Models/AsstTasks/AsstRecruitTask.cs, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/RecruitSettingsUserControlModel.cs
@Roland125 
有些地方还是感觉怪怪的，level3和level1的只有confirm没有select
=> rft: wpf招募任务序列化

resource/custom_infrast/243_layout_4_times_a_day.json
修复格雷伊重复进驻宿舍的排班错误
Fixed the bug that Greyy were designated twice in the dorms
（明明昨天检查了两遍，竟然没发现这个问题。不好意思）
=> fix: 更新 243 极限效率一天四换排班表

docs/zh-cn/protocol/integration.md, src/MaaCore/Task/Infrast/InfrastReceptionTask.cpp, src/MaaCore/Task/Infrast/InfrastReceptionTask.h, src/MaaCore/Task/Interface/InfrastTask.cpp, src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Models/AsstTasks/AsstInfrastTask.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/InfrastSettingsUserControlModel.cs, src/MaaWpfGui/Views/UserControl/TaskQueue/InfrastSettingsUserControl.xaml
- close #12047 
- wait for #12053
=> perf: 基建信息板收取信用增加开关

resource/tasks.json
哪来的普瑞塞斯，出去.wav
Should fix the long-standing issue of stuck on map screen by clicking and going back to ```Roguelike@Stages#next```.
=> fix: roguelike already left encounter check and return from map screen

src/MaaWpfGui/Models/ResourceUpdater.cs
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/11043
最近不少人遇到这个问题，解压错误。换个目录试试
=> chore: 资源更新换一个解压目录

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/12200
=> chore: Update zh-cn.xaml

src/MaaWpfGui/Constants/Enums.cs, src/MaaWpfGui/Models/ResourceUpdater.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
chore: 新增 MirrorChyan ErrorCode 提示
=> chore: 新增 MirrorChyan ErrorCode 提示

resource/global/txwy/resource/tasks.json
=> fix: 繁中服生息演算無法讀檔

.gitignore
=> chore: ignore system shits

src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UserControl/Settings/TimerSettingsUserControlModel.cs, src/MaaWpfGui/Views/UserControl/Settings/TimerSettingsUserControl.xaml
=> chore: 添加一个临时定时

resource/tasks.json, src/MaaWpfGui/Configuration/ConfigFactory.cs, src/MaaWpfGui/Helper/ConfigurationHelper.cs, src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/ViewModels/UserControl/Settings/IssueReportUserControlModel.cs
=> feat: 日志包一并打包gui配置文件 (#12310)

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Views/UserControl/GuideUserControl.xaml
The settings section was just translated so it's likely it's not precise with what the emulators display in their correspective languages.
cc @Rbqwow docs!
=> feat: Guide enable ADB

resource/custom_infrast/153_layout_4_times_a_day.json, resource/custom_infrast/243_layout_4_times_a_day.json
根据[公孙长乐 2025-04-12 新视频](https://www.bilibili.com/video/BV14XdXYCEqh/?t=127)制作。
Replacing Kal'tsit with Mon3tr...
=> feat: 更新 243/153 极限效率一天四换排班表（20250412 修订）

src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/CustomSettingsUserControlModel.cs, src/MaaWpfGui/Views/UserControl/TaskQueue/CustomUserControl.xaml
=> feat: CustomTasks 支持逗号、分号切割任务列表

src/MaaWpfGui/Res/Localizations/ko-kr.xaml
=> i18n: KR translation tweaks

resource/copilot/SSS_多索雷斯在建地块_塞雷娅+泥岩+维什戴尔_任意元件.json, resource/copilot/SSS_尚蜀夜市——澄闪or荒芜拉普兰德+维什戴尔+余or任意盾+Mon3tror闪灵+伊桑or阿斯卡纶_天工夜行套装.json, resource/copilot/SSS_荒地群兽音乐厅_塞雷娅+星熊+维什戴尔_轻型瞄准测距仪 .json, resource/copilot/SSS_荒地群兽音乐厅_荒芜拉普兰德+纯烬艾雅法拉+重岳+维什戴尔_轻型瞄准测距仪.json
feat: 新增 尚蜀夜市、多索雷斯在建地块、荒地群兽音乐厅 保全派驻作业
=> feat: 新增 尚蜀夜市、多索雷斯在建地块、荒地群兽音乐厅 保全派驻作业

src/MaaWpfGui/Constants/ConfigurationKeys.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/ViewModels/UserControl/Settings/BackgroundSettingsUserControlModel.cs, src/MaaWpfGui/Views/UI/RootView.xaml, src/MaaWpfGui/Views/UserControl/Settings/BackgroundSettings.xaml
提供背景图片拉伸模式的选项
None没提供，真的有人用那个吗.jpg
=> feat: Background stretch modes

resource/copilot/SSS_尚蜀夜市——维什戴尔+塞雷娅+伊桑+温蒂_天工夜行套装.json
=> feat: 新增 尚蜀夜市 保全派驻作业

website/turbo.json
https://github.com/vercel/turborepo/issues/7279
[skip changelog]
=> fix: 修复某些情况下官网本地开发服务器拒绝连接的问题

docs/staticwebapp.config.json, website/apps/web/src/components/home/HomeHero.tsx
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/12405
=> fix: 移除官网的PerformanceMonitor

website/apps/web/src/components/home/HomeActions/HomeActions.tsx, website/apps/web/src/components/home/HomeActionsRelease/HomeActionsRelease.tsx, website/apps/web/src/components/home/HomeHero.tsx, website/apps/web/src/components/home/HomeLinks/HomeLinks.tsx
优化友链列表出现消失动画
为底部许可证文本添加动画
修复点击查看全部后按钮乱跳
整理注释
=> feat: 优化官网动画效果

src/MaaWpfGui/Main/Bootstrapper.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> feat: Microsoft VC++可用检查

src/MaaWpfGui/Views/UserControl/Settings/TimerSettingsUserControl.xaml
=> fix: 定时执行tooltip修正

3rdparty/include/meojson/common/array.hpp, 3rdparty/include/meojson/common/exception.hpp, 3rdparty/include/meojson/common/object.hpp, 3rdparty/include/meojson/common/serialization.hpp, 3rdparty/include/meojson/common/types.hpp, 3rdparty/include/meojson/common/utils.hpp, 3rdparty/include/meojson/common/value.hpp, 3rdparty/include/meojson/json.hpp, 3rdparty/include/meojson/json5.hpp, 3rdparty/include/meojson/parser/bitops.hpp, 3rdparty/include/meojson/parser/packed_bytes.hpp, 3rdparty/include/meojson/parser/packed_bytes_arm.hpp, 3rdparty/include/meojson/parser/packed_bytes_x86.hpp, 3rdparty/include/meojson/parser/parser.hpp, 3rdparty/include/meojson/parser5/parser5.hpp, 3rdparty/include/meojson/parser5/unicode.h, 3rdparty/include/meojson/reflection/jsonization.hpp
=> chore: meoJson update to v4.3.4

tools/GetImageFromROI/cutter.py, tools/GetImageFromROI/updater.py
=> fix: 修复GetImageFromROI小工具以适配多文件tasks结构

README.md, docs/zh-cn/readme.md
将文档中的“高姿”改为“高资”
Resolves: #12566
=> docs: 更正主文档和中文文档中的两处错别字

src/MaaWpfGui/Helper/CopilotHelper.cs, src/MaaWpfGui/Helper/ETagCache.cs, src/MaaWpfGui/Models/ResourceUpdater.cs, src/MaaWpfGui/Services/Web/HttpService.cs, src/MaaWpfGui/Services/Web/IHttpService.cs, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/ViewModels/UI/VersionUpdateViewModel.cs
=> refactor: HttpService调整, Post函数追加

src/MaaWpfGui/ViewModels/UserControl/Settings/IssueReportUserControlModel.cs
=> chore: 日志压缩包压缩等级提升

resource/roguelike/Mizuki/recruitment.json, resource/roguelike/Phantom/recruitment.json, resource/roguelike/Sami/recruitment.json, resource/roguelike/Sarkaz/autopilot/卫士不语功.json, resource/roguelike/Sarkaz/recruitment.json
添加了新干员并且补全了老肉鸽缺失六星干员的分数和干员组，分数我不知道我给的合不合适，不行我再改改
顺便改了下卫士不语功的站位
=> feat: 肉鸽适配新干员

resource/roguelike/Sarkaz/autopilot/劳作的清晨.json
=> perf: 添加萨卡兹肉鸽劳作的清晨关卡策略

resource/tasks/tasks.json, src/MaaCore/Task/Infrast/InfrastAbstractTask.cpp, src/MaaCore/Task/Infrast/InfrastAbstractTask.h, src/MaaCore/Task/Infrast/InfrastProductionTask.cpp
=> fix: 修复外服基建干员选择列表无法重置

src/MaaWpfGui/Main/AsstProxy.cs
=> feat: 为Copilot添加土司通知

src/MaaWpfGui/Styles/Controls/TooltipBlock.xaml, src/MaaWpfGui/Styles/Controls/TooltipBlock.xaml.cs, src/MaaWpfGui/Views/UI/CopilotView.xaml, src/MaaWpfGui/Views/UserControl/Settings/VersionUpdateSettingsUserControl.xaml
=> rft: TooltipBlock封装

resource/global/txwy/resource/tasks/tasks.json
ref 
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/673b1b082f344192b510a1a92948a5215c797e12
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/503029581a3949d9423f1a4850022b5d2e96402c
=> chore: update txwy for update infrast training room

resource/global/txwy/resource/tasks/tasks.json
from discord
https://discord.com/channels/1326213891176271934/1326223367161905163/1382428062431318036
```
[2025-06-12 02:20:19.861][TRC][Px2eb0][Tx3dd0] asst::WordOcr [{ 超募助戰: [ 4, 10, 87, 22 ], score: 0.902133 }] by OCR Pipeline , cost 24 ms
[2025-06-12 02:20:19.861][INF][Px2eb0][Tx3dd0] {"class":"asst::ProcessTask","details":{"cur_retry":2,"retry_times":2,"to_be_recognized":["Roguelike@RecruitSupportConfirm"]},"first":["Roguelike@RecruitSupportConfirm"],"pre_task":"","subtask":"ProcessTask","taskchain":"Roguelike","taskid":7}
[2025-06-12 02:20:19.861][TRC][Px2eb0][Tx3dd0] ready to sleep 500
[2025-06-12 02:20:20.362][TRC][Px2eb0][Tx3dd0] end of sleep 500
[2025-06-12 02:20:20.414][TRC][Px2eb0][Tx3dd0] asst::WordOcr [{ 招蔓訪助戰: [ 2, 7, 90, 29 ], score: 0.758330 }] by OCR Pipeline , cost 33 …
```
=> fix: 繁中服 肉鴿助戰可能招募失敗

resource/tasks/Roguelike/base.json
link to 2ed23767637dacb3bb25ed054a1ef0998c8d4b24
cc @DavidWang19
=> fix: 移除Roguelike@GetDrop2中重复的Roguelike@DropsFlag任务

resource/roguelike/Sarkaz/autopilot/机动队.json, resource/roguelike/Sarkaz/autopilot/溃乱魔典.json, resource/roguelike/Sarkaz/autopilot/盲盒广场.json
=> perf: 添加萨卡兹肉鸽 机动队 溃乱魔典 盲盒广场 关卡策略

src/MaaCore/Task/Infrast/InfrastReceptionTask.cpp, src/MaaCore/Task/Infrast/InfrastReceptionTask.h
close #13095 
>拿送的->放->拿每日的->放
=> feat: 优化会客室线索处理逻辑

src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> perf: 干员因模组不可选中时, 加个输出

resource/tasks/Roguelike/base.json
=> fix: 肉鸽导航无法选择傀影肉鸽

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
不知道外服能不能用mumu12或者雷电模拟器
ckecklist:
=> chore: 简中繁中截图耗时过长提示增加截图增强提醒

resource/tasks/Roguelike/JieGarden.json, resource/tasks/Roguelike/Mizuki.json, resource/tasks/Roguelike/Phantom.json, resource/tasks/Roguelike/Sami.json, resource/tasks/Roguelike/Sarkaz.json, resource/tasks/Roguelike/base.json, src/MaaCore/Task/Roguelike/RoguelikeConfig.cpp, src/MaaCore/Task/Roguelike/RoguelikeCustomStartTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeRecruitTaskPlugin.cpp
=> refactor: 肉鸽局内外招募流程拆分

resource/roguelike/Sami/encounter/default.json
address https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8454
=> fix: 萨米肉鸽鲍勃杂货店卡死

src/MaaWpfGui/Res/Localizations/ja-jp.xaml
- 部分关键词改为引用
- 全部方括号改为全角方括号
- 调整几处换行，保证总行数一致
=> i18n: JP edits

resource/tasks/Roguelike/Sarkaz.json
=> fix: RoutingRefreshNode roi expand

resource/custom_infrast/243_layout_4_times_a_day.json, resource/custom_infrast/old/243_layout_4_times_a_day_20250507.json, resource/custom_infrast/old/333_layout_for_Orundum_3_times_a_day_20221219.json
根据公孙长乐 2025-08-06 新视频制作。
Mon3tr -> 斩业星熊
Mon3tr -> Hoshiguma the Breacher
顺便恢复并归档了上一次未归档的旧 333 搓玉排班表。
PS. This likely would be the last PR I make to MAA. After almost five years I got into Arknights, I made the decision last month to stop playing it. It has been a good ride. Therefore I think I would not be in a good position to update these schedules in the future without testing it in real game, if bigger changes than the current one ever come.
Please allow me to express my gratitude to all the devs/contributors of MAA in the past few years. I never thought I would have fun playing with a tool that plays the game itself!
=> feat: 更新 243 极限效率一天四换排班表（20250806 修订）

resource/global/YoStarEN/resource/tasks/tasks.json, resource/global/YoStarJP/resource/tasks/tasks.json, resource/global/YoStarKR/resource/tasks/tasks.json, resource/global/txwy/resource/tasks/tasks.json, resource/tasks/tasks.json
- close #13347 
@MaaAssistantArknights/global-support-team
=> feat: StartUp识别开始唤醒时最开始的完整性检测

.github/workflows/issue-checkbox-checker.yml
=> ci: 关issue+提示，反复提issue+tag

resource/tasks/Roguelike/base.json
=> fix: 移除使用empty.png当JustReturn屎

resource/global/txwy/resource/tasks/Stages/EP.json
=> chore: 繁中服「出蒼白海」導航入口文字調整

resource/tasks/tasks.json, src/MaaCore/Vision/Miscellaneous/DepotImageAnalyzer.cpp, src/MaaWpfGui/Extensions/NumberExtensions.cs, src/MaaWpfGui/Helper/ToolTipHelper.cs, src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/ViewModels/UI/RecognizerViewModel.cs
cc @MaaAssistantArknights/global-support-team 
I tested the Chinese and found the effect was quite good. There shouldn't be any impact on en. For tw, jp, and kr, we need to see the results.
=> perf: 仓库识别改用二值化后的非char模型识别

.github/workflows/blame-ignore.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/gen-changelog.yml, .github/workflows/markdown-checker.yml, .github/workflows/optimize-templates.yml, .github/workflows/pr-auto-tag.yml, .github/workflows/release-nightly-ota.yml, .github/workflows/release-ota.yml, .github/workflows/res-update-game.yml, .github/workflows/smoke-testing.yml, .github/workflows/sync-resource.yml, .github/workflows/website-workflow.yml
Reverts MaaAssistantArknights/MaaAssistantArknights#13648
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/16971563354/job/48141111569
=> Revert "ci: bump the github-actions group in /.github/workflows with 2 updates"

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml, src/MaaWpfGui/Views/UserControl/Settings/VersionUpdateSettingsUserControl.xaml
cc @ABA2396 @Constrat @MaaAssistantArknights/global-support-team
=> perf: 不同更新渠道加个描述

src/MaaCore/Task/Roguelike/Map/RoguelikeBoskyPassageMap.cpp, src/MaaCore/Task/Roguelike/Map/RoguelikeBoskyPassageMap.h, src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp
=> fix: 支持新建关闭状态的节点，并修正日志输出

src/MaaCore/Common/AsstBattleDef.h, src/MaaWpfGui/Models/Copilot/CopilotModel.cs
=> perf: 自动编队干员组显示模组需求

resource/global/txwy/resource/tasks/Roguelike/Mizuki.json, resource/global/txwy/resource/tasks/Roguelike/Sarkaz.json, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
這裡做了兩件事:
1. 跟上 b18d57923b79efeff70c1f245b0606b20ea6d923
2. 調整一下 GUI 上今天開放的薩卡茲 DLC - 1 的分隊名稱
=> chore: 調整繁中服水月、薩卡茲肉鴿相關內容

resource/global/YoStarJP/resource/tasks/Roguelike/base.json, resource/global/YoStarJP/resource/tasks/tasks.json
=> chore: YostarJP remove old navigation

.github/workflows/gen-changelog.yml
=> ci: 更正了生成changelog工作流中debug信息的一处错误

src/MaaWpfGui/Main/AsstProxy.cs, src/MaaWpfGui/Models/TaskSettingVisibilityInfo.cs, src/MaaWpfGui/ViewModels/UI/CopilotViewModel.cs, src/MaaWpfGui/ViewModels/UI/TaskQueueViewModel.cs, src/MaaWpfGui/ViewModels/UserControl/TaskQueue/InfrastSettingsUserControlModel.cs, src/MaaWpfGui/Views/UserControl/TaskQueue/FightSettingsUserControl.xaml, src/MaaWpfGui/Views/UserControl/TaskQueue/InfrastSettingsUserControl.xaml
移除战斗任务及基建任务独立运行状态, link to #12315
=> refactor(wpf): 长草任务运行状态

resource/tasks/RA/Tales.json
=> fix: 允许生息演算任务反复点击存档位置直到画面改变

docs/en-us/protocol/integration.md, docs/ja-jp/protocol/integration.md, docs/ko-kr/protocol/integration.md, docs/zh-cn/protocol/integration.md, docs/zh-tw/protocol/integration.md, src/MaaCore/Task/Interface/CopilotTask.cpp, src/MaaCore/Task/Interface/MallTask.cpp, src/MaaCore/Task/Miscellaneous/CreditFightTask.cpp, src/MaaCore/Task/Miscellaneous/CreditFightTask.h
=> refactor: 维护信用作战相关功能及其文档

src/MaaCore/Controller/MinitouchController.h, src/MaaCore/Task/AbstractTask.cpp, src/MaaCore/Task/BattleHelper.cpp, src/MaaCore/Task/Experiment/CombatRecordRecognitionTask.cpp, src/MaaCore/Task/Fight/FightTimesTaskPlugin.cpp, src/MaaCore/Task/Roguelike/Map/RoguelikeRoutingTaskPlugin.cpp, src/MaaCore/Task/Roguelike/RoguelikeSettlementTaskPlugin.cpp, src/MaaCore/Utils/Logger.hpp, src/MaaCore/Utils/Time.hpp, src/MaaCore/Vision/Battle/BattlefieldClassifier.cpp, src/MaaCore/Vision/Matcher.cpp, src/MaaCore/Vision/VisionHelper.cpp
=> refactor: use std::format instead of sprintf

src/MaaCore/Common/AsstBattleDef.h, src/MaaCore/Task/Interface/CopilotTask.cpp, src/MaaCore/Task/Miscellaneous/BattleFormationTask.cpp, src/MaaCore/Task/Miscellaneous/BattleFormationTask.h
- close #10849 
只做了1页的支持（10人，右边俩被UI挡了回退到普通逻辑凑合一下
=> feat: 自动战斗多作业支持保存干员组内编入的干员

.github/workflows/release-ota.yml
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/17725188293
boom again :(
=> ci: use download-artifact v4

resource/tasks/Roguelike/base.json
肉鸽通关后有概率无法跳过卡在Roguelike@ClickToStartPoint里
=> fix: 肉鸽在结算界面卡死

src/MaaWpfGui/Res/Localizations/en-us.xaml, src/MaaWpfGui/Res/Localizations/ja-jp.xaml, src/MaaWpfGui/Res/Localizations/ko-kr.xaml, src/MaaWpfGui/Res/Localizations/zh-cn.xaml, src/MaaWpfGui/Res/Localizations/zh-tw.xaml
=> refactor: 重写完成后动作仅一次的ui字符串
